### ISSUE TITLE
Updating to >= 2.11.0 is breaking with some python3 libs

### ISSUE THREAD

**Issue by ecarruda** [DataDog/dd-trace-py#10314]
### Which version of dd-trace-py are you using?
2.11.0 and 2.11.1 is breaking
2.10.6 is working good

### Which version of pip are you using?
22.0.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
annotated-types==0.7.0
anyio==4.4.0
attrs==24.2.0
autocommand==2.2.2
babel==2.16.0
backports.tarfile==1.2.0
boto3==1.35.2
botocore==1.35.2
Brotli==1.1.0
bytecode==0.15.1
cattrs==23.2.3
certifi==2024.7.4
charset-normalizer==3.3.2
cheroot==10.0.1
CherryPy==18.10.0
click==8.1.7
cramjam==2.8.3
ddsketch==3.0.1
ddtrace==2.11.1
Deprecated==1.2.14
dnspython==2.6.1
envier==0.5.2
et-xmlfile==1.1.0
exceptiongroup==1.2.2
geojson==3.1.0
gevent==24.2.1
greenlet==3.0.3
gunicorn==23.0.0
h11==0.14.0
httptools==0.6.1
idna==3.7
importlib_metadata==8.0.0
jaraco.collections==5.0.1
jaraco.context==6.0.1
jaraco.functools==4.0.2
jaraco.text==4.0.0
jmespath==1.0.1
Js2Py==0.74
mistune==3.0.2
more-itertools==10.4.0
mutagen==1.47.0
numpy==2.1.0
openpyxl==3.1.5
opentelemetry-api==1.26.0
packaging==24.1
pdfkit==1.0.0
pillow==10.4.0
portend==3.2.0
protobuf==5.27.3
pycryptodomex==3.20.0
pydantic==2.8.2
pydantic-settings==2.4.0
pydantic_core==2.20.1
pyfcm==1.5.4
pyjsparser==2.7.1
PyJWT==2.9.0
pymongo==4.8.0
pyotp==2.9.0
pypng==0.20220715.0
PyQRCode==1.2.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-snappy==0.7.2
pytz==2024.1
PyYAML==6.0.2
requests==2.32.3
s3transfer==0.10.2
sentry-sdk==2.13.0
setproctitle==1.3.3
shapely==2.0.6
six==1.16.0
sniffio==1.3.1
tempora==5.7.0
Tenjin==1.1.1
typing_extensions==4.12.2
tzlocal==5.2
urllib3==2.2.2
uvicorn==0.30.6
uvloop==0.20.0
watchfiles==0.23.0
websockets==13.0
wrapt==1.16.0
XlsxWriter==3.2.0
xmltodict==0.13.0
yt-dlp==2024.8.6
zc.lockfile==3.0.post1
zipp==3.20.0
zope.event==5.0
zope.interface==7.0.1
</details>

### How can we reproduce your problem?
With cherrypy application using gunicorn to run with lib yl-dlp

### What is the result that you get?
[2024-08-21 03:51:17 +0000] [59888] [INFO] Worker exiting (pid: 59888)
[2024-08-21 03:51:17 +0000] [59892] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/venvs/adm2/lib/python3.10/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/opt/venvs/adm2/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 94, in init_process
    super().init_process()
  File "/opt/venvs/adm2/lib/python3.10/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/opt/venvs/adm2/lib/python3.10/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/venvs/adm2/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/opt/venvs/adm2/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/opt/venvs/adm2/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/adm/current/app.py", line 172, in <module>
    app = cherrypy.tree.mount(kit.App(), "", config=adm_config)
  File "/opt/adm/current/c/kit.py", line 765, in __init__
    self._load_modules()
  File "/opt/adm/current/c/kit.py", line 774, in _load_modules
    __import__(f"c.{mms}", fromlist=["c"]), mms.capitalize()
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 305, in _exec_module
    self.loader.exec_module(module)
  File "/opt/adm/current/c/missions.py", line 28, in <module>
    from yt_dlp import YoutubeDL
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 305, in _exec_module
    self.loader.exec_module(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/__init__.py", line 17, in <module>
    from .compat import compat_os_name, compat_shlex_quote
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 312, in _exec_module
    self.call_back(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 203, in call_back
    module.spec.loader = self.loader
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 54, in __getattr__
    ret = from_child(attr)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 68, in from_child
    child = importlib.import_module(child, parent.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 312, in _exec_module
    self.call_back(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 203, in call_back
    module.spec.loader = self.loader
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 54, in __getattr__
    ret = from_child(attr)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 68, in from_child
    child = importlib.import_module(child, parent.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 305, in _exec_module
    self.loader.exec_module(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/_legacy.py", line 38, in <module>
    from ..networking.exceptions import HTTPError as compat_HTTPError  # noqa: F401
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 305, in _exec_module
    self.loader.exec_module(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/networking/__init__.py", line 4, in <module>
    from .common import (
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 305, in _exec_module
    self.loader.exec_module(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 16, in <module>
    from ._helper import make_ssl_context, wrap_request_errors
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 305, in _exec_module
    self.loader.exec_module(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/networking/_helper.py", line 13, in <module>
    from .exceptions import RequestError, UnsupportedRequest
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 305, in _exec_module
    self.loader.exec_module(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/networking/exceptions.py", line 5, in <module>
    from ..utils import YoutubeDLError
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 312, in _exec_module
    self.call_back(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 203, in call_back
    module.spec.loader = self.loader
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 54, in __getattr__
    ret = from_child(attr)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 68, in from_child
    child = importlib.import_module(child, parent.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 312, in _exec_module
    self.call_back(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 203, in call_back
    module.spec.loader = self.loader
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 54, in __getattr__
    ret = from_child(attr)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/compat/compat_utils.py", line 68, in from_child
    child = importlib.import_module(child, parent.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/ddtrace/internal/module.py", line 305, in _exec_module
    self.loader.exec_module(module)
  File "/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/utils/_legacy.py", line 15, in <module>
    from ..networking._helper import make_ssl_context
ImportError: cannot import name 'make_ssl_context' from partially initialized module 'yt_dlp.networking._helper' (most likely due to a circular import) (/opt/venvs/adm2/lib/python3.10/site-packages/yt_dlp/networking/_helper.py)

### What is the result that you expected?
All working good, and downgrading dd-trace to 2.10.6 it works good.

**Comment by Tenzer** [comment]
We see the same issue, this is the stack trace from the point at which the yt_dlp library is imported, with ddtrace v2.11.1:

<details>
<summary>Stack trace</summary>

```
Traceback (most recent call last):
  [...]
  File "/home/runner/work/project/code.py", line 14, in <module>
    import yt_dlp
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 309, in _exec_module
    self.loader.exec_module(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/__init__.py", line 17, in <module>
    from .compat import compat_os_name
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 316, in _exec_module
    self.call_back(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 204, in call_back
    module.spec.loader = self.loader
    ^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 54, in __getattr__
    ret = from_child(attr)
          ^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 68, in from_child
    child = importlib.import_module(child, parent.__name__)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 316, in _exec_module
    self.call_back(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 204, in call_back
    module.spec.loader = self.loader
    ^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 54, in __getattr__
    ret = from_child(attr)
          ^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 68, in from_child
    child = importlib.import_module(child, parent.__name__)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 309, in _exec_module
    self.loader.exec_module(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/_legacy.py", line 38, in <module>
    from ..networking.exceptions import HTTPError as compat_HTTPError
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 309, in _exec_module
    self.loader.exec_module(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/networking/__init__.py", line 4, in <module>
    from .common import (
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 309, in _exec_module
    self.loader.exec_module(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 16, in <module>
    from ._helper import make_ssl_context, wrap_request_errors
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 309, in _exec_module
    self.loader.exec_module(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/networking/_helper.py", line 13, in <module>
    from .exceptions import RequestError, UnsupportedRequest
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 309, in _exec_module
    self.loader.exec_module(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/networking/exceptions.py", line 5, in <module>
    from ..utils import YoutubeDLError
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 316, in _exec_module
    self.call_back(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 204, in call_back
    module.spec.loader = self.loader
    ^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 54, in __getattr__
    ret = from_child(attr)
          ^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 68, in from_child
    child = importlib.import_module(child, parent.__name__)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 316, in _exec_module
    self.call_back(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 204, in call_back
    module.spec.loader = self.loader
    ^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 54, in __getattr__
    ret = from_child(attr)
          ^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/compat/compat_utils.py", line 68, in from_child
    child = importlib.import_module(child, parent.__name__)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/ddtrace/internal/module.py", line 309, in _exec_module
    self.loader.exec_module(module)
  File "/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/utils/_legacy.py", line 15, in <module>
    from ..networking._helper import make_ssl_context
ImportError: cannot import name 'make_ssl_context' from partially initialized module 'yt_dlp.networking._helper' (most likely due to a circular import) (/home/runner/.cache/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/yt_dlp/networking/_helper.py)
```

</details>

**Comment by P403n1x87** [comment]
@Tenzer thanks for sharing. We have merged a fix that should resolve this issue. It will be available with the next patch releases

**Comment by Tenzer** [comment]
I can confirm vresion 2.12.0 fixes this again.
