### ISSUE TITLE
Get `execv: path should be string, bytes or os.PathLike, not NoneType` error when run it on MacOS

### ISSUE THREAD

**Issue by zhaoyi0113** [DataDog/dd-trace-py#1032]
I am using `python 3.7.2` with `uwsgi` and `ddtrace` but I got this error when launching the application:

```
Traceback (most recent call last):
  File "/Users/joey/.pyenv/versions/3.7.2/bin/ddtrace-run", line 10, in <module>
    sys.exit(main())
  File "/Users/joey/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ddtrace/commands/ddtrace_run.py", line 82, in main
    os.execl(executable, executable, *sys.argv[2:])
  File "/Users/joey/.pyenv/versions/3.7.2/lib/python3.7/os.py", line 539, in execl
    execv(file, args)
TypeError: execv: path should be string, bytes or os.PathLike, not NoneType
```

The launch script is 
```
ddtrace-run uwsgi \
  --uid uwsgi \
  --master \
  --plugins http,python3,stats_pusher_statsd \
  --http :8080 \
  --buffer-size 32768 \
  --enable-threads \
  --stats-push statsd:127.0.0.1:8125,${APP_NAME} \
  --wsgi-file api/uwsgi.py
```

The same setting works fine on `ubuntu` system but not on Mac. My Mac version is `10.14.6`.

**Comment by jd** [comment]
I suspect `ddtrace-run` is not finding `uwsgi`. Is `uwsgi` accessible from your `PATH` env var and from your shell?

**Comment by zhaoyi0113** [comment]
I am able to find `ddtrace-run` on PATH:
```
$ which ddtrace-run
/Users/joey/.pyenv/shims/ddtrace-run
```

**Comment by jd** [comment]
That I knew since it's the one printing the error. Is the same true for `uwsgi`?

**Comment by zhaoyi0113** [comment]
I think it is something wrong with uwsgi not ddtrace, thanks. Close it.
