### ISSUE TITLE
Pymongo 4.9+ doesn't compatible with current ddtrace-py

### ISSUE THREAD

**Issue by kimwonj77** [DataDog/dd-trace-py#10714]
### Summary of problem
There's no problem with pymongo 4.8.0 but after intialize new project with 4.9.1, got this error :
```
failed to import ddtrace module 'ddtrace.contrib.pymongo' when patching on import
Traceback (most recent call last):
  File "<redacted>/.venv/lib/python3.11/site-packages/ddtrace/_monkey.py", line 165, in on_import
    imported_module = importlib.import_module(path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.rye/py/cpython@3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<redacted>/.venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 309, in _exec_module
    self.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<redacted>/.venv/lib/python3.11/site-packages/ddtrace/contrib/pymongo/__init__.py", line 46, in <module>
    from . import patch as _  # noqa: F401, I001
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<redacted>/.venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 309, in _exec_module
    self.loader.exec_module(module)
  File "<redacted>/.venv/lib/python3.11/site-packages/ddtrace/contrib/pymongo/patch.py", line 1, in <module>
    from ..internal.pymongo.patch import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<redacted>/.venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 309, in _exec_module
    self.loader.exec_module(module)
  File "<redacted>/.venv/lib/python3.11/site-packages/ddtrace/contrib/internal/pymongo/patch.py", line 39, in <module>
    _VERIFY_VERSION_CLASS = pymongo.pool.SocketInfo if _VERSION < (4, 5) else pymongo.pool.Connection
                                                                              ^^^^^^^^^^^^
AttributeError: partially initialized module 'pymongo' has no attribute 'pool' (most likely due to a circular import)
```

### Which version of dd-trace-py are you using?
2.12.2

### Which version of pip are you using?
pip 24.0

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  pymongo>=4.8.0
</details>

### How can we reproduce your problem?
`patch_all` with pymongo 4.9.1

### What is the result that you get?
got error. see the summary

### What is the result that you expected?
no error.

**Comment by mabdinur** [comment]
Hi @kimwonj77, 

Thanks for opening this issue. I was able to reproduce this error with the following steps: 
```
pip install ddtrace==2.11.6 pymongo==4.9.1
python -c "import ddtrace; ddtrace.patch_all(pymongo=True); import pymongo"
```

In v4.9.0 pymongo modules were significantly refactored. For example: 
- [pymongo/pool.py was moved to pymongo/synchronous/pool.py](https://github.com/mongodb/mongo-python-driver/commit/3280769d6fec1340f21bb9a407037fe0c618ffb3)
- [pymongo/topology.py was moved to pymongo/synchronous/topology.py](https://github.com/mongodb/mongo-python-driver/commit/d6bf0e1e78c3287149ef56d9718bb6098aa6e41f#diff-0e6696523331053584c87cbd2efe458b0d05b04bc14a914d53b70c4f84164f9d)
- [pymongo/server.py was moved to pymongo/synchronous/server.py](https://github.com/mongodb/mongo-python-driver/pull/1629/files#diff-ba452a1a1e401e807ab6c3ef0fa7ceb7e79123bc30848762ca5d8e7aa4efa856)
After these changes importing the pymongo module and accessing the pool attribute (ex: `import pymongo; pymongo.pool`) now raises an AttributeError. This prevents our pymongo integration from being enabled. I opened a PR to address this issue: https://github.com/DataDog/dd-trace-py/pull/10718.

**Comment by quinna-h** [comment]
Resolved by #10718

**Comment by iherasymenko** [comment]
Linking for traceability. 2.14.0 cannot be used due to another issue https://github.com/DataDog/dd-trace-py/issues/11287
