### ISSUE TITLE
Exception raised with sizeof of some spans

### ISSUE THREAD

**Issue by jd** [DataDog/dd-trace-py#1079]
With `master`:

```
Exception in thread AgentWriter:
Traceback (most recent call last):
  File "/opt/dogweb/pyenv/versions/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/dogweb/pyenv/versions/2.7.12/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/dogweb/lib/python2.7/site-packages/ddtrace/_worker.py", line 67, in _target
    self.run_periodic()
  File "/opt/dogweb/lib/python2.7/site-packages/ddtrace/internal/writer.py", line 65, in flush_queue
    traces_queue_size = sum(map(sizeof.sizeof, traces))
  File "/opt/dogweb/lib/python2.7/site-packages/ddtrace/utils/sizeof.py", line 31, in sizeof
    return _sizeof(o)
  File "/opt/dogweb/lib/python2.7/site-packages/ddtrace/utils/sizeof.py", line 29, in _sizeof
    return sys.getsizeof(o) + sum(map(_sizeof, iter_object(o)))
  File "/opt/dogweb/lib/python2.7/site-packages/ddtrace/utils/sizeof.py", line 29, in _sizeof
    return sys.getsizeof(o) + sum(map(_sizeof, iter_object(o)))
  File "/opt/dogweb/lib/python2.7/site-packages/ddtrace/utils/sizeof.py", line 29, in _sizeof
    return sys.getsizeof(o) + sum(map(_sizeof, iter_object(o)))
  File "/opt/dogweb/lib/python2.7/site-packages/ddtrace/utils/sizeof.py", line 29, in _sizeof
    return sys.getsizeof(o) + sum(map(_sizeof, iter_object(o)))
  File "/opt/dogweb/lib/python2.7/site-packages/ddtrace/utils/sizeof.py", line 29, in _sizeof
    return sys.getsizeof(o) + sum(map(_sizeof, iter_object(o)))
  File "/opt/dogweb/lib/python2.7/site-packages/ddtrace/utils/sizeof.py", line 8, in <genexpr>
    return (getattr(o, slot) for slot in o.__slots__)
AttributeError: rate_limit
```

Might be an issue where the attribute is declared in `__slots__` but not set.

**Comment by brettlangdon** [comment]
This is weird, the only two classes that have a `rate_limit` are `ddtrace.internal.rate_limiter.RateLimiter` and `ddtrace.internal.logger.DDLogger`

however, in both cases it should have been initialized.

**Comment by brettlangdon** [comment]
I mean, the `__init__` of both of those classes set `self.rate_limit`

**Comment by jd** [comment]
`DatadogSampler` has a slot with `rate_limit` but never sets it I think:
https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/sampler.py#L116
