### ISSUE TITLE
Sporadic crashes: gevent.exceptions.LoopExit: This operation would block forever

### ISSUE THREAD

**Issue by camgraff** [DataDog/dd-trace-py#10984]
I am seeing sporadic crashes during startup in an app using flask, gunicorn w/ gevent workers, and `ddtrace-run` deployed on kubernetes. The crashes are very inconsistent and I haven't found a way to reliably reproduce them. Usually, the pod is able to start successfully on the next restart after hitting this error.

Relevant library versions:

python=3.11.7

```
Flask                                  2.3.3 
datadog                             0.50.1
ddtrace                              2.14.2
gevent                               24.2.1
gunicorn                            22.0.0
```

env vars:
```
DD_PROFILING_ENABLED=true
DD_APPSEC_ENABLED=false
DD_PROFILING_STACK_V2_ENABLED=true
DD_PROFILING_EXPORT_LIBDD_ENABLED=true
DD_LOGS_INJECTION=true
DD_RUNTIME_METRICS_ENABLED=true
```

Stack trace:
```
Using 20 workers, with 300 second timeouts.
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/module.py", line 295, in _exec_module
    self.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/router/patched.py", line 5, in <module>
    from router.server import create_app
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/module.py", line 295, in _exec_module
    self.loader.exec_module(module)
  File "/app/router/server.py", line 10, in <module>
    from router.routes import bp
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/module.py", line 295, in _exec_module
    self.loader.exec_module(module)
  File "/app/router/routes.py", line 14, in <module>
    from router.utils import (
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/module.py", line 295, in _exec_module
    self.loader.exec_module(module)
  File "/app/router/utils.py", line 4, in <module>
    from datadog import statsd
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/module.py", line 295, in _exec_module
    self.loader.exec_module(module)
  File "/usr/local/lib/python3.11/site-packages/datadog/__init__.py", line 20, in <module>
    from datadog import api
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/module.py", line 295, in _exec_module
    self.loader.exec_module(module)
  File "/usr/local/lib/python3.11/site-packages/datadog/api/__init__.py", line 27, in <module>
    from datadog.api.comments import Comment
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/module.py", line 295, in _exec_module
    self.loader.exec_module(module)
  File "/usr/local/lib/python3.11/site-packages/datadog/api/comments.py", line 4, in <module>
    from datadog.api.resources import CreateableAPIResource, UpdatableAPIResource
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/module.py", line 295, in _exec_module
    self.loader.exec_module(module)
  File "/usr/local/lib/python3.11/site-packages/datadog/api/resources.py", line 8, in <module>
    from datadog.api.api_client import APIClient
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/module.py", line 295, in _exec_module
    self.loader.exec_module(module)
  File "/usr/local/lib/python3.11/site-packages/datadog/api/api_client.py", line 14, in <module>
    from datadog.util.compat import is_p3k
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/module.py", line 295, in _exec_module
    self.loader.exec_module(module)
  File "/usr/local/lib/python3.11/site-packages/datadog/util/compat.py", line 66, in <module>
    from asyncio import iscoroutinefunction
  File "<frozen importlib._bootstrap>", line 224, in _lock_unlock_module
  File "<frozen importlib._bootstrap>", line 120, in acquire
  File "/usr/local/lib/python3.11/site-packages/gevent/thread.py", line 112, in acquire
    acquired = BoundedSemaphore.acquire(self, blocking, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/gevent/_semaphore.py", line 184, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 263, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 253, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
```

**Comment by camgraff** [comment]
this turned out to be caused by manually calling `gevent.monkey.patch_all()` when [`gunicorn` already does this](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/ggevent.py#L38). Removing the duplicate call eliminated the crashes.
