### ISSUE TITLE
Python pytest unit test interaction with ddtrace.tracer.wrap: (port 8126)

### ISSUE THREAD

**Issue by jovlinger-numerated** [DataDog/dd-trace-py#11166]
(first of all this feels like a faq, but google tells me it isn't. Sorry if indeed it is)

I have happily instrumented some of my code with `ddtrace.tracer.wrap`. 

But when I try to run pytest unit tests against that code, the tests pass, but on tear-down the test-runner complains of not being able to submit traces like below. 

How can I inhibit this behavior when running tests?

thanks 

-- johan

```
Traceback (most recent call last):
  File "/Users/johan.ovlinger/.pyenv/versions/3.10.14/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/Users/johan.ovlinger/Projects/venvs/opp_python3/lib/python3.10/site-packages/ddtrace/internal/writer/writer.py", line 412, in on_shutdown
    self.periodic()
  File "/Users/johan.ovlinger/Projects/venvs/opp_python3/lib/python3.10/site-packages/ddtrace/internal/writer/writer.py", line 400, in periodic
    self.flush_queue(raise_exc=False)
  File "/Users/johan.ovlinger/Projects/venvs/opp_python3/lib/python3.10/site-packages/ddtrace/internal/writer/writer.py", line 364, in flush_queue
    self._flush_queue_with_client(client, raise_exc=raise_exc)
  File "/Users/johan.ovlinger/Projects/venvs/opp_python3/lib/python3.10/site-packages/ddtrace/internal/writer/writer.py", line 389, in _flush_queue_with_client
    log.error(
  File "/Users/johan.ovlinger/.pyenv/versions/3.10.14/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/Users/johan.ovlinger/.pyenv/versions/3.10.14/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/Users/johan.ovlinger/Projects/venvs/opp_python3/lib/python3.10/site-packages/ddtrace/internal/logger.py", line 176, in handle
    super(DDLogger, self).handle(record)
Message: 'failed to send, dropping %d traces to intake at %s after %d retries'
Arguments: (3, 'http://localhost:8126/v0.5/traces', 3)
```

**EDIT** python 3.10 as you see and ddtrace 2.14.2

**Comment by jovlinger-numerated** [comment]
ping?

**Comment by taegyunkim** [comment]
Hi Johan,

Looks like your tests are not run with a datadog agent configured.

**Comment by mabdinur** [comment]
Hi, @jovlinger-numerated,

You can run your tests with the following environment variable: `DD_TRACE_ENABLED=False`. This will ensure spans are created but not sent. This should resolve the connection errors you are seeing in your tests.
