### ISSUE TITLE
[BUG]: KeyError: 'signals'

### ISSUE THREAD

**Issue by Omar-Bishtawi** [DataDog/dd-trace-py#11825]
### Tracer Version(s)

ddtrace==2.17.3

### Python Version(s)

Python 3.11.6

### Pip Version(s)

24.3.1

### Bug Report

sometimes without a clear pattern, or clear reproduction steps . we get the following error: 
```
Traceback (most recent call last):
  File "/var/python/venv/lib64/python3.11/site-packages/ddtrace/debugging/_debugger.py", line 266, in __return__
    self._close_signals(retval=value)
  File "/var/python/venv/lib64/python3.11/site-packages/ddtrace/debugging/_debugger.py", line 238, in _close_signals
    signals = cast(Deque[Signal], self.get("signals"))
                                  ^^^^^^^^^^^^^^^^^^^
  File "/var/python/venv/lib64/python3.11/site-packages/ddtrace/internal/wrapping/context.py", line 286, in get
    return self._storage_stack.get()[-1][key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'signals'
```

It doesn't cause any behavioral issues on the application or in APM. 

we started to notice this issue more when we enabled Dynamic instrumentation (might be correlated and might not)

**Comment by P403n1x87** [comment]
@Omar-Bishtawi thanks for reporting this. As you have noticed, this should not cause any issues to the application itself (the only nag is the extra noise in logs). We would like to get an understanding of why this might be happening to see if we can reduce the noise, and for this I would like to know if you see any lines in the logs that mention `Failed to open debugging contexts`, together with a traceback 🙏
