### ISSUE TITLE
Missing module intervaltree when trying to use the profiler.

### ISSUE THREAD

**Issue by xarg** [DataDog/dd-trace-py#1273]
### Which version of dd-trace-py are you using?

0.35.0 -> installed using pipenv on macos 10.15.3 (19D76)

### Which version of the libraries are you using?

No other libs, it's standalone.

### How can we reproduce your problem?

The zipfile with the entire folder below: https://drive.google.com/file/d/1x50VoyyoA29mhKRDU9AH92qj7Fk_HEvQ/view?usp=sharing

To reproduce it: `pipenv install` then `python profile_test.py`.

```
(ddprofile) a@m6 ddprofile % cat Pipfile
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
ddtrace = "==0.35.0"

[requires]
python_version = "3.7"
(ddprofile) a@m6 ddprofile % cat profile_test.py
from ddtrace.profile import profiler

prof = profiler.Profiler()
prof.start()
prof.stop()

(ddprofile) a@m6 ddprofile % python profile_test.py
Traceback (most recent call last):
  File "profile_test.py", line 1, in <module>
    from ddtrace.profile import profiler
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 215, in wrapped_find_and_load_unlocked
    return exec_and_call_hooks(module_name, wrapped, args, kwargs)
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 171, in exec_and_call_hooks
    return wrapped(*args, **kwargs)
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/profile/profiler.py", line 12, in <module>
    from ddtrace.profile.exporter import file
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 215, in wrapped_find_and_load_unlocked
    return exec_and_call_hooks(module_name, wrapped, args, kwargs)
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 171, in exec_and_call_hooks
    return wrapped(*args, **kwargs)
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/profile/exporter/file.py", line 5, in <module>
    from ddtrace.profile.exporter import pprof
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 215, in wrapped_find_and_load_unlocked
    return exec_and_call_hooks(module_name, wrapped, args, kwargs)
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 171, in exec_and_call_hooks
    return wrapped(*args, **kwargs)
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/profile/exporter/pprof.py", line 13, in <module>
    from ddtrace.profile import _line2def
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 215, in wrapped_find_and_load_unlocked
    return exec_and_call_hooks(module_name, wrapped, args, kwargs)
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 171, in exec_and_call_hooks
    return wrapped(*args, **kwargs)
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/profile/_line2def.py", line 4, in <module>
    import intervaltree
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 215, in wrapped_find_and_load_unlocked
    return exec_and_call_hooks(module_name, wrapped, args, kwargs)
  File "/Users/a/.local/share/virtualenvs/ddprofile-EOrU_c0p/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 171, in exec_and_call_hooks
    return wrapped(*args, **kwargs)
ModuleNotFoundError: No module named 'intervaltree'
(ddprofile) a@m6 ddprofile % python --version
Python 3.7.6
```
### What is the result that you get?

See the traceback above.

### What is result that you expected?

Noop

**Comment by majorgreys** [comment]
Based on the included `Pipfile`, it seems `ddtrace` was not installed with the optional extras for the profiler as described in http://pypi.datadoghq.com/trace/docs/installation_quickstart.html?highlight=profile#id1.

As I tried to reproduce this issue, I found some issues with the currently deployed wheels which we will need to address. 

For now you can build the module from the git repository, as so:

```
pipenv install git+https://github.com/datadog/dd-trace-py@v0.35.0#egg=ddtrace[profile]
```

**Comment by xarg** [comment]
Indeed that fixes it. Ideally this doc gets updated as well: https://github.com/DataDog/dd-trace-py/blob/master/docs/basic_usage.rst#profiler - it doesn't contain the install instructions.

**Comment by liorbrauer** [comment]
I'm having a similar issue after trying to add the auto profiler by adding `import ddtrace.profiling.auto`. When the app starts (python version `3.6.10`, dd-trace version `0.38.1`), I am getting the `ModuleNotFoundError: No module named 'intervaltree'` error as well.

Am i missing the same `OpenTracing` version? it doesn't say anything about that in this guide: https://docs.datadoghq.com/tracing/profiler/getting_started/?tab=python

**Comment by jd** [comment]
Hi @liorbrauer,

Keep in mind the guide is for the latest version, that's why it might not work.

In your case, you might be missing the `[profiling]` flavor on install as described in https://github.com/DataDog/dd-trace-py/issues/1273#issuecomment-598956671

You want to do `pip install ddtrace[profiling]==0.38.1`.
