### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by brycereynolds** [DataDog/dd-trace-py#132]
We are getting this while using just `@tracer.wrap()`.

Agent is running as well as the tracer-agent. Anything else we should be setting up here?

```
error sending spans 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.4/dist-packages/ddtrace/writer.py", line 120, in _target 
    self.api.send_traces(traces) 
  File "/usr/local/lib/python3.4/dist-packages/ddtrace/api.py", line 47, in send_traces 
  File "/usr/local/lib/python3.4/dist-packages/ddtrace/api.py", line 78, in _put 
    response = self._put(self._traces, data) 
  File "/usr/lib/python3.4/http/client.py", line 1125, in request 
    conn.request("PUT", endpoint, data, self._headers) 
    self._send_request(method, url, body, headers) 
  File "/usr/lib/python3.4/http/client.py", line 1163, in _send_request 
    self.endheaders(body) 
  File "/usr/lib/python3.4/http/client.py", line 951, in _send_output 
  File "/usr/lib/python3.4/http/client.py", line 1121, in endheaders 
    self._send_output(message_body) 
    self.send(msg) 
    self.connect() 
  File "/usr/lib/python3.4/http/client.py", line 863, in connect 
  File "/usr/lib/python3.4/http/client.py", line 886, in send 
  File "/usr/lib/python3.4/socket.py", line 512, in create_connection 
    self.timeout, self.source_address) 
    raise err 
  File "/usr/lib/python3.4/socket.py", line 503, in create_connection 
    sock.connect(sa) 
ConnectionRefusedError: [Errno 111] Connection refused 
```

**Comment by handigarde** [comment]
@brycereynolds it looks like the problem may be something happening within the trace-agent. We can take a look on our end - could you send your /var/log/datadog/trace-agent.log to support@datadoghq.com so we can investigate?

**Comment by clutchski** [comment]
Please re-open if there's more details.
