### ISSUE TITLE
Import errors when trying to use profiler

### ISSUE THREAD

**Issue by lumberj** [DataDog/dd-trace-py#1328]
Thanks for taking the time for reporting an issue!

Before reporting an issue on dd-trace-py, please be sure to provide all
necessary information.

If you're hitting a bug, make sure that you're using the latest version of this
library.

### Which version of dd-trace-py are you using?
0.35.0

### Which version of the libraries are you using?

```
alembic==1.0.3
analytics-python==1.2.9
aniso8601==7.0.0
asn1crypto==1.2.0
Authlib==0.6
awscli==1.16.186
Babel==1.3
backoff==1.6.0
bcrypt==3.1.4
bleach==3.1.4
blinker==1.3
boto3==1.9.176
botocore==1.12.176
boxsdk==1.5.5
cachetools==2.0.1
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
click-log==0.3.2
colorama==0.3.9
cryptography==2.7
datadog==0.35.0
ddtrace==0.35.0
decorator==4.4.1
defusedxml==0.5.0
docutils==0.14
expiringdict==1.2.0
Flask==1.1.1
Flask-Caching==1.8.0
Flask-GraphQL==2.0.0
Flask-Login==0.4.1
Flask-Script==2.0.6
Flask-Session==0.3.1
Flask-SQLAlchemy==2.4.1
Flask-WTF==0.14
freezegun==0.3.5
google-api-python-client==1.6.5
google-auth==1.4.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.2.0
graphene==2.1.8
graphql-core==2.2.1
graphql-relay==2.0.0
graphql-server-core==1.1.3
holidays==0.3.1
html5lib==1.0.1
httplib2==0.11.0
httpretty==0.9.5
humanize==0.5.1
idna==2.6
ijson==2.3
iso8601==0.1
isodate==0.5.0
itsdangerous==0.24
Jinja2==2.10.3
jira==2.0.0
jmespath==0.9.3
jsondiff==1.1.2
launchdarkly-server-sdk==6.9.3
lxml==4.5.0
Mako==1.1.0
MarkupSafe==1.1.1
marshmallow==3.0.0rc3
MonthDelta==0.9.1
msgpack==1.0.0
mysqlclient==1.4.6
oauth2client==4.1.2
oauthlib==2.0.7
pathspec==0.6.0
pbr==5.4.4
Pillow==6.2.0
pkgconfig==1.5.1
promise==2.3
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.19
PyJWT==1.7.1
pyRFC3339==1.1
pysnow==0.7.4
python-dateutil==2.7.5
python-editor==1.0.4
python-json-logger==0.1.10
python-slugify==1.2.4
python3-saml==1.8.0
pytoml==0.1.21
pytz==2015.2
PyYAML==5.1
redis==3.3.11
requests==2.20.0
requests-oauthlib==0.8.0
requests-toolbelt==0.8.0
rsa==3.4.2
Rx==1.6.1
s3transfer==0.2.1
semver==2.9.0
sentry-sdk==0.14.3
sh==1.11
simplejson==3.16.0
six==1.13.0
SQLAlchemy==1.3.11
sqlalchemy-easy-profile==1.0.2
sqlparse==0.3.0
tabulate==0.8.3
tlslite==0.4.6
Unidecode==1.0.22
uritemplate==3.0.0
urllib3==1.24.3
uWSGI==2.0.17.1
uwsgi-tools==1.1.1
webargs==5.1.3
webencodings==0.5.1
Werkzeug==0.16.0
wrapt==1.11.1
WTForms==2.0.2
xmlsec==1.3.3
xmltodict==0.12.0
yamllint==1.11.1
yasha==4.3
zipstreamer==0.1.3
```

### How can we reproduce your problem?

```
import ddtrace.profile.auto
```

### What is the result that you get?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 215, in wrapped_find_and_load_unlocked
    return exec_and_call_hooks(module_name, wrapped, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 171, in exec_and_call_hooks
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ddtrace/profile/auto.py", line 2, in <module>
    from ddtrace.profile.bootstrap import sitecustomize  # noqa
  File "/usr/local/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 215, in wrapped_find_and_load_unlocked
    return exec_and_call_hooks(module_name, wrapped, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 171, in exec_and_call_hooks
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ddtrace/profile/bootstrap/sitecustomize.py", line 7, in <module>
    from ddtrace.profile import profiler
  File "/usr/local/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 215, in wrapped_find_and_load_unlocked
    return exec_and_call_hooks(module_name, wrapped, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/ddtrace/internal/import_hooks.py", line 171, in exec_and_call_hooks
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ddtrace/profile/profiler.py", line 10, in <module>
    from ddtrace.profile.collector import stack
ImportError: cannot import name 'stack' from 'ddtrace.profile.collector' (/usr/local/lib/python3.7/site-packages/ddtrace/profile/collector/__init__.py)

### What is the result that you expected?

Not an exception

**Comment by jd** [comment]
Hi,

It looks like the extension has not been compiled. How did you install the library?

**Comment by lumberj** [comment]
Following the normal instructions, 

```
pip install ddtrace[profile]==0.35.0
```

This is being tested in an Alpine Linux container

**Comment by lumberj** [comment]
So this definitely looks like an issue with building in Alpine Linux:

In python:3.7 (Debian)

```
docker run -it --rm python:3.7 bash
root@10a961d023a2:/# pip install ddtrace[profile]==0.36.0
Collecting ddtrace[profile]==0.36.0
  Downloading ddtrace-0.36.0-cp37-cp37m-manylinux2010_x86_64.whl (891 kB)
     |████████████████████████████████| 891 kB 4.9 MB/s
Collecting msgpack>=0.5.0
  Downloading msgpack-1.0.0-cp37-cp37m-manylinux1_x86_64.whl (275 kB)
     |████████████████████████████████| 275 kB 24.1 MB/s
Collecting intervaltree; extra == "profile"
  Downloading intervaltree-3.0.2.tar.gz (30 kB)
Collecting protobuf>=3; extra == "profile"
  Downloading protobuf-3.11.3-cp37-cp37m-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 25.5 MB/s
Collecting sortedcontainers<3.0,>=2.0
  Downloading sortedcontainers-2.1.0-py2.py3-none-any.whl (28 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from protobuf>=3; extra == "profile"->ddtrace[profile]==0.36.0) (46.1.3)
Collecting six>=1.9
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: intervaltree
  Building wheel for intervaltree (setup.py) ... done
  Created wheel for intervaltree: filename=intervaltree-3.0.2-py3-none-any.whl size=25793 sha256=a958c9799a44688ed7ce9f742c8b5343749cd1d6bb2cd87265ae88271bc34a58
  Stored in directory: /root/.cache/pip/wheels/68/2d/6f/68fdd1342f58dac32f7d2781b00e9fd43b15d51e4c1ff9b4fb
Successfully built intervaltree
Installing collected packages: msgpack, sortedcontainers, intervaltree, six, protobuf, ddtrace
Successfully installed ddtrace-0.36.0 intervaltree-3.0.2 msgpack-1.0.0 protobuf-3.11.3 six-1.14.0 sortedcontainers-2.1.0
root@10a961d023a2:/# python
Python 3.7.7 (default, Mar 31 2020, 15:46:29)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ddtrace.profile.auto
__main__:1: RemovedInDDTrace10Warning: 'ddtrace.profile' is deprecated and will be remove in future versions. Use ddtrace.profiling instead.
No exporters are configured, no profile will be output
```

There may be a build time dependency missing, but I don't see any errors during `pip install`

**Comment by jd** [comment]
There are 3 different problems:
1. We provide pre-built wheels for Linux, but Alpine is not compatible with them, so you have to install it by source
2. Alpine does not have any C compiler by default, so you can't compile our wheels
3. Our wheel building / install mechanism should but it does not

I'll fix 3. by making sure you see an error when installing. That being said, this is not going to solve your issue — you'll just get an error message.

If you want to use Alpine Linux, you need (at least) to install `gcc`.

**Comment by lumberj** [comment]
I ran with `-v` and I can see the `gcc` failure now:

```
WARNING: Failed to build extension ddtrace.profiling.collector.stack, skipping: command 'gcc' failed with exit status 1
  building 'ddtrace.profiling.collector._traceback' extension
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.7m -c ddtrace/profiling/collector/_traceback.c -o build/temp.linux-x86_64-3.7/ddtrace/profiling/collector/_traceback.o
  gcc -shared build/temp.linux-x86_64-3.7/ddtrace/profiling/collector/_traceback.o -L/usr/local/lib -lpython3.7m -o build/lib.linux-x86_64-3.7/ddtrace/profiling/collector/_traceback.cpython-37m-x86_64-linux-gnu.so
  building 'ddtrace.profiling._build' extension
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.7m -c ddtrace/profiling/_build.c -o build/temp.linux-x86_64-3.7/ddtrace/profiling/_build.o
  gcc -shared build/temp.linux-x86_64-3.7/ddtrace/profiling/_build.o -L/usr/local/lib -lpython3.7m -o build/lib.linux-x86_64-3.7/ddtrace/profiling/_build.cpython-37m-x86_64-linux-gnu.so
  building 'ddtrace.vendor.wrapt._wrappers' extension
  creating build/temp.linux-x86_64-3.7/ddtrace/vendor
  creating build/temp.linux-x86_64-3.7/ddtrace/vendor/wrapt
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.7m -c ddtrace/vendor/wrapt/_wrappers.c -o build/temp.linux-x86_64-3.7/ddtrace/vendor/wrapt/_wrappers.o
  gcc -shared build/temp.linux-x86_64-3.7/ddtrace/vendor/wrapt/_wrappers.o -L/usr/local/lib -lpython3.7m -o build/lib.linux-x86_64-3.7/ddtrace/vendor/wrapt/_wrappers.cpython-37m-x86_64-linux-gnu.so
  building 'ddtrace.vendor.psutil._psutil_linux' extension
  creating build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_VERSION=567 -DPSUTIL_POSIX=1 -DPSUTIL_LINUX=1 -I/usr/local/include/python3.7m -c ddtrace/vendor/psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_common.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_VERSION=567 -DPSUTIL_POSIX=1 -DPSUTIL_LINUX=1 -I/usr/local/include/python3.7m -c ddtrace/vendor/psutil/_psutil_posix.c -o build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_posix.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_VERSION=567 -DPSUTIL_POSIX=1 -DPSUTIL_LINUX=1 -I/usr/local/include/python3.7m -c ddtrace/vendor/psutil/_psutil_linux.c -o build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_linux.o
  ddtrace/vendor/psutil/_psutil_linux.c: In function 'PyInit__psutil_linux':
  ddtrace/vendor/psutil/_psutil_linux.c:607:15: warning: unused variable 'v' [-Wunused-variable]
       PyObject *v;
                 ^
  gcc -shared build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_common.o build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_posix.o build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_linux.o -L/usr/local/lib -lpython3.7m -o build/lib.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_linux.cpython-37m-x86_64-linux-gnu.so
  building 'ddtrace.vendor.psutil._psutil_posix' extension
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_VERSION=567 -DPSUTIL_POSIX=1 -DPSUTIL_LINUX=1 -I/usr/local/include/python3.7m -c ddtrace/vendor/psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_common.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_VERSION=567 -DPSUTIL_POSIX=1 -DPSUTIL_LINUX=1 -I/usr/local/include/python3.7m -c ddtrace/vendor/psutil/_psutil_posix.c -o build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_posix.o
  gcc -shared build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_common.o build/temp.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_posix.o -L/usr/local/lib -lpython3.7m -o build/lib.linux-x86_64-3.7/ddtrace/vendor/psutil/_psutil_posix.cpython-37m-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
```

**Comment by jd** [comment]
I've tried compiling the library on Alpine, and it fails with some Cython generated code for the stack collector.
I'll look into that, though in the meantime I'd suggest switching to e.g. Debian based images.

**Comment by jd** [comment]
Compilation on Alpine fails and I'm unable to make it work so far — there's a conversion issue around `pthread_t` and `int` triggered with `gcc`.

As it's discouraged to use Alpine for Python image anyway¹, I recommend switching to another Docker image.

¹ https://pythonspeed.com/articles/alpine-docker-python/
