### ISSUE TITLE
"No module named 'Cython'" when pip installing ddtrace 0.36.0

### ISSUE THREAD

**Issue by JonathanAquino** [DataDog/dd-trace-py#1336]
### Which version of dd-trace-py are you using?

0.36.0

### Which version of the libraries are you using?

2to3==1.0
astroid==2.3.1
awscli==1.15.0
Babel==2.6.0
botocore==1.10.0
click==6.7
colorama==0.3.7
ddtrace==0.34.0
docutils==0.14
Flask==1.0.2
Flask-Babel==0.11.2
isort==4.3.21
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
lazy-object-proxy==0.0.0
MarkupSafe==1.0
mccabe==0.6.1
msgpack==1.0.0
pbr==4.0.4
pyasn1==0.4.2
pylint==2.4.2
python-dateutil==2.6.1
pytz==2018.5
PyYAML==3.12
rsa==3.4.2
s3transfer==0.1.13
six==1.12.0
stevedore==1.28.0
typed-ast==1.4.0
virtualenv==16.0.0
virtualenv-clone==0.3.0
virtualenvwrapper==4.8.2
Werkzeug==0.14.1
wrapt==1.11.2

### How can we reproduce your problem?

pip install ddtrace==0.36.0

### What is the result that you get?

An error:

    Collecting ddtrace==0.36.0
    Downloading https://files.pythonhosted.org/packages/41/9b/9e0c6b9927f0c1a519c975c8ffdd008a33a2fd68b15ffebf10261ac26b24/ddtrace-0.36.0.tar.gz (845kB)
        100% |████████████████████████████████| 849kB 1.1MB/s
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/wb/xzl1bpz57sqbwzplbr70wlp40000gn/T/pip-build-f8x8640l/ddtrace/setup.py", line 11, in <module>
            from Cython.Build import cythonize  # noqa: I100
        ModuleNotFoundError: No module named 'Cython'

### What is the result that you expected?

Successful installation with no error. Note that `pip install ddtrace==0.34.0` works fine.

**Comment by JonathanAquino** [comment]
Ok, thanks.
