### ISSUE TITLE
ddtrace-run doesn't log errors.

### ISSUE THREAD

**Issue by alexandrubeu** [DataDog/dd-trace-py#1453]
### Which version of dd-trace-py are you using?
0.38

### Which version of the libraries are you using?
```
args==0.1.0
astroid==1.6.6
backports.functools-lru-cache==1.5
beautifulsoup4==4.4.1
blessings==1.7
boto3==1.9.149
botocore==1.12.197
certifi==2019.6.16
chardet==3.0.4
clint==0.5.1
codecov==2.0.15
coloredlogs==10.0
colour-runner==0.1.1
configparser==3.7.4
contextlib2==0.5.5
coverage==4.5.3
cssutils==1.0.2
ddtrace==0.38.0
deepdiff==3.3.0
docutils==0.14
doublex==1.9.2
doublex-expects==0.7.0
enum34==1.1.6
expects==0.9.0
filelock==3.0.12
funcsigs==1.0.2
future==0.17.1
futures==3.3.0
humanfriendly==4.18
idna==2.8
importlib-metadata==0.19
isort==4.3.21
jmespath==0.9.4
jsonpickle==1.2
lazy-object-proxy==1.4.1
lxml==4.4.0
mamba==0.10
mccabe==0.6.1
mock==3.0.5
monotonic==1.5
msgpack==1.0.0
packaging==19.0
pathlib2==2.3.4
pkg-resources==0.0.0
pluggy==0.12.0
py==1.8.0
pycaption==0.7.7
Pygments==2.4.2
PyHamcrest==1.9.0
pylint==1.9.4
pyparsing==2.4.1.1
python-dateutil==2.8.0
PyYAML==4.2b1
requests==2.22.0
rootpath==0.1.1
s3transfer==0.2.1
scandir==1.10.0
sentry-sdk==0.8.0
simple-settings==0.16.0
singledispatch==3.4.0.3
six==1.12.0
stories==0.10
termcolor==1.1.0
toml==0.10.0
tox==3.13.2
urllib3==1.25.3
virtualenv==16.7.2
wrapt==1.11.2
zipp==0.5.2
```

### How can we reproduce your problem?
I have this file: 
ddtrace.py which contains
```
print 'hello world'

raise Exception('something wrong happened')
```
I'm using **Python 2.7**
this is the script that I'm executing
```
export DD_SERVICE=potamoi
ddtrace-run python app/ddtrace.py
```

If I'm using a span in the code everything works... I can see the logs APM Tracer.

### What is the result that you get?
when executing I get this:
```
hello world
Traceback (most recent call last):
  File "app/ddtrace.py", line 3, in <module>
    raise Exception('something wrong happend')
Exception: something wrong happend
```
And with DATADOG_TRACE_DEBUG
```
DEBUG:ddtrace.commands.ddtrace_run:sys.argv: ['/home/alexandrubeu/Projects/Potamoi/venv/bin/ddtrace-run', 'python', 'app/ddtrace.py']
DEBUG:ddtrace.commands.ddtrace_run:ddtrace root: /home/alexandrubeu/Projects/Potamoi/venv/local/lib/python2.7/site-packages/ddtrace
DEBUG:ddtrace.commands.ddtrace_run:ddtrace bootstrap: /home/alexandrubeu/Projects/Potamoi/venv/local/lib/python2.7/site-packages/ddtrace/bootstrap
DEBUG:ddtrace.commands.ddtrace_run:PYTHONPATH: /home/alexandrubeu/Projects/Potamoi/venv/local/lib/python2.7/site-packages/ddtrace/bootstrap:/home/alexandrubeu/Projects/Potamoi
DEBUG:ddtrace.commands.ddtrace_run:sys.path: ['/home/alexandrubeu/Projects/Potamoi/venv/bin', '/home/alexandrubeu/Projects/Potamoi', '/home/alexandrubeu/Projects/Potamoi/venv/lib/python2.7', '/home/alexandrubeu/Projects/Potamoi/venv/lib/python2.7/plat-x86_64-linux-gnu', '/home/alexandrubeu/Projects/Potamoi/venv/lib/python2.7/lib-tk', '/home/alexandrubeu/Projects/Potamoi/venv/lib/python2.7/lib-old', '/home/alexandrubeu/Projects/Potamoi/venv/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/alexandrubeu/Projects/Potamoi/venv/local/lib/python2.7/site-packages', '/home/alexandrubeu/Projects/Potamoi/venv/lib/python2.7/site-packages']
DEBUG:ddtrace.commands.ddtrace_run:program executable: /home/alexandrubeu/Projects/Potamoi/venv/bin/python
2020-05-22 12:54:41,577 DEBUG [ddtrace.internal.import_hooks] [import_hooks.py:136] [dd.service=potamoi dd.env= dd.version= dd.trace_id=0 dd.span_id=0] - No hooks registered for module 'utils.importlib'
2020-05-22 12:54:41,577 DEBUG [ddtrace.monkey] [monkey.py:154] [dd.service=potamoi dd.env= dd.version= dd.trace_id=0 dd.span_id=0] - failed to patch algoliasearch
Traceback (most recent call last):
  File "/home/alexandrubeu/Projects/Potamoi/venv/local/lib/python2.7/site-packages/ddtrace/monkey.py", line 150, in patch_module
    return _patch_module(module)
  File "/home/alexandrubeu/Projects/Potamoi/venv/local/lib/python2.7/site-packages/ddtrace/monkey.py", line 185, in _patch_module
    raise PatchException("module '%s' not installed" % module)
PatchException: module 'algoliasearch' not installed
2020-05-22 12:54:41,667 DEBUG [ddtrace.monkey] [monkey.py:173] [dd.service=potamoi dd.env= dd.version= dd.trace_id=0 dd.span_id=0] - already patched: ddtrace.contrib.logging
2020-05-22 12:54:41,668 INFO [ddtrace.monkey] [monkey.py:140] [dd.service=potamoi dd.env= dd.version= dd.trace_id=0 dd.span_id=0] - patched 6/33 modules (botocore,celery,flask,logging,requests,sqlite3)
2020-05-22 12:54:41,669 DEBUG [sitecustomize] [sitecustomize.py:122] [dd.service=potamoi dd.env= dd.version= dd.trace_id=0 dd.span_id=0] - sitecustomize from user found in: /usr/lib/python2.7/sitecustomize.py
hello world
Traceback (most recent call last):
  File "app/ddtrace.py", line 3, in <module>
    raise Exception('something wrong happend')
Exception: something wrong happend
2020-05-22 12:54:41,669 DEBUG [ddtrace._worker] [_worker.py:58] [dd.service=potamoi dd.env= dd.version= dd.trace_id=0 dd.span_id=0] - Stopping AgentWriter thread
```

### What is the result that you expected?
I don't see any logs in datadog APM traces at all. 
I see only spans if I use them
Am I doing something wrong?

**Comment by Kyle-Verhoog** [comment]
Hi @alexandrubeu!

The library does not catch exceptions that are raised outside of a tracing span. As you mentioned, they're only captured and attached to the span if one is present.

If you were to do

```python
import ddtrace

with ddtrace.tracer.trace("mycode"):
    raise Exception('something wrong happened')
```

you would then see the associated span with error and exception information in Datadog. I'd recommend wrapping the code that's generating exceptions to be wrapped in a `with tracer.trace()` statement or you can wrap your function:

```python
@tracer.wraps("my_fn")
def my_fn():
    raise Exception("uh oh!")

my_fn()
```

Let me know if this is unclear or if I can help further 🙂.

**Comment by Kyle-Verhoog** [comment]
Going to close this, feel free to re-open if it's still unclear!
