### ISSUE TITLE
Python/Docker ddtrace error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by EliFinkelshteyn** [DataDog/dd-trace-py#146]
Hi,
I just got into the APM beta and have been trying it out with no luck. I have both the dd-agent and the dd-trace-agent installed and seemingly working just fine. `/var/log/datadog/trace-agent.log` looks like:

```
2016-12-29 23:35:48 INFO (receiver.go:86) - listening for traces at http://localhost:7777/
2016-12-29 23:36:48 INFO (receiver.go:288) - receiver handled 0 spans, dropped 0 ; handled 0 traces, dropped 0
2016-12-29 23:37:48 INFO (receiver.go:288) - receiver handled 0 spans, dropped 0 ; handled 0 traces, dropped 0
2016-12-29 23:38:48 INFO (receiver.go:288) - receiver handled 0 spans, dropped 0 ; handled 0 traces, dropped 0
2016-12-29 23:39:48 INFO (receiver.go:288) - receiver handled 0 spans, dropped 0 ; handled 0 traces, dropped 0
...
```

Unfortunately, in my app log, I get this every little while:
```
ERROR:ddtrace.writer:error sending spans
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ddtrace/writer.py", line 120, in _target
    self.api.send_traces(traces)
  File "/usr/local/lib/python2.7/site-packages/ddtrace/api.py", line 47, in send_traces
    response = self._put(self._traces, data)
  File "/usr/local/lib/python2.7/site-packages/ddtrace/api.py", line 78, in _put
    conn.request("PUT", endpoint, data, self._headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/local/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/local/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
```

In my app, I'm just doing:

```python
from ddtrace import patch_all
        patch_all()
```

What's probably relevant here is my app is being run in a Docker container whereas my agent is installed on the host. This works fine for me on NewRelic's agent, but it looks like it might be an issue for DataDog's?

**Comment by awang** [comment]
Posting the solution here for posterity:

dd-trace-agent should work fine with Docker, but you'll have to make sure the Python side is able to connect to dd-trace-agent (by default it submits to localhost), and that the agent  accepts requests by binding to 0.0.0.0.  

We have some docs up at https://app.datadoghq.com/trace/docs/tutorials/docker

For the Python-side, the easiest way for you is probably something like
```
from ddtrace import tracer
tracer.configure(hostname="<IP address of trace-agent>")
```

You can set the agent binding via `bind_host` in `/etc/dd-agent/datadog.conf` or the DD_BIND_HOST env variable

**Comment by EliFinkelshteyn** [comment]
I'd like to request this be reopened as this no longer seems to work. I have the following in Flask:

```python
tracer.configure(hostname="parent-host")
tracer.debug_logging = True
```

I can see that the trace-agent is running on 0.0.0.0:7777 in `/var/log/datadog/trace-agent.log`:
`2017-05-03 09:00:29 INFO (receiver.go:86) - listening for traces at http://0.0.0.0:7777/`

My Docker run command maps properly to `parent-host` with ``--add-host=parent-host:`ip route show | grep docker0 | awk '{print \$9}'``. Nevertheless, I'm now seeing the following in my logs when trying to send spans:

```
2017-05-03 09:13:06,567 - ddtrace.writer - ERROR - cannot send spans: [Errno 111] Connection refused
ERROR:ddtrace.writer:cannot send spans: [Errno 111] Connection refused
```

**Comment by palazzem** [comment]
Hello @EliFinkelshteyn ! what version of the agent and the library are you using? we changed many things during these months, and actually the port our agent is listening is `8126` (`7777` is activated as a legacy port). Anyway, the latest version of the Python library will send traces to `8126` and not `7777`. Can you double check if both components are up to date? in that case I'd reopen the issue!

Thank you!

**Comment by EliFinkelshteyn** [comment]
That was the issue! I was running a newer version of the python library, but still running an older version of the trace agent. I didn't find any documentation that the ports were switched anywhere, so wasn't aware there would be an issue. Is there a place that keeps track of compatibility between client libraries and the `dd-trace-agent` somewhere so I can avoid having this happen in the future?

**Comment by palazzem** [comment]
Right, sorry about that! the problem is that the new port was officially exposed when the first version out of the Beta was released. Usually we write about these incompatibilities in our changelog (both for clients and agents). Here you can find the example about this specific incompatibility: https://github.com/DataDog/dd-trace-py/releases/tag/v0.6.0

We may think to write that somewhere else, so there is not real need to be updated with every changelog! Thanks for the suggestion!
