### ISSUE TITLE
RuntimeWorker exception raised during shutdown

### ISSUE THREAD

**Issue by zhammer** [DataDog/dd-trace-py#1462]
### Which version of dd-trace-py are you using?

`0.36.1` to `0.37.1`

### Bug

discovered a long-running bug in our python 2.7 apps running with dd-trace-py. i'm still investigating but wanted to flag here in case others have seen.

from what i can tell, there is a race condition on our dd-trace-py `python 2.7.13` applications where occasionally on shutdown an exception is raised from [RuntimeWorker](https://github.com/DataDog/dd-trace-py/blob/7e327048b32bfdeaf0f2cb7a0078c748b9cbea24/ddtrace/internal/runtime/runtime_metrics.py#L52-L74). the tracebacks are hard to grok since there seems to be some multi-thread messiness happening in the log buffer. here are two of those exception traces.

```
Exception Exception in thread RuntimeWorker (most likely raised during interpreter shutdown):
Traceback (most recent call last):
TypeError  File "/root/.pyenv/versions/2.7.13/lib/python2.7/threading.py", line 801, in __bootstrap_inner
:   File "/root/.pyenv/versions/2.7.13/lib/python2.7/threading.py", line 754, in run'super() argum
  File "/root/.pyenv/versions/general-2/lib/python2.7/site-packages/ddtrace/_worker.py", line 70, in _target
  File "/root/.pyenv/versions/general-2/lib/python2.7/site-packages/ddtrace/_worker.py", line 79, in _on_shutdown
  File "/root/.pyenv/versions/general-2/lib/python2.7/site-packages/ddtrace/internal/runtime/runtime_metrics.py", line 67, in flush
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/logging/__init__.py", line 1155, in debug
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/logging/__init__.py", line 1285, in _log
  File "/root/.pyenv/versions/general-2/lib/python2.7/site-packages/ddtrace/contrib/logging/patch.py", line 40, in _w_makeRecord
e<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'LOG_SPAN_KEY'
nt 1 must be type, not None' in <bound method HTTPClient.__del__ of <tornado.httpclient.HTTPClient object at 0x7f3cfb929850>> ignored
```

```
Exception Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(RuntimeWorker, stopped daemon 140462873298688)>>
Error in sys.excepthook:
Traceback (most recent call last):
  File "/root/.pyenv/versions/general-2/lib/python2.7/site-packages/sgrun/instrument.py", line 49, in excepthook
TypeError: "'NoneType' object is not callable"    logger.error(
AttributeError: 'NoneType' object has no attribute 'error'
 in 
Original exception was:
Traceback (most recent call last):
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/threading.py", line 814, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/traceback.py", line 241, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'
```

the tracebacks are all different but follow a pattern where the python interpreter tries to access an attribute (`sys.exc_info()`), but the variable is (in this case `sys`) is `None`, (`'NoneType' object has no attribute 'exc_info'`). my guess is some garbage collection is happening before the interpreter gets to the `RuntimeWorker` registered `atexit` function.

some notes:
- from what I can tell in our logs, this exception only comes from RuntimeWorker
- seems similar to [python bug: multiprocessing 'NoneType' object is not callable](https://bugs.python.org/issue15881) though from what i can tell that was patched by python 2.7.4
- from what I can tell, RuntimeWorker does some garbage collection metrics via [GCRuntimeMetricCollector](https://github.com/DataDog/dd-trace-py/blob/7125e740b0303d32dc4e2719c063f3505376094c/ddtrace/internal/runtime/metric_collectors.py#L23-L41)
- this doesn't change the application's exit code (which is why we didn't notice for a long time. even if this exception is raised, app still exit 0s.)
- some related work on RuntimeWorker race conditions last year: https://github.com/DataDog/dd-trace-py/pull/887

### How can we reproduce your problem?

working on a local reproduction. hard to get right as this is seems to be happening in the `DogStatsD` `RuntimeWorker`, and I don't have a testing agent installed locally. i can easily reproduce this on our staging environment by restarting allocations

**Comment by zhammer** [comment]
update: `ddtrace.tracer.configure(collect_metrics=False)` stops exception from being raised on shutdown. definitely seems to be isolated to `RuntimeWorker`

**Comment by jd** [comment]
This is a classic, on shutdown `sys` is `None` and that's a good way to detect Python shutdown. The `threading` module does that.
We should if it that way too for the `RuntimeWorker`.

**Comment by zhammer** [comment]
ah glad you've seen this before! @jd for context is this what you're talking about? https://stackoverflow.com/questions/25649676/where-is-pythons-shutdown-procedure-documented/25649713#25649713 

would like to read up a bit more

**Comment by jd** [comment]
Yes, you can check what Python does here to hide the problem in daemonic threads:
https://github.com/python/cpython/blob/master/Lib/threading.py#L894-L912

**Comment by zhammer** [comment]
> when a daemon thread wakes up at an unfortunate
> moment, finds the world around it destroyed, and raises some
> random exception *** while trying to report the exception in
> _bootstrap_inner() below ***

ha i love that

**Comment by zhammer** [comment]
repro'ing locally: https://gist.github.com/zhammer/f0322695167ced73124b2504934171df

**Comment by zhammer** [comment]
@jd can you explain a bit more what you mean by
> We should if it that way too for the RuntimeWorker.

I'm not sure exactly *where* we should try to catch those exceptions. I've tried both [in the PeriodicWorkerThread](https://github.com/seatgeek/dd-trace-py/pull/1/files) and [in the RuntimeWorker](https://github.com/seatgeek/dd-trace-py/pull/1/commits/d58bc71035d50642843724df62d736eda675657a) but can repro the issue on both commits with the repro gist in my previous comment.

---

on another note, i'm also seeing a bunch of instances of this exception on that repro gist:
```
Exception in thread RuntimeWorker (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/site-packages/ddtrace/_worker.py", line 69, in _target
  File "/usr/local/lib/python2.7/threading.py", line 614, in wait
  File "/usr/local/lib/python2.7/threading.py", line 364, in wait
<type 'exceptions.ValueError'>: list.remove(x): x not in list
```

which is odd as from what i can tell the stdlib's threading.py should swallow those exceptions: https://github.com/python/cpython/blob/8d21aa21f2cbc6d50aab3f420bb23be1d081dac4/Lib/threading.py#L363-L366

**Comment by jd** [comment]
You could try something like that to hide the issue on shutdown:

```
diff --git ddtrace/_worker.py ddtrace/_worker.py
index 8b2b6db7..bf6878de 100644
--- ddtrace/_worker.py
+++ ddtrace/_worker.py
@@ -1,6 +1,7 @@
 import atexit
 import threading
 import os
+import sys

 from .internal.logger import get_logger

@@ -65,9 +66,15 @@ class PeriodicWorkerThread(object):
         return self._thread.join(timeout)

     def _target(self):
-        while not self._stop.wait(self.interval):
-            self.run_periodic()
-        self._on_shutdown()
+        try:
+            while not self._stop.wait(self.interval):
+                self.run_periodic()
+            self._on_shutdown()
+        except Exception:
+            # If the problem is due to an interpreter shutdown, ignore it
+            # This is a workaround for Python 2
+            if sys is not None:
+                raise

     @staticmethod
     def run_periodic():
```

**Comment by brettlangdon** [comment]
Closing since there hasn't been any activity on this issue. Please feel free to re-open if the problem is still occurring!
