### ISSUE TITLE
RuntimeError iterating over StackCollector thread span links

### ISSUE THREAD

**Issue by benwebber** [DataDog/dd-trace-py#1466]
Since enabling profiling, we've observed regular `RuntimeError`s in our Gunicorn logs:

```
Exception in thread ddtrace.profiling.collector.stack:StackCollector:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/path/to/virtualenv/src/ddtrace/ddtrace/profiling/_periodic.py", line 48, in run
    self._target()
  File "/path/to/virtualenv/src/ddtrace/ddtrace/profiling/collector/__init__.py", line 21, in periodic
    for events in self.collect():
  File "ddtrace/profiling/collector/stack.pyx", line 408, in ddtrace.profiling.collector.stack.StackCollector.collect
  File "ddtrace/profiling/collector/stack.pyx", line 276, in ddtrace.profiling.collector.stack.stack_collect
  File "ddtrace/profiling/collector/stack.pyx", line 350, in ddtrace.profiling.collector.stack._ThreadSpanLinks.get_active_leaf_spans_from_thread_id
  File "/path/to/virtualenv/lib/python3.6/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

It seems the `WeakSet` containing thread span links mutates while we iterate over it here:

https://github.com/DataDog/dd-trace-py/blob/5dfce22baf990f2d0d31296e4f1a4e1057ff38d6/ddtrace/profiling/collector/stack.pyx#L350

### Which version of dd-trace-py are you using?

v0.37.0-55-gb9c73d75 (0.37.1 with the patch from #1441)

### Which version of the libraries are you using?

Potentially relevant libraries:

```
Django==3.0.4
gunicorn==19.6.0
```

We use the default Gunicorn sync worker.

Our ddtrace configuration is pretty simple:

```python
ddtrace.config.analytics_enabled = True
ddtrace.config.elasticsearch.analytics_enabled = True
ddtrace.config.celery.analytics_enabled = True
ddtrace.config.celery['distributed_tracing'] = True
ddtrace.config.dbapi2.analytics_enabled = True
```

### How can we reproduce your problem?

It's not clear if there's anything specific about the WSGI requests that triggers this condition. The exceptions correlate with general traffic, and they seem to occur pretty regularly.

We only observe this with Gunicorn, although we've also enabled ddtrace for Celery workers.

### What is the result that you get?

—

### What is the result that you expected?

—

**Comment by jd** [comment]
Thanks for the report! It looks like `WeakSet` is not thread-safe. I'll write a fix.

**Comment by jd** [comment]
If you have the chance to give a try to #1469, that'd be fantastic 🙏

**Comment by benwebber** [comment]
We've deployed that patch on top of 0.38.1 (and the patch from #1441). I'll update this issue tomorrow after we record several hours of traffic.

**Comment by benwebber** [comment]
Since deploying the patch at around 22:00 UTC yesterday, we've only observed one new `RuntimeError` (note the new line number):

```
Exception in thread ddtrace.profiling.collector.stack:StackCollector:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/path/to/virtualenv/src/ddtrace/ddtrace/profiling/_periodic.py", line 49, in run
    self._target()
  File "/path/to/virtualenv/src/ddtrace/ddtrace/profiling/collector/__init__.py", line 21, in periodic
    for events in self.collect():
  File "ddtrace/profiling/collector/stack.pyx", line 467, in ddtrace.profiling.collector.stack.StackCollector.collect
  File "ddtrace/profiling/collector/stack.pyx", line 325, in ddtrace.profiling.collector.stack.stack_collect
  File "ddtrace/profiling/collector/stack.pyx", line 407, in ddtrace.profiling.collector.stack._ThreadSpanLinks.get_active_leaf_spans_from_thread_id
  File "ddtrace/profiling/collector/stack.pyx", line 408, in ddtrace.profiling.collector.stack._ThreadSpanLinks.get_active_leaf_spans_from_thread_id
  File "/path/to/virtualenv/lib/python3.6/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

Prior to the change, we observed around 500 over the same time duration.

It definitely seems like the lock makes a substantial difference. I'm curious how we managed to hit the same bug while under the thread lock.

**Comment by jd** [comment]
Thanks for testing! By "one new", did you mean it only occurred once?
Are you using gevent by any chance?

**Comment by benwebber** [comment]
That's correct. We have only recorded one `RuntimeError` in the Gunicorn logs since 2020-05-28 22:00 UTC.

We use the default Gunicorn sync worker, not gevent.

**Comment by damjankuznar** [comment]
@jd FYI - We are getting this same error when profiling Python code without using Gunicorn or using threads in our code.

**Comment by jd** [comment]
@damjankuznar Thanks for heads-up. Do you use anything that introduce concurrency?

**Comment by Kyle-Verhoog** [comment]
Anyone please feel free to reopen this if you're still seeing the error after trying #1469, it was just auto-closed by github
