### ISSUE TITLE
Internal logger fails until logging is patched because dd.service is not set

### ISSUE THREAD

**Issue by ryboe** [DataDog/dd-trace-py#1960]
### Which version of dd-trace-py are you using?
0.46.0

### Which version of the libraries are you using?
datadog 0.39.0
ddtrace 0.46.0

### How can we reproduce your problem?

1. Make a toy project that uses `jinja2`, or some other module from `contrib/`, and `logging`.
2. Enable these env vars:
```
DD_SERVICE=foo
DD_TRACE_DEBUG=true
DD_TRACE_STARTUP_LOGS=true
```
3. Start the project with `ddtrace-run` and observe that the internal logger fails until `logging` is patched.

### What is the result that you get?

Every time the `ddtrace` internal logger tries to log something, it raises an exception like this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 430, in format
    return self._format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 426, in _format
    return self._fmt % record.__dict__
KeyError: 'dd.service'
member_backend              |
During handling of the above exception, another exception occurred:
member_backend              |
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 662, in format
    s = self.formatMessage(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 631, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 432, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'dd.service'
Call stack:
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site.py", line 589, in <module>
    main()
  File "/usr/local/lib/python3.9/site.py", line 582, in main
    execsitecustomize()
  File "/usr/local/lib/python3.9/site.py", line 521, in execsitecustomize
    import sitecustomize
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/ddtrace/bootstrap/sitecustomize.py", line 17, in <module>
    from ddtrace.utils.formats import asbool, get_env, parse_tags_str  # noqa
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/ddtrace/__init__.py", line 18, in <module>
    tracer = Tracer()
  File "/usr/local/lib/python3.9/site-packages/ddtrace/tracer.py", line 146, in __init__
    self.configure(
  File "/usr/local/lib/python3.9/site-packages/ddtrace/vendor/debtcollector/removals.py", line 261, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/vendor/debtcollector/removals.py", line 261, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/tracer.py", line 362, in configure
    self._log_compat(logging.WARNING, msg)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/tracer.py", line 590, in _log_compat
    self.log.log(level, msg)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1500, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/internal/logger.py", line 118, in handle
    super(DDLogger, self).handle(record)
Message: '- DATADOG TRACER DIAGNOSTIC - Agent not reachable at datadog:8126. Exception raised: [Errno 111] Connection refused'
Arguments: ()
```
I've confirmed that `$DD_SERVICE` is set before `ddtrace-run` is called.

When it finally patches `logging`, all the exceptions go away.

```
2021-01-26 19:53:06,768 INFO [ddtrace.monkey] [monkey.py:171] [dd.service=backend dd.env=dev dd.version= dd.trace_id=0 dd.span_id=0] - patched 1/1 modules (logging)
```

I think this is a bug in `ddtrace`. It needs to patch `logging` first so that its own internal logger will work.

### What is the result that you expected?

There shouldn't be any exceptions when `ddtrace` starts up.

**Comment by c0rv4x** [comment]
Hey @ryboe 

Have you found any solution for this?

**Comment by ryboe** [comment]
No, sorry. I haven't looked at this problem in months.

**Comment by c0rv4x** [comment]
Thanks! Seems like it is more pain to use APM than the gain it provides.

**Comment by atroche** [comment]
Having this exact issue fwiw, with `ddtrace` 0.51.2.

**Comment by alesso-x** [comment]
Having the same issue with `ddtrace = 0.53.0`
