### ISSUE TITLE
Using botocore.Stubber without ResponseMetadata fails

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-trace-py#2116]
### Which version of dd-trace-py are you using?

0.45.0, but the code is the same on 0.47.0

### Which version of the libraries are you using?

botocore==1.16.15

### How can we reproduce your problem?

Write a test using [Stubber](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/stubber.html#botocore-stub):

```python
import datetime

import ddtrace
ddtrace.patch_all()

import botocore.session
from botocore.stub import Stubber

s3 = botocore.session.get_session().create_client('s3', aws_access_key_id="foo", aws_secret_access_key="bar")

response = {
    "Owner": {
        "ID": "foo",
        "DisplayName": "bar"
    },
    "Buckets": [{
        "CreationDate": datetime.datetime(2016, 1, 20, 22, 9),
        "Name": "baz"
    }]
}

with Stubber(s3) as stubber:
    stubber.add_response('list_buckets', response, {})
    service_response = s3.list_buckets()

assert service_response == response
```

### What is the result that you get?

```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    service_response = s3.list_buckets()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ddtrace/contrib/botocore/patch.py", line 166, in patched_api_call
    response_meta = result['ResponseMetadata']
KeyError: 'ResponseMetadata'
```

### What is the result that you expected?

No exceptions.

**Comment by brettlangdon** [comment]
Hey @miketheman thanks for the report. I have put up a fix in #2117 that also includes a reproduction test case from your example code.
