### ISSUE TITLE
grpc client interceptor fails when it cannot extract port from channel target

### ISSUE THREAD

**Issue by akursar** [DataDog/dd-trace-py#2322]
### Which version of dd-trace-py are you using?

0.48.0

### Which version of pip are you using?

21.0.1

### Which version of the libraries are you using?

datadog==0.41.0
datadog-lambda==3.33.0
ddtrace==0.48.0

### How can we reproduce your problem?

Attempt to use a ddtrace-patched grpc client with a channel `target` which omits the port number. There's an exception in the client interceptor.

After effectively upgrading from 0.45.0 to 0.48.0, our lambdas started failing with the error found below. It looks like there's a bug in `ddtrace.contrib.grpc.patch._parse_target_from_arguments` where if a port number cannot be extracted, None is returned, but this cannot be used as a span tag value. We connect to a target without a port number, which defaults to 443 for secure connections.

*The workaround for us is pretty simple - we just needed to append the port number to our config. But typically we set this to "api.example.com" and I think omitting 80/443 for secure/insecure connections is customary.*

### What is the result that you get?

    [ERROR] TypeError: not expecting type '<class 'NoneType'>'
    Traceback (most recent call last):
    ...
    File "/tmp/pip-target-txfs3xa9/lib/python/grpc/_interceptor.py", line 216, in __call__
    File "/tmp/pip-target-txfs3xa9/lib/python/grpc/_interceptor.py", line 254, in _with_call
    File "/tmp/pip-target-txfs3xa9/lib/python/ddtrace/contrib/grpc/client_interceptor.py", line 215, in intercept_unary_unary
    File "/tmp/pip-target-txfs3xa9/lib/python/ddtrace/contrib/grpc/client_interceptor.py", line 184, in _intercept_client_call
    File "/tmp/pip-target-txfs3xa9/lib/python/ddtrace/span.py", line 318, in _set_str_tag
    File "/tmp/pip-target-txfs3xa9/lib/python/ddtrace/vendor/six/__init__.py", line 937, in ensure_text

### What is the result that you expected?

I expect the RPC to work without exception, like it does with 0.45.0.

**Comment by majorgreys** [comment]
@akursar I actually opened a draft PR #2298 but meant to add a test case. I'll update it in the coming days and we'll be sure to get it into the next release. Thanks for posting this issue!

**Comment by majorgreys** [comment]
Closing since #2298 was merged
