### ISSUE TITLE
grpc client fails when parse_method_path() does not return a value for package

### ISSUE THREAD

**Issue by plannigan** [DataDog/dd-trace-py#2375]
### Which version of dd-trace-py are you using?

ddtrace==0.48.0

### Which version of pip are you using?

pip 21.1

### Which version of the libraries are you using?

ddtrace==0.48.0

### How can we reproduce your problem?

parse_method_path() can [return None](https://github.com/DataDog/dd-trace-py/blob/7f817089fac3efc2d1204d347e5d21abe344445c/ddtrace/contrib/grpc/utils.py#L12) for the `package` value. This is then passed to [span._set_str_tag()](https://github.com/DataDog/dd-trace-py/blob/7f817089fac3efc2d1204d347e5d21abe344445c/ddtrace/contrib/grpc/client_interceptor.py#L184), which expects the value to always be `str`.

### What is the result that you get?
```2021-04-29 12:50:27 [6] [ERROR] grpc._server     Exception calling application: not expecting type '<class 'NoneType'>'
Traceback (most recent call last):
  File "/pyenv/versions/app_venv/lib/python3.7/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/pyenv/versions/app_venv/lib/python3.7/site-packages/ddtrace/contrib/grpc/server_interceptor.py", line 112, in unary_unary
    return self._fn(constants.GRPC_METHOD_KIND_UNARY, self.__wrapped__.unary_unary, args, kwargs)
  File "/pyenv/versions/app_venv/lib/python3.7/site-packages/ddtrace/contrib/grpc/server_interceptor.py", line 79, in _fn
    span._set_str_tag(constants.GRPC_METHOD_PACKAGE_KEY, method_package)
  File "/pyenv/versions/app_venv/lib/python3.7/site-packages/ddtrace/span.py", line 318, in _set_str_tag
    self.meta[key] = ensure_text(value, errors="replace")
  File "/pyenv/versions/app_venv/lib/python3.7/site-packages/ddtrace/vendor/six/__init__.py", line 937, in ensure_text
    raise TypeError("not expecting type '%s'" % type(s))
TypeError: not expecting type '<class 'NoneType'>'
```

### What is the result that you expected?
The interceptor does not raise exceptions when the value is not available.

The issue seems to be surfaces as a result of #2218. it's not clear if the method package should be omitted or converted to a string as done in some of the other integrations edited in that PR.

**Comment by majorgreys** [comment]
@plannigan You are right! Sorry that this recent change introduced a regression. I'll work on adding a test and make this fix.
