### ISSUE TITLE
import library issue

### ISSUE THREAD

**Issue by rodrigoechaide** [DataDog/dd-trace-py#2469]
Error when importing ddtrace library.

When trying to import ddtrace inside a flask application using the following code:

```
from ddtrace import patch_all
patch_all()
import ddtrace.profiling.auto
```

I am getting the following error:

```
[Tue May 25 03:05:15.300477 2021] [wsgi:error] [pid 10853:tid 140242417870592] [client 172.31.28.36:37272] TypeError: attrib() got an unexpected keyword argument 'factory'
[Tue May 25 03:05:29.620846 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598] mod_wsgi (pid=10854): Target WSGI script '/var/www/tradersync-v2-backend/flaskapp.wsgi' cannot be loaded as Python module.
[Tue May 25 03:05:29.620896 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598] mod_wsgi (pid=10854): Exception occurred processing WSGI script '/var/www/tradersync-v2-backend/flaskapp.wsgi'.
[Tue May 25 03:05:29.621013 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598] Traceback (most recent call last):
[Tue May 25 03:05:29.621045 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]   File "/var/www/tradersync-v2-backend/flaskapp.wsgi", line 5, in <module>
[Tue May 25 03:05:29.621049 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]     from ddtrace import patch_all
[Tue May 25 03:05:29.621055 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]   File "/usr/local/lib/python3.6/dist-packages/ddtrace/__init__.py", line 3, in <module>
[Tue May 25 03:05:29.621059 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]     from .monkey import patch  # noqa: E402
[Tue May 25 03:05:29.621063 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]   File "/usr/local/lib/python3.6/dist-packages/ddtrace/monkey.py", line 21, in <module>
[Tue May 25 03:05:29.621067 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]     from .settings import _config as config
[Tue May 25 03:05:29.621071 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]   File "/usr/local/lib/python3.6/dist-packages/ddtrace/settings/__init__.py", line 1, in <module>
[Tue May 25 03:05:29.621074 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]     from .._hooks import Hooks
[Tue May 25 03:05:29.621079 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]   File "/usr/local/lib/python3.6/dist-packages/ddtrace/_hooks.py", line 18, in <module>
[Tue May 25 03:05:29.621083 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]     class Hooks(object):
[Tue May 25 03:05:29.621087 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]   File "/usr/local/lib/python3.6/dist-packages/ddtrace/_hooks.py", line 29, in Hooks
[Tue May 25 03:05:29.621091 2021] [wsgi:error] [pid 10854:tid 140242275194624] [client 172.31.58.117:1598]     _hooks = attr.ib(init=False, factory=lambda: collections.defaultdict(set), type=DefaultDict[str, Set])
```

Note: This is only happening when using `ddtrace==0.49.0`. If I downgrade to `ddtrace==0.48.4` the problem disappears.

### Which version of dd-trace-py are you using?

ddtrace==0.49.0

### Which version of pip are you using?

pip==9.0.1 installed from ubuntu 18.04 repositories

**Comment by Kyle-Verhoog** [comment]
hey @rodrigoechaide! If can you share the results of a `pip freeze`? I'm specifically interested in the `attrs` version that you have installed.

(We changed `attrs` from being vendored to being a normal Python dependency. The `factory` argument was added in attrs [18.1.0](https://www.attrs.org/en/stable/changelog.html#id120) and [ddtrace requires >= 19.2.0](https://github.com/DataDog/dd-trace-py/blob/c55207aea2818d18ada274e90621ecea0b56f9bc/setup.py#L173).)

**Comment by rodrigoechaide** [comment]
Hi @Kyle-Verhoog it seems that somehow the **attrs** installed version was `attrs==17.4.0` and **ddtrace** installed version was `ddtrace==0.49.0`. After upgrading **attrs** to `attrs >= 19.2.0` the problem is solved. Many thanks and sorry for reporting this false positive. You can close the issue.

**Comment by Kyle-Verhoog** [comment]
awesome thanks for following up!
