### ISSUE TITLE
With Django 3.2, psycopg2 SQL queries using quote_ident are failing with TypeError: argument 2 must be a connection or a cursor

### ISSUE THREAD

**Issue by phililippe** [DataDog/dd-trace-py#2618]
Hi,
Since my migration from Django 2.2 to Django 3.2, psycopg2 SQL queries using quote_ident are failing with "TypeError: argument 2 must be a connection or a cursor".

### Which version of dd-trace-py are you using?
ddtrace==0.49.3

### Which version of pip are you using?
pip 21.1.3 on python 3.8.7

### Which version of the libraries are you using?
psycopg2-binary==2.9.1
Django==3.2.5

### How can we reproduce your problem?

Using `ddtrace-run manage.py shell`
```python
Python 3.8.7 (default, Dec 21 2020, 20:10:35) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.db import connection
>>> from psycopg2 import sql
>>> cursor = connection.cursor()
INFO 2021-07-08 14:39:20,851 trace xxxx 1397113345xxxxx trace 129369116773149xxxxx sampled (1/1 spans sampled)
>>> cursor.execute(sql.SQL("select count(*) from {0} where app='auth'").format(sql.Identifier('django_migrations')));
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "xxx/pythonenv/lib/python3.8/site-packages/ddtrace/contrib/dbapi/__init__.py", line 113, in execute
    return self._trace_method(self.__wrapped__.execute, self._self_datadog_name, query, {}, query, *args, **kwargs)
  File "xxx/pythonenv/lib/python3.8/site-packages/ddtrace/contrib/psycopg/patch.py", line 60, in _trace_method
    resource = resource.as_string(self.__wrapped__)
  File "xxx/pythonenv/lib/python3.8/site-packages/psycopg2/sql.py", line 122, in as_string
    rv.append(i.as_string(context))
  File "xxx/pythonenv/lib/python3.8/site-packages/psycopg2/sql.py", line 350, in as_string
    return '.'.join(ext.quote_ident(s, context) for s in self._wrapped)
  File "xxx/pythonenv/lib/python3.8/site-packages/psycopg2/sql.py", line 350, in <genexpr>
    return '.'.join(ext.quote_ident(s, context) for s in self._wrapped)
  File "xxx/pythonenv/lib/python3.8/site-packages/ddtrace/contrib/psycopg/patch.py", line 162, in _extensions_quote_ident
    return func(obj, scope) if scope else func(obj)
TypeError: argument 2 must be a connection or a cursor
```
This error doen't happen if ddtrace-run is not used.

This issue in XRay APM is a look alike: https://github.com/aws/aws-xray-sdk-python/issues/243

For those who get the same issue, I did a quick fix that disable the ddtrace patch on cursor, but this is not very clean indeed:

```python
def disable_trace(cursor):
    if hasattr(cursor, '__wrapped__'):
        return cursor.__wrapped__
    return cursor

disable_trace(cursor).execute(...)
```

Thanks a lot for any help.

**Comment by emmettbutler** [comment]
The fix for this is blocked on https://github.com/DataDog/dd-trace-py/issues/2438#issuecomment-906661786
