### ISSUE TITLE
IndexError in _wrap_get_create

### ISSUE THREAD

**Issue by kharmabum** [DataDog/dd-trace-py#2733]
### How can we reproduce your problem?

Install redis if needed (on macOS):
```
brew install redis
brew services start redis
```

Create  a dogpile region cache:
```
from dogpile.cache import make_region
region = make_region("foo",
            key_mangler=lambda key: '{}:{}:{}'.format("foo", "env", key)) \
            .configure('dogpile.cache.redis', arguments=dict(url="redis://localhost:6379")
```

Call `get_or_create` using only kwargs:

```
        return token_cache.get_or_create(
            key="cache_key", creator=lambda: make_value(foo, bar, buzz))

```

Invoke your script via ddtrace-run:

```
ddtrace-run python3 test_ddtrace_and_dogpile.py
```

### What is the result that you get?

```
[ERROR] IndexError: tuple index out of range
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/site-packages/datadog_lambda/wrapper.py", line 54, in __call__
    return self.func(*args, **kwargs)
  File "/var/lang/lib/python3.8/site-packages/datadog_lambda/wrapper.py", line 124, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/handler.py", line 105, in execute_task
    executor = executor_getter(event)
  File "/var/task/handler.py", line 43, in get_step_executor
    executor = ETLStepExecutor(Worker.lambda_instance.value, **get_parameters_for_inference_pipeline(event))
  File "/var/lang/lib/python3.8/site-packages/sondes/containers/executors/base.py", line 24, in __init__
    client = get_third_party_client(kwargs["third_party_module_name"])(
  File "/var/task/caiso/client.py", line 17, in __init__
    self.api = get_caiso_api_client(
  File "/var/task/caiso/utility/caiso_api_client.py", line 40, in get_caiso_api_client
    token = get_login_token(service_url, username, password, worker, environment, cache_host)
  File "/var/task/caiso/utility/caiso_api_client.py", line 32, in get_login_token
    return token_cache.get_or_create(
  File "/var/lang/lib/python3.8/site-packages/ddtrace/contrib/dogpile_cache/region.py", line 14, in _wrap_get_create
    key = args[0]
```

### What is the result that you expected?
No error

**Comment by Kyle-Verhoog** [comment]
Thanks for the report @kharmabum! I'm able to reproduce the issue. Fix will be up shortly!

**Comment by Kyle-Verhoog** [comment]
Repro: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/10371/workflows/f38f48f5-a19b-42ab-8fe6-f1acbda30c91/jobs/795400

```
func = <bound method CacheRegion.get_or_create of <dogpile.cache.region.CacheRegion object at 0x7f53f4510e50>>
instance = <dogpile.cache.region.CacheRegion object at 0x7f53f4510e50>
args = ()
kwargs = {'creator': <function <lambda> at 0x7f53f447c6d0>, 'key': 'key'}

    def _wrap_get_create(func, instance, args, kwargs):
        pin = Pin.get_from(dogpile.cache)
        if not pin or not pin.enabled():
            return func(*args, **kwargs)
    
>       key = args[0]
E       IndexError: tuple index out of range

ddtrace/contrib/dogpile_cache/region.py:14: IndexError
```
