### ISSUE TITLE
Python 3.6 support for Tornado 6

### ISSUE THREAD

**Issue by Peilun-Li** [DataDog/dd-trace-py#2798]
### Which version of dd-trace-py are you using?
0.49.4

### Which version of the libraries are you using?
tornado = 6.1

### How can we reproduce your problem?
We are using KFServing which [requires tornado>=6.0](https://github.com/kubeflow/kfserving/blob/master/python/kfserving/requirements.txt#L7) for realtime services, however, we are also using Python 3.6.8, where we hit the restriction as documented in [ddtrace tornado integration doc](https://ddtrace.readthedocs.io/en/stable/integrations.html#tornado)

```
Note: This integration requires Python 3.7 and above for Tornado 5 and 6.
```

```
Traceback (most recent call last):
  File "/opt/zillow/.venv/lib/python3.6/site-packages/ddtrace/monkey.py", line 243, in _patch_module
    imported_module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/zillow/.venv/lib/python3.6/site-packages/ddtrace/contrib/tornado/__init__.py", line 114, in <module>
    from .stack_context import TracerStackContext
  File "/opt/zillow/.venv/lib/python3.6/site-packages/ddtrace/contrib/tornado/stack_context.py", line 15, in <module>
    from tornado.stack_context import StackContextInconsistentError
ModuleNotFoundError: No module named 'tornado.stack_context'

...

  File "/opt/zillow/.venv/lib/python3.6/site-packages/ddtrace/monkey.py", line 192, in patch
    patch_module(module, raise_errors=raise_errors)
  File "/opt/zillow/.venv/lib/python3.6/site-packages/ddtrace/monkey.py", line 210, in patch_module
    return _patch_module(module)
  File "/opt/zillow/.venv/lib/python3.6/site-packages/ddtrace/monkey.py", line 246, in _patch_module
    raise PatchException("integration '%s' not available" % path)
ddtrace.monkey.PatchException: integration 'ddtrace.contrib.tornado' not available
```

There seems to be a fix but for Python 3.7+ only https://github.com/DataDog/dd-trace-py/pull/1034, https://github.com/DataDog/dd-trace-py/issues/837. Curious can we extend that for Python 3.6 (a bit hard for us on our side to upgrade to 3.7 as a whole)

**Comment by Kyle-Verhoog** [comment]
hey @Peilun-Li, so sorry we never got back to you on this issue!

Is this still a problem for you? Python 3.6 has reached end of life so we'd really only look into this if it is blocking you from using the tornado integration.

Going to close the issue, please shout if you'd still like to see Python 3.6 Tornado 6 support!
