### ISSUE TITLE
Pyramid instrumentation breaks Configurator object.

### ISSUE THREAD

**Issue by marcin-lulek-cint** [DataDog/dd-trace-py#2942]
### Which version of dd-trace-py are you using?

ddtrace==0.54.1

### Which version of the libraries are you using?

```
attrs==21.2.0
ddtrace==0.54.1
# Editable Git install with no remote (ddtracer-test==0.0)
-e /home/ergo/workspace/ddtracer_test
hupper==1.10.3
Jinja2==3.0.2
Mako==1.1.5
MarkupSafe==2.0.1
packaging==21.0
PasteDeploy==2.1.1
plaster==1.0
plaster-pastedeploy==0.7
protobuf==3.19.0
Pygments==2.10.0
pyparsing==2.4.7
pyramid==2.0
pyramid-debugtoolbar==4.9
pyramid-jinja2==2.8
pyramid-mako==1.1.0
repoze.lru==0.7
six==1.16.0
tenacity==8.0.1
translationstring==1.4
venusian==3.0.0
waitress==2.0.0
WebOb==1.8.7
zope.deprecation==4.4.0
zope.interface==5.4.0
```

### How can we reproduce your problem?

I've prepared a minimal test case here

https://github.com/ergo/ddtrace_pyramid

### What is the result that you get?

When running:

`ddtrace-run pserve development.ini `

```
Traceback (most recent call last):
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/pyramid/path.py", line 387, in _zope_dottedname_style
    found = getattr(found, n)
AttributeError: module 'paste.deploy' has no attribute 'routes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ergo/workspace/ddtracer_test/env/bin/pserve", line 8, in <module>
    sys.exit(main())
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/pyramid/scripts/pserve.py", line 30, in main
    return command.run()
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/pyramid/scripts/pserve.py", line 271, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/plaster_pastedeploy/__init__.py", line 125, in get_wsgi_app
    return loadapp(
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/ergo/workspace/ddtracer_test/ddtracer_test/__init__.py", line 9, in main
    config.include('.routes')
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/pyramid/config/__init__.py", line 632, in include
    c = self.maybe_dotted(callable)
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/pyramid/config/__init__.py", line 740, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/pyramid/path.py", line 327, in maybe_resolve
    return self._resolve(dotted, package)
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/pyramid/path.py", line 334, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/home/ergo/workspace/ddtracer_test/env/lib/python3.9/site-packages/pyramid/path.py", line 389, in _zope_dottedname_style
    __import__(used)
ModuleNotFoundError: No module named 'paste.deploy.routes'
```

I've found potential problem - monkeypatching pyramid changes how package and root_package are being computed - so import calls break in our case with the exception I've posted above

https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/pyramid/patch.py#L77 - I've tracked this piece of code to be problematic.

I think the `caller_package` level argument needs to be adjusted - when I set it to 2 the application start.

### What is the result that you expected?

`pserve development.ini `
```
Starting server in PID 230548.
2021-10-22 16:06:31,327 INFO  [waitress:485][MainThread] Serving on http://127.0.0.1:8081
```

**Comment by Kyle-Verhoog** [comment]
👋  @marcin-lulek-cint / @ergo, I was able to add a repro and the fix in #2959. Also confirmed the fix with the repro you provided (many thanks for providing that).

We'll get this out in a 0.55.2 release shortly.
