### ISSUE TITLE
`gevent` with traces on the main thread 

### ISSUE THREAD

**Issue by wackywendell** [DataDog/dd-trace-py#309]
When using the monkey-patched `gevent` integration, if you attempt to create a trace on the main greenlet, the context will not be stored to the tracer, and `tracer.current_span()` will error.

### Example

```python
# patch before importing gevent
from ddtrace import patch, tracer
patch(gevent=True)

# use gevent as usual with or without the monkey module
import gevent
from gevent import monkey; monkey.patch_all()

@tracer.wrap(service='web')
def my_parent_function():
    span = tracer.current_span()
    gevent.spawn(worker_function)

def worker_function():
    # then trace its child
    with tracer.trace("greenlet.call") as span:
        span.service = "greenlet"

        with tracer.trace("greenlet.child_call") as child:
            print("Worker function")

my_parent_function()
```

Yields the following error:

```
Traceback (most recent call last):
  File "geventtracetest.py", line 23, in <module>
    my_parent_function()
  File "/usr/local/lib/python2.7/site-packages/ddtrace/tracer.py", line 369, in func_wrapper
    return f(*args, **kwargs)
  File "geventtracetest.py", line 11, in my_parent_function
    span = tracer.current_span()
  File "/usr/local/lib/python2.7/site-packages/ddtrace/tracer.py", line 234, in current_span
    return self.get_call_context().get_current_span()
AttributeError: 'NoneType' object has no attribute 'get_current_span'
```

**Comment by palazzem** [comment]
@wackywendell in the current `master` I've merged this PR that adds the `Context` to the main greenlet: https://github.com/DataDog/dd-trace-py/pull/339/files#diff-f149df7502f5a7073b6cd83108ba8444R41

It has been already tested and it should work effortless. I will keep you updated! for now we can close this Issue since it's fixed with #339
