### ISSUE TITLE
Unable to start Gunicorn with ddtrace-run

### ISSUE THREAD

**Issue by BuckinghamIO** [DataDog/dd-trace-py#310]
I am trying to run gunicorn with ddtrace-run however I keep hitting this same error no matter what or where I try and execute the command I get this result:

```

Traceback (most recent call last):
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/home/webapps/minecraftmarket/minecraftmarket/wsgi.py", line 24, in <module>
    application = get_wsgi_application()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/ddtrace/contrib/django/patch.py", line 18, in traced_setup
    if 'ddtrace.contrib.django' not in settings.INSTALLED_APPS:
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/virtualenv/minecraftmarket/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/webapps/minecraftmarket/minecraftmarket/settings/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/webapps/minecraftmarket/minecraftmarket/settings/celery.py", line 24, in <module>
    django.setup()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/ddtrace/contrib/django/patch.py", line 34, in traced_setup
    if 'ddtrace.contrib.django.TraceMiddleware' not in settings.MIDDLEWARE:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/home/webapps/minecraftmarket/minecraftmarket/wsgi.py", line 24, in <module>
    application = get_wsgi_application()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/ddtrace/contrib/django/patch.py", line 18, in traced_setup
    if 'ddtrace.contrib.django' not in settings.INSTALLED_APPS:
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/virtualenv/minecraftmarket/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/webapps/minecraftmarket/minecraftmarket/settings/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/webapps/minecraftmarket/minecraftmarket/settings/celery.py", line 24, in <module>
    django.setup()
  File "/virtualenv/minecraftmarket/lib/python3.5/site-packages/ddtrace/contrib/django/patch.py", line 34, in traced_setup
    if 'ddtrace.contrib.django.TraceMiddleware' not in settings.MIDDLEWARE:
TypeError: argument of type 'NoneType' is not iterable
[2017-07-14 14:15:10 +0000] [10132] [INFO] Worker exiting (pid: 10132)
[2017-07-14 10:15:11 -0400] [10126] [INFO] Shutting down: Master
[2017-07-14 10:15:11 -0400] [10126] [INFO] Reason: Worker failed to boot.
(minecraftmarket)webapps@srv1:~/minecraftmarket$ 

```

I can confirm the middleware is present, along with the installed app and the application sucessfully sends APM data for everything I have patched already within the application without fault.

So I'm unsure of where to start here?

**Comment by talwai** [comment]
@BuckinghamIO could you confirm your django version for us?

**Comment by BuckinghamIO** [comment]
@talwai Django version: 1.11.1

**Comment by palazzem** [comment]
Hello @BuckinghamIO! can you please try our latest release https://github.com/DataDog/dd-trace-py/releases/tag/v0.9.2 and see if the problem has been fixed? we did some work around Django, but  if doesn't work we're going to fix that quickly. Thank you!

**Comment by palazzem** [comment]
Hello @BuckinghamIO! I want to write in this thread again since we've shipped new versions of our Python client. The latest is https://github.com/DataDog/dd-trace-py/releases/tag/v0.10.1 . Would be great to know if the problem is still there after this time, so that we can schedule some work to address the problem.

Thank you very much!
