### ISSUE TITLE
Intermittent `RuntimeError: the memalloc module was not started` error

### ISSUE THREAD

**Issue by cyface** [DataDog/dd-trace-py#3121]
### Which version of dd-trace-py are you using?

ddtrace==0.57.0

### Which version of the libraries are you using?

You can copy/paste the output of `pip freeze` here.

**Comment by arthurio** [comment]
We are facing the same issue with a Fastapi app. I'd be happy to share logs/config you need.

**Comment by jd** [comment]
Could you share:
1. which Web server you're running?
2. Its configuration?
3. If you're using gevent?

**Comment by cyface** [comment]
I am using nginx feeding into gunicon/gevent with regular proxy setup. Not sure which configurations would be helpful to you?

**Comment by arthurio** [comment]
We have 2 different servers (not behind nginx).

**flask**
1. Gunicorn
2. `--worker-class=gthread`
3. No

**fastapi**
1. Gunicorn
2. `--worker-class=uvicorn.workers.UvicornWorker`
3. No

**Comment by roniemartinez** [comment]
+1 We have the same issue with Gunicorn + Django

**Comment by visaals** [comment]
+1 same in `0.59.1` we are using sanic with profiling enabled: `DD_PROFILING_ENABLED=true`

```
datadog~=0.44.0
ddtrace~=0.59.1
requests~=2.27.1
sanic~=19.12.2
```

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/19598277/159076397-a20fc9dc-4f0b-4332-a4c0-0dba795b8b6b.png">

**Comment by FlavioAlexander** [comment]
Currently, having the same issue

**Comment by luislew** [comment]
Same issue, with Flask/gunicorn/gevent, using ddtrace 1.2.1:
```

RuntimeError: the memalloc module was not started
  File "ddtrace/internal/periodic.py", line 70, in run
    self._target()
  File "ddtrace/profiling/collector/__init__.py", line 42, in periodic
    for events in self.collect():
  File "ddtrace/profiling/collector/memalloc.py", line 145, in collect
    events, count, alloc_count = _memalloc.iter_events()
```

**Comment by rgilkey** [comment]
Same issue with Flask/gunicorn/gevent as well using ddtrace 1.4.4:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/3894011/201698121-ef82b8fb-f191-4a7b-9a8f-2841c37e57bf.png">

**Comment by rgilkey** [comment]
@jd we're working on adding `DD_GEVENT_PATCH_ALL` in as recommended by Datadog support. we also need to upgrade some other some deps along the way to make it work. i'll post back if that gets us resolved.

**Comment by jorgemo-fever** [comment]
@rgilkey did adding `DD_GEVENT_PATCH_ALL` resolve the issue? I'm facing the same problem

**Comment by LPauzies** [comment]
We are currently facing the same issue, and it seems to be a bit random, it appears not frequently but it appears...
We use Flask + Gunicorn and ddtrace==1.0.1

**Comment by swingingsimian** [comment]
'Me too'ing this for Gunicorn, Uvicorn, FastaAPI with dd-trace 1.10.3

**Comment by P403n1x87** [comment]
@swingingsimian can I please check with you whether you are seeing
~~~
RuntimeError: the memalloc module was not started
~~~
or
~~~
RuntimeError: the memalloc module is already started
~~~
or both?

**Comment by joesteffee** [comment]
We are also seeing this behavior as of yesterday in our development cluster:

```
Traceback (most recent call last):
  File "/app/python/<app>/wsgi_image.binary.runfiles/pypi_ddtrace/site-packages/ddtrace/profiling/profiler.py", line 266, in _start_service
   col.start()
  File "/app/python/<app>/wsgi_image.binary.runfiles/pypi_ddtrace/site-packages/ddtrace/internal/service.py", line 58, in start
   self._start_service(*args, **kwargs)
 File "/app/python/<app>/wsgi_image.binary.runfiles/pypi_ddtrace/site-packages/ddtrace/profiling/collector/memalloc.py", line 108, in _start_service
   _memalloc.start(self.max_nframe, self._max_events, self.heap_sample_size)
RuntimeError: the memalloc module is already started
[2023-04-18 22:45:49 +0000] [72] [INFO] Booting worker with pid: 72
```

I believe it was triggered after our nodegroups cycled out in dev, the containers don't want to come back online. In this case many of them are stuck in crashloopbackoff for a period of time. It does eventually stabilize... maybe this is an API issue on datadog's end? We are running ddtrace 1.12.0

**Comment by P403n1x87** [comment]
Thanks for the reports @lfvarela @joesteffee. This exception is handled and so the only issue caused is that memory allocations won't be profiled. I think I have found the source of the problem, but can I please confirm with you that your services work and that this is just undesirable noise in your logs?

**Comment by P403n1x87** [comment]
The new reports are a different issue that is a manifestation of a regression. The fix is in #5586.

**Comment by lfvarela** [comment]
Thanks! To confirm - our servers couldn't even start. Weirdly - by increasing our CPU limits in our servers we stopped seeing the issue.
