### ISSUE TITLE
0.58.1 Install Cmake error w/ubuntu 18.0.4 and old pip

### ISSUE THREAD

**Issue by jason-kane** [DataDog/dd-trace-py#3255]
Thanks for taking the time for reporting an issue!

Before reporting an issue on dd-trace-py, please be sure to provide all
necessary information.

If you're hitting a bug, make sure that you're using the latest version of this
library.

### Which version of dd-trace-py are you using?
0.58.1

### Which version of pip are you using?
9.0.1 I believe

_ddtrace requires pip>=18 to install one of our pre-built wheels_

### Which version of the libraries are you using?
doesn't matter
You can copy/paste the output of `pip freeze` here.

### How can we reproduce your problem?

docker run -ti ubuntu:18.04
apt update; apt install -y python3-pip cmake
pip3 install cython 
pip3 install ddtrace

### What is the result that you get?
There is now a cmake dependency:
    WARNING: building extension "ddtrace.appsec._ddwaf" failed: [Errno 2] No such file or directory: 'cmake': 'cmake'
    error: [Errno 2] No such file or directory: 'cmake': 'cmake'

But when that is resolved:

CMake Error: The source directory "/tmp/tmpn2fqsj3y" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    WARNING: building extension "ddtrace.appsec._ddwaf" failed: Command '['cmake', '-S', '/tmp/pip-build-t1aq8vu6/ddtrace/ddtrace/appsec', '-B', '/tmp/tmpn2fqsj3y', '-DCMAKE_BUILD_TYPE=Release', '-G', 'Ninja']' returned non-zero exit status 1.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t1aq8vu6/ddtrace/setup.py", line 331, in <module>
        + get_exts_for("psutil"),
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
...
    subprocess.CalledProcessError: Command '['cmake', '-S', '/tmp/pip-build-t1aq8vu6/ddtrace/ddtrace/appsec', '-B', '/tmp/tmpn2fqsj3y', '-DCMAKE_BUILD_TYPE=Release', '-G', 'Ninja']' returned non-zero exit status 1.

### What is the result that you expected?
Workaround is easy; upgrading pip to current works.  I just want to be sure dropping old pip entirely is intentional not accidental.

**Comment by nizox** [comment]
Thanks for reporting this issue. You can use the following commands to install ddtrace on ubuntu 18.08:
```
apt update; apt install -y python3-pip git
pip3 install cmake ninja
pip3 install ddtrace
```

**Comment by brettlangdon** [comment]
@jason-kane 

> Workaround is easy; upgrading pip to current works. I just want to be sure dropping old pip entirely is intentional not accidental.

Correct. `pip<18` does not always properly recognize/fetch our pre-built wheels, and then it does not support all of the features in `pyproject.toml` which is why building from source distribution will also fail.

Unless you need to stay on an older version of `pip` I would definitely recommend upgrading anyways.


Please let us know if this is an acceptable solution for you.


Also, it does look like `pip==9.0.1`

```
root@8e26a21cd036:/# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

**Comment by jason-kane** [comment]
I'm unblocked, it broke our ci/cd until I figured out where the trouble was but the fix was easy.

I added the issue so other people with the same problem could google for it and to make sure the devs were aware of the change since it would be easy not to notice.

**Comment by brettlangdon** [comment]
@DavidS-cloud, I am sorry for any issues this has caused.


> a) the assertion "However, any errors during the compilation of this extension is ignored for now in order to avoid installation failures" in https://github.com/DataDog/dd-trace-py/pull/3027 were correct

Good catch, we forgot to update the PR description, we explicitly changed it so that compilation issues are not suppressed. https://github.com/DataDog/dd-trace-py/pull/3027/files#r774653854

I have removed that sentence from the PR description to be remove any confusion.

> b) the changelog mentioned any of this

Since this feature/extension is still meant to be private we explicitly decided to keep it from the changelog. We also recommend that people use `pip >= 18` to ensure they can install the pre-built wheels instead of needing to worry about build dependencies for our library.

However, you are correct that a Prelude message in the changelog stating that the build requirements have changed would have been a very useful thing to have.
