### ISSUE TITLE
TagsetEncodeError, failed to encode x-datadog-tags

### ISSUE THREAD

**Issue by fredrikaverpil** [DataDog/dd-trace-py#3319]
### Which version of dd-trace-py are you using?

`0.58.4`

### Which version of pip are you using?

```
pip 21.2.4 from /opt/venv/lib/python3.10/site-packages/pip (python 3.10)
```
_ddtrace requires pip>=18 to install one of our pre-built wheels_

### Which version of the libraries are you using?

I would prefer not to post a `pip freeze` in public but can provide this privately. But I can say we are using [`loguru` 0.6.0](https://github.com/Delgan/loguru/releases/tag/0.6.0) with a custom sink, meaning we construct and inject span_id and span_tags manually.

### How can we reproduce your problem?

N/A

### What is the result that you get?

I'm seeing an issue in when viewing logs in datadog:

```
2022-02-24 00:43:59,585 WARNING [ddtrace.propagation.http] [http.py:97] [dd.service=conversation-svc dd.env=staging dd.version=v3-134 dd.trace_id=8793797471281061728 dd.span_id=11227667759570421022] - failed to encode x-datadog-tags

Traceback (most recent call last):
File "/opt/venv/lib/python3.10/site-packages/ddtrace/propagation/http.py", line 89, in inject
encoded_tags = encode_tagset_values(tags_to_encode)
File "ddtrace/internal/_tagset.pyx", line 160, in ddtrace.internal._tagset.encode_tagset_values
ddtrace.internal._tagset.TagsetEncodeError: Value is not valid: 'cGF0LWFwaQ==|1|1|1'
```

The `cGF0LWFwaQ==|1|1|1` value itself is a base64-encoded string and after decoding it, it seems to contain a carriage return.
It's hard to tell right now if we put that carriage return in there by mistake - or if datadog did that - or if it matters at all, since it is encoded.

We started seeing this error after upgrading from ddtrace 0.57.3 to 0.58.4. When looking at the release notes, it seems you've been doing work on the span tagging. I wonder if there could be some oversight during that work which could've caused this?

I'm thinking we'll have to downgrade back to 0.57.3 or so to avoid disruptions, but it would be good to understand what is causing this.

### What is the result that you expected?

Not to see that `TagsetEncodeError` error at all.

**Comment by fredrikaverpil** [comment]
There was a GitHub outage or disruption of some kind, and so this got filed twice somehow...

Closing this and marking it as a duplicate of #3318
