### ISSUE TITLE
[psycopg2] Error when registering json

### ISSUE THREAD

**Issue by k4nar** [DataDog/dd-trace-py#387]
Hello,
I get an error when running the following file with `ddtrace-run`:

```python
import psycopg2
import psycopg2.extras


conn = psycopg2.connect(host=None)
psycopg2.extras.register_default_json(conn)
```

```shell
$ ddtrace-run python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    psycopg2.extras.register_default_json(conn)
  File "/home/yannick/.local/share/virtualenvs/core/lib/python3.6/site-packages/psycopg2/_json.py", line 165, in register_default_json
    loads=loads, oid=JSON_OID, array_oid=JSONARRAY_OID)
  File "/home/yannick/.local/share/virtualenvs/core/lib/python3.6/site-packages/psycopg2/_json.py", line 147, in register_json
    register_type(JSON, not globally and conn_or_curs or None)
TypeError: argument 2 must be a connection, cursor or None
```

As `register_default_json` is called by default by Aiopg at each connection, I have the same error with this simple script:

```python
import asyncio
import aiopg


async def main():
    async with aiopg.create_pool(host=None):
        pass

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

```shell
$ ddtrace-run python test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "test.py", line 6, in main
    async with aiopg.create_pool(host=None):
  File "/home/yannick/.local/share/virtualenvs/core/lib/python3.6/site-packages/aiopg/utils.py", line 77, in __aenter__
    self._obj = yield from self._coro
  File "/home/yannick/.local/share/virtualenvs/core/lib/python3.6/site-packages/aiopg/pool.py", line 47, in _create_pool
    yield from pool._fill_free_pool(False)
  File "/home/yannick/.local/share/virtualenvs/core/lib/python3.6/site-packages/aiopg/pool.py", line 209, in _fill_free_pool
    **self._conn_kwargs)
  File "/home/yannick/.local/share/virtualenvs/core/lib/python3.6/site-packages/aiopg/utils.py", line 67, in __iter__
    resp = yield from self._coro
  File "/home/yannick/.local/share/virtualenvs/core/lib/python3.6/site-packages/ddtrace/contrib/aiopg/patch.py", line 35, in patched_connect
    conn = yield from connect_func(*args, **kwargs)  # noqa: E999
  File "/home/yannick/.local/share/virtualenvs/core/lib/python3.6/site-packages/aiopg/connection.py", line 79, in _connect
    extras.register_default_json(conn._conn)
  File "/home/yannick/.local/share/virtualenvs/core/lib/python3.6/site-packages/psycopg2/_json.py", line 165, in register_default_json
    loads=loads, oid=JSON_OID, array_oid=JSONARRAY_OID)
  File "/home/yannick/.local/share/virtualenvs/core/lib/python3.6/site-packages/psycopg2/_json.py", line 147, in register_json
    register_type(JSON, not globally and conn_or_curs or None)
TypeError: argument 2 must be a connection, cursor or None
ERROR:asyncio:Unclosed connection
connection: <aiopg.connection.Connection object at 0x7fd48829bf98>
```

I have Python 3.6.3, ddtrace 0.10.0 and psycopg2 2.7.3.2. With `DATADOG_PATCH_MODULES` set to `psycopg:false` the issue is no longer present.

This looks similar to #383. Also there is a [test about the same error](https://github.com/DataDog/dd-trace-py/blob/be4800c86bcbc7b70d577961f7f58bf0a27c57fb/tests/contrib/psycopg/test_psycopg.py#L111-L117) but for uuids.

**Comment by stj** [comment]
I run into the same issue. For me it looked related to #96, so I created PR #393 to patch the `register_type` function in all locations of `psycopg2`. That solved the issue for me.
