### ISSUE TITLE
Unable to patch botocore to address HeadObject/404 issue

### ISSUE THREAD

**Issue by justinrmiller** [DataDog/dd-trace-py#4186]
Hello, I'm running into an issue with patching botocore to get around the HeadObject/404 issue.

```
from ddtrace import patch # noqa: E402
patch(gevent=True)
patch(botocore=True)

# Patch Datadog to avoid sending exceptions for 404s
# from ddtrace import config
import ddtrace
ddtrace.config.botocore['operations']['s3.headobject'].error_statuses = '404,500-599'
```

I'm first patching gevent then trying to patch botocore. The exception that gets thrown is the following:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "gunicorn.conf.py", line 28, in <module>
    ddtrace.config.botocore['operations']['s3.headobject'].error_statuses = '404,500-599'
KeyError: 'operations'
```

I feel like I'm missing something obvious so apologies in advance if I am. Thanks for taking a look!

### Which version of dd-trace-py are you using?

ddtrace==1.2.0

### Which version of pip are you using?

pip 22.2.2

### Which version of the libraries are you using?

    "datadog==0.42.0",
    "ddtrace==1.2.0",

### How can we reproduce your problem?

That I'm a bit unsure of as this is project is closed source.

### What is the result that you get?

KeyError: 'operations'

### What is the result that you expected?

No KeyError and botocore is successfully patched.

**Comment by justinrmiller** [comment]
I should add, when I print `ddtrace.config` I get: 

```ddtrace.settings.config.Config()```

Thanks!

**Comment by justinrmiller** [comment]
Figured it out, I was patching too early on. Once I moved the patch to right before the startup of the application (Flask) everything worked fine.
