### ISSUE TITLE
AttributeError: 'Span' object has no attribute 'sampling_priority'

### ISSUE THREAD

**Issue by caleb15** [DataDog/dd-trace-py#4187]
### Which version of dd-trace-py are you using?
ddtrace==1.4.4 (latest)

### Which version of pip are you using?
22.0.4

### Which version of the libraries are you using?
django v3

### How can we reproduce your problem?
```python
# Python 3.7.7 (default, Jun 23 2020, 10:35:24) 
# [GCC 7.5.0] on linux
import ddtrace
root_span = ddtrace.tracer.trace('main','foo_service')
ddtrace.tracer.current_root_span()
# <Span(id=17878154194350733971,trace_id=9855259419182767790,parent_id=None,name=main)>

headers = {}
from ddtrace.propagation.http import HTTPPropagator
HTTPPropagator.inject(ddtrace.tracer.current_root_span(), headers)
```

### What is the result that you get?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/caleb/.pyenv/versions/fifteen5/lib/python3.7/site-packages/ddtrace/propagation/http.py", line 55, in inject
    sampling_priority = span_context.sampling_priority
AttributeError: 'Span' object has no attribute 'sampling_priority'
```

### What is the result that you expected?
No error. Tracing headers injected into headers dict.

**Comment by avara1986** [comment]
Hi @caleb15, `HTTPPropagator` expects Span Context instead Span as parameter:

```
class HTTPPropagator(object):
    def inject(span_context, headers):
        # type: (Context, Dict[str, str]) -> None
```
Could you try with:

```
headers = {}
from ddtrace.propagation.http import HTTPPropagator
span = ddtrace.tracer.current_root_span()
if span:
    HTTPPropagator.inject(span.context, headers)
```

**Comment by caleb15** [comment]
That works, thanks :sweat_smile:
