### ISSUE TITLE
Cannot load `ddtrace` package when `DD_AGENT_HOST` is an IPv6 address

### ISSUE THREAD

**Issue by philhchen** [DataDog/dd-trace-py#4739]
### Summary of problem

When `DD_AGENT_HOST` is set to an IPv6 address, like `3b12:fb33:0:10::f262`, one cannot import `ddtrace`.

### Which version of dd-trace-py are you using?
`1.6.3`

### Which version of pip are you using?
`22.3.1`

### Which libraries and their versions are you using?

N/A

### How can we reproduce your problem?

```bash
DD_AGENT_HOST=3b12:fb33:0:10::f262 python -c "import ddtrace"
```

### What is the result that you get?

```commandline
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/anaconda3/envs/hmi/lib/python3.8/site-packages/ddtrace/__init__.py", line 24, in <module>
    tracer = Tracer()
  File "/usr/local/anaconda3/envs/hmi/lib/python3.8/site-packages/ddtrace/tracer.py", line 218, in __init__
    dogstatsd=get_dogstatsd_client(self._dogstatsd_url),
  File "/usr/local/anaconda3/envs/hmi/lib/python3.8/site-packages/ddtrace/internal/dogstatsd.py", line 24, in get_dogstatsd_client
    port=base.DEFAULT_PORT if parsed.port is None else parsed.port,
  File "/usr/local/anaconda3/envs/hmi/lib/python3.8/urllib/parse.py", line 177, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'fb33:0:10::f262:8125'
```

### What is the result that you expected?

`ddtrace` should be successfully imported.

**Comment by philhchen** [comment]
If possible, I'd love to get access to open a PR for this. I think you could add the following in `ddtrace/internal/agent.py`

```python
def is_ipv6_hostname(hostname):
    # type: (str) -> bool
    try:
        socket.inet_pton(socket.AF_INET6, hostname)
        return True
    except socket.error:  # not a valid address
        return False

def get_trace_hostname(default=DEFAULT_HOSTNAME):
    # type: (Union[T, str]) -> Union[T, str]
    hostname = os.environ.get("DD_AGENT_HOST", os.environ.get("DD_TRACE_AGENT_HOSTNAME", default))
    return "[{}]".format(hostname) if is_ipv6_hostname(hostname) else hostname


def get_stats_hostname(default=DEFAULT_HOSTNAME):
    # type: (Union[T, str]) -> Union[T, str]
    hostname = os.environ.get("DD_AGENT_HOST", os.environ.get("DD_DOGSTATSD_HOST", default))
    return "[{}]".format(hostname) if is_ipv6_hostname(hostname) else hostname
```

**Comment by syandroo** [comment]
+1 this would be super useful
