### ISSUE TITLE
ddtrace causes lazily imported modules to be fully loaded while

### ISSUE THREAD

**Issue by sidgandhi90w** [DataDog/dd-trace-py#4834]
### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

**Comment by brettlangdon** [comment]
hey @sidgandhi90w thank you for opening this issue.

do you have some more details about the error you are seeing?

do you have an example of a module which gets loaded in a way you do not expect?

do you happen to have a minimum reproducible example we could run to verify the problem on ourselves?

lastly, which version of our library are you using?

**Comment by sidgandhi90w** [comment]
> hey @sidgandhi90w thank you for opening this issue.
> 
> do you have some more details about the error you are seeing?
> 
> do you have an example of a module which gets loaded in a way you do not expect?
> 
> do you happen to have a minimum reproducible example we could run to verify the problem on ourselves?
> 
> lastly, which version of our library are you using?

Hey Brett, edited the original post and added details. Is there anything else you need?

**Comment by brettlangdon** [comment]
@sidgandhi90w perfect, thanks! which version of Python?

when I run on Python 3.10 I get an `AttributeError` instead:

```
Traceback (most recent call last):
  File "repro.py", line 15, in <module>
    lazy_requests = lazy_import("requests")
  File "repro.py", line 7, in lazy_import
    loader = importlib.util.LazyLoader(spec.loader)
AttributeError: 'NoneType' object has no attribute 'loader'
```

**Comment by brettlangdon** [comment]
🤦🏻 I didn't install `requests`, sorry, ignore that last message.

**Comment by brettlangdon** [comment]
ok, maybe I do need the Python version or something else. I cannot seem to reproduce the issue.


```python
# repro.py
import importlib.util
import sys


def lazy_import(name):
    spec = importlib.util.find_spec(name)
    loader = importlib.util.LazyLoader(spec.loader)
    spec.loader = loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    loader.exec_module(module)
    return module


lazy_requests = lazy_import("requests")
import ddtrace

print("success")
```

```
$ virtualenv --python 3.10 .repro
$ source .repo/bin/activate
$ pip install ddtrace==1.6.3 requests
$ python repro.py
success
$ ddtrace-run python repro.py
success
```


I also ran this to check if both `lazy_requests` and importing `requests` would end up getting patched:

```python
# repro.py
import importlib.util
import sys


def lazy_import(name):
    spec = importlib.util.find_spec(name)
    loader = importlib.util.LazyLoader(spec.loader)
    spec.loader = loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    loader.exec_module(module)
    return module


lazy_requests = lazy_import("requests")

import ddtrace


print(repr(lazy_requests.Session.send))


import requests


print(repr(requests.Session.send))
```


```python
# Not patched because `ddtrace.patch_all()` was not called, or `ddtrace-run` not used
$ python repro.py
<function Session.send at 0x1048c3b50>
<function Session.send at 0x1048c3b50>

# We do end up patching both lazy_requests and requests just fine
# We also get this result if we call `ddtrace.patch_all()` manually
$ ddtrace-run python repro.py
<BoundFunctionWrapper at 0x106443220 for function at 0x10646a4d0>
<BoundFunctionWrapper at 0x106443220 for function at 0x10646a4d0>
```

**Comment by brettlangdon** [comment]
I was able to repro with Python 3.6

**Comment by amitlissack** [comment]
I can reproduce with Python 3.9.14

**Comment by sidgandhi90w** [comment]
I just repro'd with Python 3.10.8, using the exact same commands and sequence in @brettlangdon's comment!

NOTE: using `ddtrace-run` does not cause this problem since that likely imports ddtrace before any other code is run.

**Comment by brettlangdon** [comment]
This appears to have been resolved by https://github.com/DataDog/dd-trace-py/pull/4528 which is not yet released.

It will be in 1.7.0 release which will happen after the new year.

**Comment by P403n1x87** [comment]
Just a note that this might still cause the lazy modules to be force-loaded, since we are trying to access the `__file__` attribute on each entry in `sys.modules`. Ideally, `ddtrace` should be the first thing to be imported if possible, as to reproduce the behaviour of `ddtrace-run`.

**Comment by sidgandhi90w** [comment]
Verified that this has been fixed in v1.6.4
