### ISSUE TITLE
ddtrace.internal._encoding.MsgpackStringTable.insert crashes

### ISSUE THREAD

**Issue by miohtama** [DataDog/dd-trace-py#4945]
### Summary of problem

Something breaks internally in `ddtrace` due to very long strings associated with SQL queries.

### Which version of dd-trace-py are you using?

`1.7.0`

### Which version of pip are you using?

Poetry 1.3.1

### Which libraries and their versions are you using?

```
aiohttp==3.8.3
aiosignal==1.3.1
alabaster==0.7.13
alembic==1.9.1
appnope==0.1.3
APScheduler==3.9.1.post1
asttokens==2.2.1
async-timeout==4.0.2
attrs==22.2.0
Babel==2.11.0
backcall==0.2.0
base58==2.1.1
beautifulsoup4==4.11.1
bitarray==2.6.2
bleach==5.0.1
bytecode==0.14.0
cached-property==1.5.2
cachetools==5.2.1
cattrs==22.2.0
certifi==2022.12.7
charset-normalizer==2.1.1
chart-studio==1.1.0
cli-helpers==2.3.0
click==7.1.2
coloredlogs==15.0.1
colorlover==0.3.0
configobj==5.0.6
contourpy==1.0.5
cufflinks==0.17.3
cycler==0.11.0
cytoolz==0.12.1
dataclasses-json==0.5.7
datadog==0.44.0
ddsketch==2.0.4
ddtrace==1.7.0
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.13
discord-webhook==1.0.0
docutils==0.17.1
dramatiq==1.13.0
entrypoints==0.4
envier==0.4.0
eth-abi==2.2.0
eth-account==0.5.9
eth-bloom==1.0.4
eth-hash==0.3.3
eth-keyfile==0.5.1
eth-keys==0.3.4
eth-rlp==0.2.1
eth-tester==0.6.0b6
eth-typing==2.3.0
eth-utils==1.10.0
exceptiongroup==1.1.0
executing==1.2.0
fastjsonschema==2.16.2
fonttools==4.37.3
freezegun==1.2.2
frozenlist==1.3.3
futureproof==0.3.1
gprof2dot==2022.7.29
gql==2.0.0
graphql-core==2.3.2
greenlet==2.0.1
hexbytes==0.2.3
humanfriendly==10.0
idna==3.4
imagesize==1.4.1
iniconfig==2.0.0
ipdb==0.13.11
ipfshttpclient==0.8.0a2
ipykernel==6.15.3
ipython==8.8.0
ipywidgets==8.0.2
jedi==0.18.2
Jinja2==3.1.2
jsonlines==3.1.0
jsonschema==4.17.3
jupyter-core==4.11.1
jupyter_client==7.4.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.3
kiwisolver==1.4.4
lru-dict==1.1.8
lxml==4.9.1
Mako==1.2.4
MarkupSafe==2.1.1
marshmallow==3.19.0
marshmallow-enum==1.5.1
matplotlib==3.6.0
matplotlib-inline==0.1.6
mistune==2.0.4
mplfinance==0.12.9b1
multiaddr==0.0.9
multidict==6.0.4
multiprocessing-logging==0.3.3
mypy-extensions==0.4.3
nbclient==0.7.0
nbconvert==7.2.1
nbformat==5.7.0
nbsphinx==0.8.9
nest-asyncio==1.5.6
netaddr==0.8.0
numpy==1.24.1
opentracing==2.4.0
packaging==23.0
pandas==1.5.2
pandocfilters==1.5.0
parsimonious==0.8.1
parso==0.8.3
pendulum==2.1.2
pexpect==4.8.0
pgcli==3.5.0
pgspecial==2.0.1
pickleshare==0.7.5
Pillow==9.2.0
plotly==5.11.0
pluggy==1.0.0
prometheus-client==0.15.0
promise==2.3
prompt-toolkit==3.0.36
protobuf==3.20.1
psutil==5.9.4
psycopg==3.0.18
psycopg2==2.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
py-ecc==5.2.0
py-evm==0.5.0a3
py-geth==3.10.0
pyarrow==7.0.0
pycryptodome==3.16.0
pyethash==0.1.27
Pygments==2.14.0
pyparsing==3.0.9
pyrsistent==0.19.3
pysha3==1.0.2
pytest==7.2.0
pytest-mock==3.10.0
pytest-profiling==1.7.0
python-dateutil==2.8.2
python-logging-discord-handler==0.1.4
python-redis-lock==3.7.0
python-slugify==5.0.2
pytz==2022.7
pytz-deprecation-shim==0.1.0.post0
pytzdata==2020.1
pyzmq==24.0.1
redis==4.4.2
requests==2.28.2
requests-mock==1.10.0
retry==0.9.2
retrying==1.3.3
rlp==2.0.1
Rx==1.6.3
scipy==1.10.0
semantic-version==2.10.0
setproctitle==1.3.2
setuptools-scm==7.0.5
six==1.16.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
Sphinx==4.5.0
sphinx-autodoc-typehints==1.19.1
sphinx-rtd-theme==1.1.1
sphinx-sitemap==2.2.1
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib.applehelp==1.0.3
SQLAlchemy==1.4.18
SQLAlchemy-Utils==0.37.9
sqlparse==0.4.3
stack-data==0.6.2
tabulate==0.9.0
tenacity==8.1.0
text-unidecode==1.3
tinycss2==1.1.1
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
tornado==6.2
tqdm==4.64.1
tqdm-loggable==0.1.2
trading-strategy==0.9.1
trading-strategy-backtrader==0.1
traitlets==5.8.1
trie==2.0.0a5
typing-extensions==3.10.0.2
typing-inspect==0.8.0
tzdata==2022.7
tzlocal==4.2
ujson==5.7.0
urllib3==1.26.14
varint==1.0.2
waitress==2.1.2
wcwidth==0.2.5
web3==5.31.0
web3-ethereum-defi==0.13.8
webencodings==0.5.1
WebOb==1.8.7
websockets==9.1
WebTest==2.0.35
widgetsnbextension==4.0.3
wrapt==1.14.1
xmltodict==0.13.0
yarl==1.8.2
```

### How can we reproduce your problem?

There is not yet a clear pattern of what is producing this, but my gut feeling is that `ddtrace` tries to serialise a very long SQL query, and it causes something to break internally.

### What is the result that you get?

ddtrace logs an error to Python logging output.

```
| Traceback (most recent call last):
|   File "/usr/local/lib/python3.10/site-packages/ddtrace/span.py", line 503, in __exit__
|     self.finish()
|   File "/usr/local/lib/python3.10/site-packages/ddtrace/span.py", line 245, in finish
|     cb(self)
|   File "/usr/local/lib/python3.10/site-packages/ddtrace/tracer.py", line 746, in _on_span_finish
|     p.on_span_finish(span)
|   File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/processor/trace.py", line 206, in on_span_finish
|     self._writer.write(spans)
|   File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 545, in write
|     self._encoder.put(spans)
|   File "ddtrace/internal/_encoding.pyx", line 683, in ddtrace.internal._encoding.MsgpackEncoderV05.put
|   File "ddtrace/internal/_encoding.pyx", line 684, in ddtrace.internal._encoding.MsgpackEncoderV05.put
|   File "ddtrace/internal/_encoding.pyx", line 690, in ddtrace.internal._encoding.MsgpackEncoderV05.put
|   File "ddtrace/internal/_encoding.pyx", line 687, in ddtrace.internal._encoding.MsgpackEncoderV05.put
|   File "ddtrace/internal/_encoding.pyx", line 472, in ddtrace.internal._encoding.MsgpackEncoderBase.put
|   File "ddtrace/internal/_encoding.pyx", line 476, in ddtrace.internal._encoding.MsgpackEncoderBase.put
|   File "ddtrace/internal/_encoding.pyx", line 499, in ddtrace.internal._encoding.MsgpackEncoderBase.put
|   File "ddtrace/internal/_encoding.pyx", line 480, in ddtrace.internal._encoding.MsgpackEncoderBase.put
|   File "ddtrace/internal/_encoding.pyx", line 467, in ddtrace.internal._encoding.MsgpackEncoderBase._pack_trace
|   File "ddtrace/internal/_encoding.pyx", line 708, in ddtrace.internal._encoding.MsgpackEncoderV05.pack_span
|   File "ddtrace/internal/_encoding.pyx", line 693, in ddtrace.internal._encoding.MsgpackEncoderV05._pack_string
|   File "ddtrace/internal/_encoding.pyx", line 184, in ddtrace.internal._encoding.StringTable._index
|   File "ddtrace/internal/_encoding.pyx", line 248, in ddtrace.internal._encoding.MsgpackStringTable.insert
ValueError: Cannot insert 'SELECT count(*) AS count_1
... very large SQL query dump follows...
...  %(id_1_1311060)s, %(id_1_1311061)s, %(id_1_1311062)s, %(id_1_1311063)s, %(id_1_1311064)s, %(id_1_1311065)s, %(id_1_1311066)s, %(id_1_1311067)s, %(id_1_1311068)s, %(id_1_1311069)s, %(id_1_1311070)s, %(id_1_1311071)s, %(id_1_1311072)s, %(id_1_1311073)s, %(id_1_1311074)s, %(id_1_1
311075)s, %(id_1_1311076)s, %(id_1_1311077)s, %(id_1_1311078)s, %(id_1_1311079)s, %(id_1_1311080)s, %(id_1_1311081)s, %(id_1_1311082)s, %(id_1_1311083)s, %(id_1_1311084)s, %(id_1_1311085)s, %(id_1_1311086)s, %(id_1_1311087)s, %(id_1_1311088)s, %(id_1_1311089)s, %(id_1_1311090)s, %(id_1_1311091)s,
%(id_1_1311092)s, %(id_1_1311093)s, %(id_1_1311094)s, %(id_1_1311095)s, %(id_1_1311096)s, %(id_1_1311097)s, %(id_1_1311098)s, %(id_1_1311099)s, %(id_1_1311100)s, %(id_1_1311101)s, %(id_1_1311102)s, %(id_1_1311103)s, %(id_1_1311104)s, %(id_1_1311105)s, %(id_1_1311106)s, %(id_1_1311107)s, %(id_1_131
1108)s, %(id_1_1311109)s, %(id_1_1311110)s, %(id_1_1311111)s, %(id_1_1311112)s, %(id_1_1311113)s)': string table is full (current size: 42, max size: 8388608).
```

I am not sure `string table is full (current size: 42, max size: 8388608)` is internal to ddtrace, or is it a part of a failing SQL query error message.

### What is the result that you expected?

- ddtrace can handle situations with problematic very long SQL queries
- if ddtrace cannot handle these situations, it will output a helpful exception message on how to disable it for these queries or increase its internal buffers

**Comment by P403n1x87** [comment]
This is indeed due to a potentially large string, like the reported SQL query, which can cause the internal string table to fill beyond the backing buffer capacity. This happening could be an indication that the generated traces could be larger than the maximum trace size that we allow to be serialised with default limits, which in itself would be another issue. The default buffer size can be increased with `DD_TRACE_WRITER_BUFFER_SIZE_BYTES` (the default is the logged value `8388608` i.e. 8 MB). It's perhaps worth trying to bump it to e.g. `15000000` to see if it helps with the issue.

**Comment by miohtama** [comment]
Thank you @P403n1x87.

Two questions 

- Do you know if this is related to exceptions in general or just SQL? If I do `patch_all(sqlalchemy=False, psycopg=False)` is this problem likely to go away, as I do not need SQL tracing at the moment?
- Is there a way to pass `DD_TRACE_WRITER_BUFFER_SIZE_BYTES` as initializer argument from Python code instead of environment variable?

**Comment by P403n1x87** [comment]
> * Do you know if this is related to exceptions in general or just SQL? I am not sure if the root cause is that DD tried to capture the SQL query or DD tried to capture an exception. If I do `patch_all(sqlalchemy=False, psycopg=False)` is this problem likely to go away, as I do not need SQL tracing at the moment?

This is a general exception (that we probably don't handle too gracefully at the moment as we didn't expect the string table to fill up the entire buffer for itself) that can happen when very long string occurs in traces (e.g. as values of tags, like the reported long SQL queries). So turning off the source of such long strings, like you're suggesting, should prevent this issue from occurring.

> * Is there a way to pass `DD_TRACE_WRITER_BUFFER_SIZE_BYTES` as initializer argument from Python code instead of environment variable?

I don't think we provide that programmatic API at the moment unfortunately, but I'd like either @brettlangdon or @Kyle-Verhoog to confirm this.

**Comment by bissli82** [comment]
Same issue here, please address

![image](https://user-images.githubusercontent.com/6223793/218760118-6caa6403-f475-428c-853d-6b630d4592ec.png)


![image](https://user-images.githubusercontent.com/6223793/218759976-4278acf5-0aab-456e-8f5e-afe29b88c803.png)

**Comment by emmettbutler** [comment]
I've opened a pull request suggesting a fix for this issue. Check it out and let me know your thoughts @P403n1x87 @miohtama https://github.com/DataDog/dd-trace-py/pull/5375

**Comment by emmettbutler** [comment]
Fixed in https://github.com/DataDog/dd-trace-py/pull/5375
