### ISSUE TITLE
Disable datadog tracer library logs

### ISSUE THREAD

**Issue by riyadparvez** [DataDog/dd-trace-py#4961]
### Summary of problem

Apologies if this is not the place to ask for help. Our application log is flooded with error messages from datadog. Please see below. Setting aside the error messges themselves is there a way to completely disable all the logs from datadog library?

```
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/ddtrace/internal/remoteconfig/client.py", line 407, in request
    response = self._send_request(payload)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/ddtrace/internal/remoteconfig/client.py", line 248, in _send_request
    self._conn.request("POST", "v0.7/config", payload, self._headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
```

### Which version of dd-trace-py are you using?
1.7.0

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

**Comment by juanjux** [comment]
Hi @riyadparvez, we just opened a PR related to this, should be in 1.9. Regarding your question, you can change ddtrace logging with this snippet (in this case it would only show messages with a log level of ERROR):

```python
import logging
ddlog = logging.getLogger("ddtrace")
ddlog.setLevel(logging.ERROR)
```

**Comment by riyadparvez** [comment]
Thank you for your prompt response. Just out of curiosity, what exactly is this error message is about? Since we can see our logs/metrics showing up on datadog. So the tracer must be connected to the agent on the node

**Comment by juanjux** [comment]
Hi @riyadparvez,

This error is a connection from the tracer library the datadog host. Metrics and logs will work because they're collected by the host directly, not by the tracer. But things like remote configuration management and some tags (like ASM tags) would not work. My advice would be to check the connection to the configured agent host and URL if you want these features to work.
