### ISSUE TITLE
Lambda Layer is crashing because of infinite recursion

### ISSUE THREAD

**Issue by rajveerappan** [DataDog/dd-trace-py#5286]
### Summary of problem

Similar to the issue described in https://github.com/DataDog/dd-trace-py/issues/5220 we are seeing a crash due to the `wrap_signals` handler even though we're not using `signal` in our code, nor is the lambda close to timing out when the error shows up.

### Which version of dd-trace-py are you using?

1.9.2

### Which version of pip are you using?

23.0.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
  datadog-lambda==4.68.0
  datadog==0.44.0
  ddtrace==1.9.2
  ddsketch==2.0.4
</details>

### How can we reproduce your problem?

- Deploy a lambda app as described in [the following official documentation](https://docs.datadoghq.com/serverless/installation/python/?tab=containerimage)
- A small percentage of invocations fail. In our case it seemed to be between 20-50 per 10K invocations. Unfortunately no more reliable repro steps available.

### What is the result that you get?

The whole lambda request fails with the following Cloudwatch logs:
```
START RequestId: ef1dce6b-d81c-41d6-866f-4bdc6413128b Version: $LATEST
--
  | Traceback (most recent call last):
  | File "/var/runtime/bootstrap.py", line 480, in <module>
  | main()
  | File "/var/runtime/bootstrap.py", line 462, in main
  | event_request = lambda_runtime_client.wait_next_invocation()
  | File "/var/runtime/lambda_runtime_client.py", line 49, in wait_next_invocation
  | response_body, headers = rapid_client.next()
  | File "/var/lang/lib/python3.8/site-packages/ddtrace/contrib/aws_lambda/patch.py", line 49, in wrap_signals
  | old_signal(*args, **kwargs)
  | File "/var/lang/lib/python3.8/site-packages/ddtrace/contrib/aws_lambda/patch.py", line 49, in wrap_signals
  | old_signal(*args, **kwargs)
  | File "/var/lang/lib/python3.8/site-packages/ddtrace/contrib/aws_lambda/patch.py", line 49, in wrap_signals
  | old_signal(*args, **kwargs)
  | [Previous line repeated 994 more times]
  | RecursionError: maximum recursion depth exceeded
  | RequestId: ef1dce6b-d81c-41d6-866f-4bdc6413128b Error: Runtime exited with error: exit status 1 Runtime.ExitError
  | END RequestId: ef1dce6b-d81c-41d6-866f-4bdc6413128b
  | REPORT RequestId: ef1dce6b-d81c-41d6-866f-4bdc6413128b Duration: 3597.12 ms Billed Duration: 3598 ms Memory Size: 256 MB Max Memory Used: 221 MB XRAY TraceId: **** SegmentId: 3ffa4ed72d5b3955 Sampled: true
```

### What is the result that you expected?
Such an error shouldn't occur.

**Comment by rajveerappan** [comment]
@duncanista I think you tackled the other issue. One thing to note here is that both this issue and https://github.com/DataDog/dd-trace-py/issues/5220 we are only seeing in our environments that are using containerized lambda deploy. We also have environments where we are doing zip based lambda deploy and have not seen these issues there.

**Comment by duncanista** [comment]
Hey @rajveerappan 

Thank you for bringing this out. I've noticed this only happens for containerized lambda deployments. I'll keep working and researching the root cause for this. It would be really helpful if you could raise a ticket with Datadog, so we can take a look more in depth into the logs of your specific case, it might gave us some insight.

I understand it's really complex to reproduce. I can recommend locking the `1.8.x` of the tracer in the meantime. 

Thanks, again.

**Comment by duncanista** [comment]
Hey @rajveerappan,

I was not able to reproduce it. I thought maybe the AWS Lambda function was not removing defined signals after invocations, no matter if the environment was warm. I proved that this was not the case by debugging the code. 

Nonetheless, I've made sure our signal is removed after an invocation – no matter if it was an impending timeout, or a successful run. This way, we are hoping to avoid previous signals defined by us. 
On the other hand, I also added a check to make sure the incoming signal `f` was not `wrap_signals`. 

I've opened a PR, will get it through the weekend.

**Comment by rajveerappan** [comment]
thank you @duncanista!
