### ISSUE TITLE
Throws exception when reloading module in REPL (specifically with iPython), even when `DD_TRACE_ENABLED=false`

### ISSUE THREAD

**Issue by oryband** [DataDog/dd-trace-py#5345]
### Summary of problem

The exception includes this stack trace:
```python
[autoreload of my_module failed: Traceback (most recent call last):
  File "/home/ory/.pyenv/versions/3.10.7/envs/my_module/lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 261, in check
    superreload(m, reload, self.old_objects)
  File "/home/ory/.pyenv/versions/3.10.7/envs/my_module/lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 459, in superreload
    module = reload(module)
  File "/home/ory/.pyenv/versions/3.10.7/lib/python3.10/importlib/__init__.py", line 166, in reload
    spec = module.__spec__ = _bootstrap._find_spec(name, pkgpath, target)
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "/home/ory/.pyenv/versions/3.10.7/envs/my_module/lib/python3.10/site-packages/ddtrace/internal/module.py", line 368, in find_spec
    spec = find_spec(fullname)
  File "/home/ory/.pyenv/versions/3.10.7/lib/python3.10/importlib/util.py", line 111, in find_spec
    raise ValueError('{}.__spec__ is not set'.format(name)) from None
ValueError: my_module.__spec__ is not set
```

### Which version of dd-trace-py are you using?

1.8.0 

### Which version of pip are you using?

22.2.2

**Comment by emmettbutler** [comment]
Thank you for reporting this issue, @oryband. How can I reproduce it locally?

**Comment by P403n1x87** [comment]
@oryband would you be happy to upgrade to the latest ddtrace release after the fix is merged, or would you prefer this backported to 1.8?

**Comment by oryband** [comment]
> @oryband would you be happy to upgrade to the latest ddtrace release after the fix is merged, or would you prefer this backported to 1.8?

Hey @P403n1x87 ; thanks for taking care of this issue, sorry for taking so long. Not critical to backport. Thank you
