### ISSUE TITLE
Version 1.11.0 breaks confluent-kafka `AvroConsumer` and `AvroProducer` classes

### ISSUE THREAD

**Issue by ffissore** [DataDog/dd-trace-py#5494]
Version 1.11.0 breaks confluent-kafka `AvroConsumer` and `AvroProducer` classes, because, compared to `Consumer` and `Producer`, they have additional fields not listed in the `__slots__` of `TracedConsumer` and `TracedProducer`.

The traceback is
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 521, in <module>
    AvroConsumer(
  File "/home/federico/.pyenv/versions/test-env/lib/python3.11/site-packages/confluent_kafka/avro/__init__.py", line 161, in __init__
    self._serializer = MessageSerializer(schema_registry, reader_key_schema, reader_value_schema)
    ^^^^^^^^^^^^^^^^
AttributeError: 'cimpl.Consumer' object has no attribute '_serializer'
```

[I have a fix](https://github.com/DataDog/dd-trace-py/compare/1.x...ffissore:dd-trace-py:1.x) but it's probably naive and lacks test coverage. I'll try to make it better in the coming days but don't hold your breath.

_Originally posted by @ffissore in https://github.com/DataDog/dd-trace-py/issues/5027#issuecomment-1497542203_

**Comment by ffissore** [comment]
For anyone stumbling on this, you can disable confluent kafka patching by adding this env var: `DD_PATCH_MODULES=kafka:false`

**Comment by Yun-Kim** [comment]
Hi @ffissore, thanks for reaching out!
I was able to reproduce your issue, and fixed in #5545 by inheriting our traced producer/consumer classes directly from confluent_kafka's Producer/Consumer base classes. Our usual approach of wrapping these classes with an ObjectProxy resulted in this issue since confluent_kafka's base classes are implemented in C.
