### ISSUE TITLE
AttributeError for SQLite Traces in v1.13.4

### ISSUE THREAD

**Issue by seandstewart** [DataDog/dd-trace-py#5993]
### Summary of problem

This appears to be similar to #5821 

I occasionally get an AttributeError on the IntegrationConfig object, however it's not consistent.

### Which version of dd-trace-py are you using?
v1.13.4

### Which version of pip are you using?

v22.3.1 

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
```
aiokafka==0.8.0
async-timeout==4.0.2
attrs==23.1.0
black==23.3.0
bumpver==2022.1120
bytecode==0.14.2
cachetools==5.3.1
cattrs==23.1.1
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
coverage==6.5.0
cryptography==41.0.0
datadog==0.45.0
ddsketch==2.0.4
ddtrace==1.13.4
Deprecated==1.2.14
envier==0.4.0
factory-boy==3.2.1
Faker==18.9.0
fastavro==1.7.4
flake8==6.0.0
flake8-bugbear==23.5.9
flake8-gl-codeclimate==0.1.6
future-typing==0.4.1
google-api-core==2.11.0
google-auth==2.19.0
google-cloud-pubsub==2.17.1
googleapis-common-protos==1.59.0
grpc-google-iam-v1==0.12.6
grpcio==1.54.2
grpcio-status==1.54.2
hiredis==2.2.3
idna==3.4
importlib-metadata==6.0.1
inflection==0.5.1
iniconfig==2.0.0
isort==5.12.0
jsonschema==4.17.3
kafka-python==2.0.2
lexid==2021.1006
mccabe==0.7.0
multidict==5.2.0
mypy==1.3.0
mypy-extensions==1.0.0
opentelemetry-api==1.18.0
opentracing==2.4.0
orjson==3.8.14
packaging==23.1
pathlib2==2.3.7.post1
pathspec==0.11.1
pendulum==2.1.2
platformdirs==3.5.1
pluggy==1.0.0
proto-plus==1.22.2
protobuf==4.23.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycodestyle==2.10.0
pycparser==2.21
pyflakes==3.0.1
pyrsistent==0.19.3
pytest==7.3.1
pytest-asyncio==0.21.0
pytest-cov==3.0.0
pytest-parametrize-suite==23.1.2
python-dateutil==2.8.2
python-dotenv==1.0.0
pytzdata==2020.1
redis==4.5.5
requests==2.31.0
rsa==4.9
six==1.16.0
structlog==23.1.0
tenacity==8.2.2
toml==0.10.2
types-boto==2.49.18.8
types-protobuf==4.23.0.1
types-pyOpenSSL==23.1.0.3
types-python-dateutil==2.8.19.13
types-redis==4.5.5.2
types-requests==2.31.0.1
types-setuptools==67.8.0.0
types-six==1.16.21.8
types-ujson==5.7.0.5
types-urllib3==1.26.25.13
typical==2.8.1
typing_extensions==4.6.2
urllib3==1.26.16
uvloop==0.17.0
wrapt==1.15.0
xmltodict==0.13.0
zipp==3.15.0
```
</details>

### How can we reproduce your problem?

I'm only able to reproduce this when running a full test suite in pytest with pytest-cov, however a small test suite failed to reproduce the issue. I have tried to isolate a min-reproducible but it is eluding me at this point. I'll keep looking into it, but wanted to raise the issue.

### What is the result that you get?

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/pytest_cov/plugin.py", line 294, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/pytest_cov/engine.py", line 44, in ensure_topdir_wrapper
INTERNALERROR>     return meth(self, *args, **kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/pytest_cov/engine.py", line 231, in finish
INTERNALERROR>     self.cov.save()
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/control.py", line 710, in save
INTERNALERROR>     data = self.get_data()
INTERNALERROR>            ^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/control.py", line 782, in get_data
INTERNALERROR>     if self._collector and self._collector.flush_data():
INTERNALERROR>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/collector.py", line 473, in flush_data
INTERNALERROR>     self.covdata.add_arcs(self.mapped_file_dict(data))
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/sqldata.py", line 238, in _wrapped
INTERNALERROR>     return method(self, *args, **kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/sqldata.py", line 499, in add_arcs
INTERNALERROR>     self._choose_lines_or_arcs(arcs=True)
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/sqldata.py", line 528, in _choose_lines_or_arcs
INTERNALERROR>     with self._connect() as con:
INTERNALERROR>          ^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/sqldata.py", line 315, in _connect
INTERNALERROR>     self._open_db()
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/sqldata.py", line 266, in _open_db
INTERNALERROR>     self._read_db()
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/sqldata.py", line 270, in _read_db
INTERNALERROR>     with self._dbs[threading.get_ident()] as db:
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/sqldata.py", line 1083, in __enter__
INTERNALERROR>     self._connect()
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/coverage/sqldata.py", line 1062, in _connect
INTERNALERROR>     self.con = sqlite3.connect(self.filename, check_same_thread=False)
INTERNALERROR>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/ddtrace/contrib/sqlite3/patch.py", line 44, in traced_connect
INTERNALERROR>     return patch_conn(conn)
INTERNALERROR>            ^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/ddtrace/contrib/sqlite3/patch.py", line 48, in patch_conn
INTERNALERROR>     wrapped = TracedSQLite(conn)
INTERNALERROR>               ^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/ddtrace/contrib/sqlite3/patch.py", line 73, in __init__
INTERNALERROR>     cursor_cls = TracedSQLiteFetchCursor if config.sqlite.trace_fetch_methods else TracedSQLiteCursor
INTERNALERROR>                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/seanstewart/PycharmProjects/maven-sdk-streams-python/.venv/lib/python3.11/site-packages/ddtrace/internal/utils/attrdict.py", line 27, in __getattr__
INTERNALERROR>     return object.__getattribute__(self, key)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> AttributeError: 'IntegrationConfig' object has no attribute 'trace_fetch_methods'
```

### What is the result that you expected?

No errors.

**Comment by emmettbutler** [comment]
Thanks for the bug report, @seandstewart.

The first thing I recommend trying is setting the environment variable `DD_TRACE_SQLITE3_ENABLED=False`. It looks to me like ddtrace is attempting to patch `pytest`'s use of `sqlite3` via `coverage`, which probably doesn't always initialize the ddtrace integration properly.

**Comment by emmettbutler** [comment]
@seandstewart did disabling the sqlite3 integration work for you?

**Comment by seandstewart** [comment]
@emmettbutler - yes, disabling the sqlite3 integration worked
