### ISSUE TITLE
Unexpected ssl issue after `1.14.0` upgrade

### ISSUE THREAD

**Issue by mattupstate** [DataDog/dd-trace-py#6041]
### Summary of problem

After upgrading to `ddtrace=1.14.0` an application that makes HTTP requests to other services over SSL started experiencing an issue with Python's built-in `ssl` module. Any libraries that use the `ssl` module are experiencing an internal traceback, such as `requests` and `boto3`. For example, here is an example traceback that occurs internally to the `botocore` module:

```
botocore.exceptions.HTTPClientError: An HTTP Client raised an unhandled exception: 'int' object is not callable
Traceback (most recent call last):
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/httpsession.py", line 405, in send
    urllib_response = conn.urlopen(
  File "/srv/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/srv/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/srv/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/srv/app/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/srv/app/.venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 424, in ssl_wrap_socket
    context.set_alpn_protocols(ALPN_PROTOCOLS)
  File "/usr/local/lib/python3.10/ssl.py", line 566, in set_alpn_protocols
    if len(b) == 0 or len(b) > 255:
TypeError: 'int' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/app/.venv/lib/python3.10/site-packages/ddtrace/contrib/botocore/patch.py", line 415, in patched_api_call
    result = original_func(*args, **kwargs)
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/client.py", line 711, in _make_api_call
    http, parsed_response = self._make_request(
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/client.py", line 731, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/endpoint.py", line 107, in make_request
    return self._send_request(request_dict, operation_model)
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/endpoint.py", line 183, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/endpoint.py", line 305, in _needs_retry
    responses = self._event_emitter.emit(
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 192, in __call__
    if self._checker(**checker_kwargs):
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 265, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 331, in __call__
    checker_response = checker(attempt_number, response,
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 231, in __call__
    return self._check_caught_exception(
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 374, in _check_caught_exception
    raise caught_exception
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/endpoint.py", line 249, in _do_get_response
    http_response = self._send(request)
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/endpoint.py", line 321, in _send
    return self.http_session.send(request)
  File "/srv/app/.venv/lib/python3.10/site-packages/botocore/httpsession.py", line 450, in send
    raise HTTPClientError(error=e)
botocore.exceptions.HTTPClientError: An HTTP Client raised an unhandled exception: 'int' object is not callable
```
It's as if something has patched the `ssl` module in such a way that it confuses the `len` global function with a parameter named `len`. The only breadcrumb on the internet I could find that looks at all similar is an [httpx discussion](https://github.com/encode/httpx/discussions/2285). 

And for what it's wroth, I'm reporting this here at this time is because the issue began after upgrading `ddtrace` to `1.14.0` and no other dependencies.

### Which version of dd-trace-py are you using?

`1.14.0`

### Which version of pip are you using?

N/A

### Which libraries and their versions are you using?

Versions of things that may affect this:

```
python = 3.10.10 (via python:3.10.10-slim-bullseye Docker image)
aiohttp = ^3.8.1
fastapi = ^0.94.1
hypercorn = ^0.14.0
requests = ^2.26.0
aioboto3 = ^9.3.0
redis = ^4.5.5
ddtrace = 1.11.6
httpx = ^0.23.0
uvloop = ^0.16.0
hiredis = ^2.2.2
```

### How can we reproduce your problem?

I have been unable to reproduce this in a local environment with our closed source application. I haven't been able to reproduce this with a minimal example either.

### What is the result that you get?

See traceback above.

### What is the result that you expected?

No internal `ssl` module errors.

**Comment by P403n1x87** [comment]
@mattupstate we've had reports of a similar issue with previous versions of `ddtrace`, with `httpx` being a common denominator. Do you have other dependencies, like `numpy`, that make use of Cython by any chance? Was `ddtrace` the only dependency that was updated? If not, would you perhaps be able to test with the previous version of `ddtrace` that you were using (which one was it?) to indeed make sure that the issue comes from the upgrade of `ddtrace`? 🙏 

Just so that we can gather more information, what products from `ddtrace` are you using (e.g. tracing and/or profiling etc...). Cheers!

**Comment by mattupstate** [comment]
@P403n1x87 Ah, yes. `numpy` is a transitive dependency in the application here. And to confirm `ddtrace` was the only dependency updated at the time the problem began to appear. And finally, we're using tracing and profiling in the environment we saw this issue in.

**Comment by P403n1x87** [comment]
@mattupstate thanks for the extra details. Would you be able to share which version of `numpy` gets pulled in? Does the problem go away if profiling is disabled with `DD_PROFILING_ENABLED=0`?

**Comment by emmettbutler** [comment]
I'm going to close this due to lack of activity. Please comment or reopen if there's new information to share.
