### ISSUE TITLE
Opentracing SpanContextCorruptedException

### ISSUE THREAD

**Issue by raybotha** [DataDog/dd-trace-py#606]
Using the ddtracer.opentracing exactly as in the example, just switching it out with the current Jaeger setup we're using, I get this exception on all requests:
```python
ERROR:root:tracer.extract() failed
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/grpc_opentracing/_server.py", line 117, in _start_span
     opentracing.Format.HTTP_HEADERS, dict(metadata))
   File "/usr/local/lib/python3.6/site-packages/ddtrace/opentracer/tracer.py", line 291, in extract
     return propagator.extract(carrier)
   File "/usr/local/lib/python3.6/site-packages/ddtrace/opentracer/propagation/http.py", line 73, in extract
     raise SpanContextCorruptedException('failed to extract span context')
 opentracing.propagation.SpanContextCorruptedException: failed to extract span context
```
The spans do make it do datadog though, they're just errors of course:
![screenshot from 2018-09-16 01 48 50](https://user-images.githubusercontent.com/9902896/45591422-be8a6d80-b952-11e8-95f3-271fe5130fd8.png)

Using Python 3.6.6 with ddtrace[opentracing] and grpcio-opentracing 1.1.3.

**Comment by Kyle-Verhoog** [comment]
@raybotha 

I'll look into the parenting issue, it might be related to the `grpcio-opentracing`.


As for the side note:

The logs are probably coming as a result of our agent setting the sample rate for your services. This can overridden to force the trace to be sampled in the opentracer by setting the `SAMPLING_PRIORITY` tag on the span to one of these values: https://github.com/DataDog/dd-trace-py/blob/3a4e3fe859c889da997c9ca612714eaefb1a0f4a/ddtrace/ext/priority.py#L17-L24.

The same principles as stated here: http://pypi.datadoghq.com/trace/docs/advanced_usage.html#priority-sampling apply to the opentracer as well.

Let me know if this is unclear or if that issue still persists! 😄

**Comment by raybotha** [comment]
Thanks Kyle, I'll take a stab at setting the sampling priority on the context.

I'll also try and take a look at the interaction between datadog and the `grpcio-opentracing`, it's an odd bug.

**Comment by raybotha** [comment]
Regarding the side note, I tried assigning a sampling priority of 2 to all spans, and also tried patching the RateSampler to sample 100%. The effect is that there are _more_ traces coming through but I think some still get discarded due to the volume, this also increases the amount of spans missing children and parents, probably due to the other spans not being sampled on a different host.

So I've gone back to the regular `priority_sampling: True` config, but I would still like to eliminate spans that get dropped out of a distributed trace. If I understand the tracer code correctly this isn't supposed to happen by the way the `Context` is used, maybe it's related to the context issue with redis/psycopg? But these opentracer spans are only missing around 50% of the time with a one client and one server setup.

**Comment by Kyle-Verhoog** [comment]
Hey @raybotha, I was able to track down the parenting issue, was an oversight on my part with the span context propagation. A fix is provided in #608 on branch `kyle-verhoog/ot-dist-fix`, let me know if this fixes your parenting issue. 😄

**Comment by raybotha** [comment]
Awesome @Kyle-Verhoog, I tested your patch and it does fix it:
![sa](https://user-images.githubusercontent.com/9902896/45708378-95035900-bb81-11e8-9fa2-b25ea9ec1f54.png)
Thanks!
Some opentracing traces don't have the full context though, are distributed traces supposed to always be complete, or if one span doesn't get sampled should the other spans in a trace also be discarded? This is the same call and expected exception as the screenshot right above but somehow the server spans didn't make it:
![sb](https://user-images.githubusercontent.com/9902896/45708560-0e02b080-bb82-11e8-8eb4-b34d2f783cd3.png)
Or is that to be expected?

**Comment by raybotha** [comment]
Here is the same situation with identical successful calls, the server is always called. I can't find a trace where this happens with redis or postgres - those two are always part of the server trace as expected.
![sc](https://user-images.githubusercontent.com/9902896/45709024-363edf00-bb83-11e8-90f3-f8e344cf982d.png)
![sd](https://user-images.githubusercontent.com/9902896/45709028-38a13900-bb83-11e8-936f-7cce41cf4c59.png)

**Comment by Kyle-Verhoog** [comment]
In order to prevent parts of the trace from being sampled you have to set the sampling priority on the parent span of the distributed trace as soon as the trace is started (or just before any sort of propagation).

This would look something like:

```python
from ddtrace.ext.priority import USER_KEEP
span = tracer.start_span(...) # the parent of the distributed trace
span.set_tag('SAMPLING_PRIORITY', USER_KEEP)
```

This should work, let me know if it doesn't (I think you mentioned that you set it on all the spans in an earlier comment, but wanted to make sure).

This does seem like an issue for OpenTracing integrations like `grpcio-opentracing` since this requires the user of the opentracer to somehow gain access to the parent (which they might not have). It might be worth exploring making this configurable from the tracer itself such that all spans will include the sampling priority.

**Comment by raybotha** [comment]
Perfect, I patched the `ddtrace.tracer`'s `start_span` method to set the sampling priority to `USER_KEEP` if it is a root span. Thanks Kyle, I think everything's running smoothly now.
