### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused Profiling

### ISSUE THREAD

**Issue by aleixisp** [DataDog/dd-trace-py#6184]
### Summary of problem
ConnectionRefusedError: [Errno 111] Connection refused

I'm getting this error from the terminal when starting it.
```
2023-06-21 14:00:29,230 - ddtrace.profiling.scheduler - ERROR - Unexpected error while exporting events. Please report this bug to https://github.com/DataDog/dd-trace-py/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ddtrace/profiling/scheduler.py", line 53, in flush
    exp.export(events, start, self._last_export)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/profiling/exporter/http.py", line 227, in export
    self._upload(client, self.endpoint_path, body, headers)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/internal/utils/retry.py", line 48, in retry_wrapped
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/ddtrace/internal/utils/retry.py", line 39, in retry_wrapped
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/profiling/exporter/http.py", line 233, in _upload
    client.request("POST", path, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/usr/local/lib/python3.9/http/client.py", line 923, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
¡ConnectionRefusedError: [Errno 111] Connection refused
```
### Which version of dd-trace-py are you using?
1.15.0
### Which version of pip are you using?
22.2.2

### Which libraries and their versions are you using?
```
[packages]
flask-mongoengine = "==1.0.0"
flask = "==2.1.0"
python-dotenv = "==0.18.0"
flask-cors = "==3.0.10"
flask-jwt-extended = "==4.2.1"
flask-mail = "==0.9.1"
marshmallow = "==3.12.1"
boto3 = "==1.17.98"
phonenumbers = "==8.12.25"
requests = "==2.25.1"
gunicorn = "==20.1.0"
dnspython = "==2.1.0"
twilio = "<6.51.0"
solana = "==0.9.2"
urllib3 = "==1.26.7"
tblib = "==1.7.0"
flask-limiter = "==2.4.6"
importlib-metadata = "==4.12.0"
mixpanel = "==4.10.0"
marshmallow-enum = "==1.5.1"
bson = "==0.5.10"
google-auth = "==2.16.0"
google-auth-oauthlib = "==0.8.0"
googlemaps = "==4.10.0"
web3 = "==6.2.0"
nostr = "==0.0.2"
ddtrace = "==1.15.0"

[dev-packages]
mongomock = "==4.0.0"
pytest = "==6.2.5"
pytest-mock = "==3.7.0"
pytest-cov = "==3.0.0"
pre-commit = "==2.18.1"
flake8-docstrings = "==1.6.0"

[requires]
python_version = "3.9"
```
<details>
  <summary>`pip freeze`</summary>
aiohttp==3.8.4
aiosignal==1.3.1
APScheduler==3.10.1
async-timeout==4.0.2
attrs==23.1.0
base58==2.1.1
bitarray==2.7.5
blinker==1.6.2
boto3==1.17.98
botocore==1.20.112
bson==0.5.10
bytecode==0.14.2
cachetools==5.3.1
cattrs==23.1.2
certifi==2023.5.7
cffi==1.15.1
cfgv==3.3.1
chardet==4.0.0
charset-normalizer==3.1.0
click==8.1.3
commonmark==0.9.1
construct==2.10.68
coverage==6.4.4
cryptography==41.0.1
cytoolz==0.12.1
ddsketch==2.0.4
ddtrace==1.15.0
Deprecated==1.2.14
distlib==0.3.6
dnspython==2.1.0
email-validator==2.0.0.post2
envier==0.4.0
eth-abi==4.1.0
eth-account==0.9.0
eth-hash==0.5.2
eth-keyfile==0.6.1
eth-keys==0.4.0
eth-rlp==0.3.0
eth-typing==3.4.0
eth-utils==2.1.1
exceptiongroup==1.1.1
filelock==3.8.0
flake8==5.0.4
flake8-docstrings==1.6.0
Flask==2.1.0
Flask-Cors==3.0.10
Flask-JWT-Extended==4.2.1
Flask-Limiter==2.4.6
Flask-Mail==0.9.1
flask-mongoengine==1.0.0
Flask-WTF==1.1.1
frozenlist==1.3.3
google-auth==2.16.0
google-auth-oauthlib==0.8.0
googlemaps==4.10.0
gunicorn==20.1.0
hashistack==0.0.15
hexbytes==0.3.1
hvac==0.11.2
identify==2.5.5
idna==2.10
importlib-metadata==4.12.0
importlib-resources==5.12.0
iniconfig==1.1.1
isodatetimehandler==1.0.2
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==0.10.0
jsonpickle==3.0.1
jsonschema==4.17.3
limits==3.5.0
logdna==1.16.0
lru-dict==1.2.0
MarkupSafe==2.1.3
marshmallow==3.12.1
marshmallow-enum==1.5.1
mccabe==0.7.0
mixpanel==4.10.0
moesifapi==1.4.0
moesifpythonrequest==0.3.0
moesifwsgi==1.3.6
mongoengine==0.27.0
mongomock==4.0.0
multidict==6.0.4
munch==3.0.0
nodeenv==1.7.0
nostr==0.0.2
oauthlib==3.2.2
opentelemetry-api==1.16.0
packaging==23.1
parsimonious==0.9.0
phonenumbers==8.12.25
pika==1.3.2
pipenv==2022.9.21
platformdirs==2.5.2
pluggy==1.0.0
pre-commit==2.18.1
protobuf==4.23.3
py==1.11.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycodestyle==2.9.1
pycparser==2.21
pycryptodome==3.18.0
pydocstyle==6.1.1
pyflakes==2.5.0
Pygments==2.15.1
PyJWT==2.7.0
pymongo==4.3.3
PyNaCl==1.5.0
pyparsing==3.0.9
pyrsistent==0.19.3
pytest==6.2.5
pytest-cov==3.0.0
pytest-mock==3.7.0
python-consul2==0.1.5
python-dateutil==2.8.2
python-dotenv==0.18.0
pytz==2023.3
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
regex==2023.6.3
requests==2.25.1
requests-oauthlib==1.3.1
rich==12.6.0
rlp==3.0.0
rsa==4.9
s3transfer==0.4.2
secp256k1==0.14.0
sentinels==1.0.0
six==1.16.0
snowballstemmer==2.2.0
solana==0.9.2
tblib==1.7.0
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
twilio==6.50.1
typing_extensions==4.6.3
tzdata==2023.3
tzlocal==5.0.1
urllib3==1.26.7
virtualenv==20.16.5
virtualenv-clone==0.5.7
web3==6.2.0
websocket-client==1.6.0
websockets==11.0.3
Werkzeug==2.3.6
wrapt==1.15.0
WTForms==3.0.1
xmltodict==0.13.0
yarl==1.9.2
zipp==3.15.0
</details>

### How can we reproduce your problem?
I'd say start a Flask app and add this aftr setting the app.confgi
```python
config.env = environment
        config.service = "api-service"
        config.flask['service_name'] = "api-service"
        config.flask.http.trace_headers([
            'user-agent',
            'x-org-code'
        ])
        prof = Profiler(
            env=environment,  # if not specified, falls back to environment variable DD_ENV
            service="olyn-wallet-api-service",  # if not specified, falls back to environment variable DD_SERVICE
            version="1.0.0",  # if not specified, falls back to environment variable DD_VERSION
        )
        prof.start()  # Should be as early as possible, eg before other imports, to ensure everything is profiled
        tracer.configure(enabled=True, hostname="172.17.0.1", port=8126)
        patch_all()
```
### What is the result that you get?
I'm getting a connection refuse form the profiling
### What is the result that you expected?
I should not get a connection refuse from the profiling

**Comment by majorgreys** [comment]
@aleixisp, can you try moving the `tracer.configure(...)` call before the profiler instance is initialized?

But step backing, I don't think I understand why you are creating the profiler instance separately with a service name and version that is different than the one used for the flask application. Had you already tried using auto-instrumentation with `ddtrace-run` and environment variables for configuring?

**Comment by mabdinur** [comment]
Closing due to lack of activity.
