### ISSUE TITLE
ddtrace  error: builtins.SystemExit: 1

### ISSUE THREAD

**Issue by avanish-appdirect** [DataDog/dd-trace-py#6363]
### Summary of problem
I have recently started seeing ddtrace giving below error.
I'm running Django application using Gunicorn.
```
ddtrace-run gunicorn --bind 0.0.0.0:8000 --timeout 120 --limit-request-field_size 16000 --workers 4 test_project.wsgi:application

```
Error:
```
builtins.SystemExit: 1
Traceback (most recent call last):
  File "/home/python/.local/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 328, in traced_get_response
    response = func(*args, **kwargs)
  File "/home/python/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/home/python/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/python/.local/lib/python3.8/site-packages/ddtrace/contrib/trace_utils.py", line 162, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
  File "/home/python/.local/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 213, in wrapped
    return func(*args, **kwargs)
  File "/home/python/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/home/python/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/python/.local/lib/python3.8/site-packages/ddtrace/contrib/trace_utils.py", line 162, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
  File "/home/python/.local/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 213, in wrapped
    return func(*args, **kwargs)
  File "/home/python/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/home/python/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/python/.local/lib/python3.8/site-packages/ddtrace/contrib/trace_utils.py", line 162, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
  File "/home/python/.local/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 213, in wrapped
    return func(*args, **kwargs)
  File "/home/python/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/home/python/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/python/.local/lib/python3.8/site-packages/ddtrace/contrib/trace_utils.py", line 162, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
  File "/home/python/.local/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 213, in wrapped
    return func(*args, **kwargs)
  File "/home/python/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/home/python/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/python/.local/lib/python3.8/site-packages/ddtrace/contrib/trace_utils.py", line 162, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
SystemExit: 1
```

### Which version of dd-trace-py are you using?
ddtrace==0.58.1
Python==3.8
Django==3.2.18

### Which version of pip are you using?
pip==19.x.x

**Comment by P403n1x87** [comment]
@avanish-appdirect ddtrace 0.58.1 was released in February 2022. If this is a recent issue then the problem is likely not within ddtrace. Have you tried with a different version of ddtrace? 0.58.1 is not the latest of the 0.x series.

**Comment by mabdinur** [comment]
Closing due to lack of activity
