### ISSUE TITLE
Langchain Integration failing application

### ISSUE THREAD

**Issue by rodrigocaus** [DataDog/dd-trace-py#6464]
### Summary of problem
I am using langchain+fastapi to serve ChatGPT through an API. I am having trouble in production running application through `ddtrace-run uvicorn --port ...`. The ddtrace seems to prevent the request that calls OpenAI to complete successfully.

### Which version of dd-trace-py are you using?
ddtrace==1.17.1
### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>

  ```
  ddtrace==1.17.1
  fastapi==0.97.0
  openai==0.27.8
  langchain==0.0.205
  ```

</details>

### How can we reproduce your problem?
Expose an endpoint to langchain `agenerate`. In sumary:
```python
from fastapi import FastAPI
from pydantic import BaseModel
from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage, SystemMessage, LLMResult


app = FastAPI()
chat = ChatOpenAI(...)

class Prompt(BaseModel):
    system: str
    message: str

@app.post("/generate")
async def generate_text(request: Prompt) -> LLMResult:
    messages = [
            SystemMessage(
                content=request.system,
            ),
            HumanMessage(
                content=request.message,
            ),
        ]
    return await chat.agenerate(messages=[messages])
```

### What is the result that you get?
In the request, the application returns with 500 status code. The application logs are:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/run/lib/python3.10/site-packages/ddtrace/internal/utils/__init__.py", line 37, in get_argument_value
    return kwargs[kw]
KeyError: 'chat_messages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/run/lib/python3.10/site-packages/ddtrace/internal/utils/__init__.py", line 40, in get_argument_value
    return args[pos]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/run/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/run/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/run/lib/python3.10/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/run/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/run/lib/python3.10/site-packages/ddtrace/contrib/asgi/middleware.py", line 270, in __call__
    reraise(exc_type, exc_val, exc_tb)
  File "/usr/local/run/lib/python3.10/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/run/lib/python3.10/site-packages/ddtrace/contrib/asgi/middleware.py", line 265, in __call__
    return await self.app(scope, receive, wrapped_send)
  File "/usr/local/run/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/run/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/run/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/run/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/run/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/run/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/run/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/run/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/run/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/run/lib/python3.10/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/run/lib/python3.10/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
  File "/application/ai/main.py", line 73, in answer_text
    return await chat(input, prompt)
  File "/application/ai/llm/chatgpt.py", line 85, in __call__
    api_response: LLMResult = await self.llm.agenerate(messages=[messages])
  File "/usr/local/run/lib/python3.10/site-packages/ddtrace/contrib/langchain/patch.py", line 420, in traced_chat_model_agenerate
    chat_messages = get_argument_value(args, kwargs, 0, "chat_messages")
  File "/usr/local/run/lib/python3.10/site-packages/ddtrace/internal/utils/__init__.py", line 42, in get_argument_value
    raise ArgumentError("%s (at position %d)" % (kw, pos))
ddtrace.internal.utils.ArgumentError: chat_messages (at position 0)
```
It seems to have an attribute problem in [langchain integration patch](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/langchain/patch.py#L420).

### What is the result that you expected?
Even with the attribute error problem, it is expected to not impact the application. Running the server through `uvicorn --port ...` without the `ddtrace-run` solved this problem.

**Comment by Yun-Kim** [comment]
Hi @rodrigocaus, thanks for reaching out!

I was able to reproduce your issue, and we'll work on a fix ASAP. In the meantime, a possible workaround is to pass `messages` as a positional argument rather than a keyword argument, let me know if that works for you.

**Comment by rodrigocaus** [comment]
Thank you for your support @Yun-Kim 

Pass `messages` as positional argument worked for me.

**Comment by Harish-Tricon** [comment]
How it works with LangGraph? (e.g. invoke() method)
