### ISSUE TITLE
Flaky boto test_data_streams_sqs_batch

### ISSUE THREAD

**Issue by majorgreys** [DataDog/dd-trace-py#6498]
Failed runs: 
* [First](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/41636/workflows/e46190ff-ebe6-493a-b2c1-bbd4c4f13fd6/jobs/2786425/parallel-runs/0?filterBy=FAILED)
- [Retry](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/41636/workflows/951c5eb8-0694-41d6-be1a-b4aa47c333f7/jobs/2786798)

```
=================================== FAILURES ===================================
___________________ BotocoreTest.test_data_streams_sqs_batch ___________________

self = <tests.contrib.botocore.test.BotocoreTest testMethod=test_data_streams_sqs_batch>
result = <TestCaseFunction test_data_streams_sqs_batch>

    def _run_test_in_subprocess(self, result):
        # Copy the environment and include the special subprocess environment
        # variable for the subprocess to detect.
        env_overrides = self._get_env_overrides()
        use_pytest = self._get_use_pytest()
        full_testcase_name = self._full_method_name(use_pytest=use_pytest)
        sp_test_env = os.environ.copy()
        sp_test_env.update(env_overrides)
        sp_test_env[SUBPROC_ENV_VAR] = "True"
        test_framework = "pytest" if use_pytest else "unittest"
        sp_test_cmd = ["python", "-m", test_framework, full_testcase_name]
        sp = subprocess.Popen(
            sp_test_cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=sp_test_env,
        )
        stdout, stderr = sp.communicate()
    
        if sp.returncode:
            try:
                cmdf = " ".join(sp_test_cmd)
>               raise Exception('Subprocess Test "{}" Failed'.format(cmdf))
E               Exception: Subprocess Test "python -m unittest tests.contrib.botocore.test.BotocoreTest.test_data_streams_sqs_batch" Failed

tests/subprocesstest.py:127: Exception
----------------------------- Captured stderr call -----------------------------
/root/.pyenv/versions/3.9.16/lib/python3.9/socket.py:775: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55614), raddr=('127.0.0.1', 9126)>
  self._sock = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
skipping trace injection, max number (10) of MessageAttributes exceeded
F
======================================================================
FAIL: test_data_streams_sqs_batch (tests.contrib.botocore.test.BotocoreTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/.riot/venv_py3916_mock_pytest_pytest-mock_coverage_pytest-cov_opentracing_hypothesis6451_moto[all]_botocore/lib/python3.9/site-packages/moto/core/models.py", line 124, in wrapper
    result = func(*args, **kwargs)
  File "/root/project/tests/contrib/botocore/test.py", line 1243, in test_data_streams_sqs_batch
    assert len(buckets) == 1
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.218s

FAILED (failures=1)
=============================== warnings summary ===============================
```

https://app.circleci.com/insights/github/DataDog/dd-trace-py/workflows/test/tests?branch=1.x

**Comment by majorgreys** [comment]
@tabgok Can you investigate?
