### ISSUE TITLE
Circular Import with psycopg patch

### ISSUE THREAD

**Issue by mikeyk** [DataDog/dd-trace-py#6578]
### Summary of problem

We updated today to 1.17.3 (we were previously running 1.1.3). Upon updating, we started seeing the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/github/.local/lib/python3.10/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/home/github/.local/lib/python3.10/site-packages/psycopg/__init__.py", line 11, in <module>
    from . import postgres
  File "/home/github/.local/lib/python3.10/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/home/github/.local/lib/python3.10/site-packages/psycopg/postgres.py", line 9, in <module>
    from ._adapters_map import AdaptersMap
  File "/home/github/.local/lib/python3.10/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/home/github/.local/lib/python3.10/site-packages/psycopg/_adapters_map.py", line 14, in <module>
    from ._cmodule import _psycopg
  File "/home/github/.local/lib/python3.10/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/home/github/.local/lib/python3.10/site-packages/psycopg/_cmodule.py", line 19, in <module>
    from psycopg_binary import _psycopg as _psycopg  # type: ignore
  File "/home/github/.local/lib/python3.10/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "psycopg_binary/_psycopg/generators.pyx", line 14, in init psycopg_binary._psycopg
  File "/home/github/.local/lib/python3.10/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/home/github/.local/lib/python3.10/site-packages/psycopg/waiting.py", line 22, in <module>
    from ._cmodule import _psycopg
ImportError: cannot import name '_psycopg' from partially initialized module 'psycopg._cmodule' (most likely due to a circular import) (/home/github/.local/lib/python3.10/site-packages/psycopg/_cmodule.py)
```

This sounds somewhat similar to #5601, though that issue related to the Redis patch.

### Which version of dd-trace-py are you using?

1.17.3

### Which version of pip are you using?

22.3.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
```
psycopg==3.1.9
ddtrace==1.17.3
```
</details>

### How can we reproduce your problem?

Start up a simple Python app with the above imports.

### What is the result that you get?

Circular import error.

### What is the result that you expected?

A clean import.

Thanks in advance for taking a look!

**Comment by mabdinur** [comment]
Hi @mikeyk,

Thanks for opening this issue. What was the resolution?

**Comment by mikeyk** [comment]
> Hi @mikeyk,
> 
> Thanks for opening this issue. What was the resolution?

Thanks for checking in! We resolved it by:
1. Updating psycopg to 3.1.9 (we were on 3.1.3)
2. Removing our usage of psycopg2 entirely so we're just using psycopg

At that point the patch error (and the cmodule error we hit afterwards) went away. Thanks!

**Comment by ArzelaAscoIi** [comment]
Any updates on this ? Is there a way to make it work with psycopg2 ?

**Comment by bertramr** [comment]
Looking for a solution for running psycopg2 and psycopg3 in parallel. At the moment removing usage of psycopg2 is not a solution for us.
