### ISSUE TITLE
1.18.0 version throws ImportError: /opt/venv/lib/python3.10/site-packages/ddtrace/internal/datadog/profiling/ddup.cpython-310-aarch64-linux-gnu.so: undefined symbol: _ZN7Datadog7Profile15push_trace_typeESt17basic_string_viewIcSt11char_traitsIcEE

### ISSUE THREAD

**Issue by EliSzBr** [DataDog/dd-trace-py#6666]
### 1.18.0 throws import errors due to compiled code on arm
happens on M1 mac + `m7g.8xlarge` aws instance
```
ImportError: /opt/venv/lib/python3.10/site-packages/ddtrace/internal/datadog/profiling/ddup.cpython-310-aarch64-linux-gnu.so: undefined symbol: _ZN7Datadog7Profile15push_trace_typeESt17basic_string_viewIcSt11char_traitsIcEE
```

### Which version of dd-trace-py are you using?
1.18.0

### Which version of pip are you using?
23.0.1

### Which libraries and their versions are you using?
only ddtrace - reporoduces in container

### How can we reproduce your problem?
```
docker run --rm -it python:3.10-slim-buster bash
pip install ddtrace==1.18.0
python -c "from ddtrace.profiling import Profiler"
```
### What is the result that you get?
```
root@84794ab1499a:/# python -c "from ddtrace.profiling import Profiler"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/usr/local/lib/python3.10/site-packages/ddtrace/profiling/__init__.py", line 5, in <module>
    from .profiler import Profiler  # noqa:F401
  File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/usr/local/lib/python3.10/site-packages/ddtrace/profiling/profiler.py", line 19, in <module>
    from ddtrace.internal.datadog.profiling import ddup
  File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/module.py", line 197, in _create_module
    return self.loader.create_module(spec)
ImportError: /usr/local/lib/python3.10/site-packages/ddtrace/internal/datadog/profiling/ddup.cpython-310-aarch64-linux-gnu.so: undefined symbol: _ZN7Datadog7Profile15push_trace_typeESt17basic_string_viewIcSt11char_traitsIcEE
```
### What is the result that you expected?
should not throw error,
it does not for the 1.17.3 version

**Comment by P403n1x87** [comment]
@EliSzBr thanks for reporting this. We are already on top of this with #6529 and we hope to have a release with the fix out soon.

**Comment by sanchda** [comment]
Backporting to 1.18 in #6670.  I'll update this thread when we've cut a new release.

@EliSzBr, if this is time-critical for you, I can see about sharing a custom build--just respond here if that's the case.

**Comment by sanchda** [comment]
FYI, this has been backported to 1.18.1.  Updating should resolve.  Closing, but _please_ reopen if the behavior continues.
