### ISSUE TITLE
ddtrace doesn't support pymongo v4.5.0

### ISSUE THREAD

**Issue by CristianCeferinoLlanos** [DataDog/dd-trace-py#6723]
### Summary of problem
The `pymongo` instrumentation uses a method that was removed in the `pymongo` version `v4.5.0`, so the following error is raised when trying to bump `pymongo-v4.5.0`:
``` shell
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/main.py", line 28, in <module>
    patch_all()
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/_monkey.py", line 203, in patch_all
    patch(raise_errors=False, **modules)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/_monkey.py", line 231, in patch
    when_imported(module)(
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/importer.py", line 284, in register
    register_post_import_hook(hook, name)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/decorators.py", line 470, in _synchronized
    return wrapped(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/importer.py", line 82, in register_post_import_hook
    hook(module)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/_monkey.py", line 166, in on_import
    imported_module.patch()
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/contrib/pymongo/patch.py", line 33, in patch
    patch_pymongo_module()
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/contrib/pymongo/patch.py", line 53, in patch_pymongo_module
    _w("pymongo.server", "Server.get_socket", traced_get_socket)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 882, in wrap_function_wrapper
    return wrap_object(module, name, FunctionWrapper, (wrapper,))
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 822, in wrap_object
    (parent, attribute, original) = resolve_path(module, name)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 812, in resolve_path
    original = lookup_attribute(parent, attribute)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 804, in lookup_attribute
    return getattr(parent, attribute)
AttributeError: type object 'Server' has no attribute 'get_socket'
```

### Which version of dd-trace-py are you using?
`ddtrace==1.18.0`

### Which version of pip are you using?
`22.3.1`

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
Flask-2.3.2 Jinja2-3.1.2 MarkupSafe-2.1.3 PyMeta3-0.5.1 PyYAML-6.0.1 SQLAlchemy-2.0.20 Werkzeug-2.3.7 XlsxWriter-3.1.2 aiohttp-3.8.5 aiosignal-1.3.1 anyio-3.7.1 async-timeout-4.0.3 attrs-23.1.0 backoff-2.2.1 blinker-1.6.2 bytecode-0.14.2 catalogue-2.0.9 cattrs-23.1.2 chardet-5.2.0 click-8.1.7 clickhouse-connect-0.6.9 coloredlogs-15.0.1 dataclasses-json-0.5.14 dateparser-1.1.8 ddsketch-2.0.4 ddtrace-1.18.0 deprecated-1.2.14 dnspython-2.4.2 duckdb-0.8.1 envier-0.4.0 et-xmlfile-1.1.0 exceptiongroup-1.1.3 faker-19.3.0 fastapi-0.85.1 filetype-1.2.0 flask-cors-4.0.0 flask-pydantic-spec-0.4.5 flatbuffers-23.5.26 frozenlist-1.4.0 greenlet-2.0.2 gunicorn-21.2.0 h11-0.14.0 httptools-0.6.0 humanfriendly-10.0 importlib-metadata-6.8.0 inflection-0.5.1 itsdangerous-2.1.2 joblib-1.3.2 lxml-4.9.3 lz4-4.3.2 markdown-3.4.4 marshmallow-3.20.1 mongoengine-0.27.0 monotonic-1.6 mpmath-1.3.0 msg-parser-1.2.0 multidict-6.0.4 mypy-extensions-1.0.0 nltk-3.8.1 numexpr-2.8.5 olefile-0.46 onnxruntime-1.15.1 openai-0.27.8 openapi-schema-pydantic-1.2.4 openpyxl-3.1.2 opentelemetry-api-1.19.0 outcome-1.2.0 overrides-7.4.0 pandas-2.0.3 pdf2image-1.16.3 pdfminer.six-20221105 phonenumbers-8.13.19 pillow-10.0.0 posthog-3.0.2 protobuf-4.24.1 pulsar-client-3.2.0 pybars3-0.9.7 pydantic-1.10.12 pymongo-4.5.0 pypandoc-1.11 python-dateutil-2.8.2 python-docx-0.8.11 python-dotenv-1.0.0 python-magic-0.4.27 python-pptx-0.6.21 python-stdnum-1.19 pytz-2023.3 regex-2023.8.8 requests-2.31.0 scrubadub-2.0.0 selenium-4.10.0 sklearn-0.0.post7 sniffio-1.3.0 sortedcontainers-2.4.0 starlette-0.20.4 sympy-1.12 tabulate-0.9.0 tenacity-8.2.3 textblob-0.15.3 tiktoken-0.4.0 tokenizers-0.13.3 tqdm-4.66.1 trio-0.22.2 trio-websocket-0.10.3 typing-extensions-4.7.1 typing-inspect-0.9.0 tzdata-2023.3 tzlocal-5.0.1 unstructured-0.8.7 uvicorn-0.23.2 uvloop-0.17.0 watchfiles-0.19.0 websockets-11.0.3 wrapt-1.15.0 wsproto-1.2.0 xlrd-2.0.1 xmltodict-0.13.0 yarl-1.9.2 zipp-3.16.2 zstandard-0.21.0
</details>

### How can we reproduce your problem?
Bump `pymongo` to `v4.5.0` and run the `ddtrce` instrumentation.

### What is the result that you get?
``` shell
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/conda/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/main.py", line 28, in <module>
    patch_all()
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/_monkey.py", line 203, in patch_all
    patch(raise_errors=False, **modules)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/_monkey.py", line 231, in patch
    when_imported(module)(
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/importer.py", line 284, in register
    register_post_import_hook(hook, name)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/decorators.py", line 470, in _synchronized
    return wrapped(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/importer.py", line 82, in register_post_import_hook
    hook(module)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/_monkey.py", line 166, in on_import
    imported_module.patch()
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/contrib/pymongo/patch.py", line 33, in patch
    patch_pymongo_module()
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/contrib/pymongo/patch.py", line 53, in patch_pymongo_module
    _w("pymongo.server", "Server.get_socket", traced_get_socket)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 882, in wrap_function_wrapper
    return wrap_object(module, name, FunctionWrapper, (wrapper,))
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 822, in wrap_object
    (parent, attribute, original) = resolve_path(module, name)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 812, in resolve_path
    original = lookup_attribute(parent, attribute)
  File "/opt/conda/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 804, in lookup_attribute
    return getattr(parent, attribute)
AttributeError: type object 'Server' has no attribute 'get_socket'
```

### What is the result that you expected?
No error

**Comment by elch-yan** [comment]
I've started experiencing same issue after 1.18.1 release.

**Comment by emmettbutler** [comment]
Thanks for bringing this to our attention, @CristianCeferinoLlanos. Looks like it could be a pretty straightforward fix.

**Comment by tabgok** [comment]
Merged a fix for the issue, let us know how it works!
