### ISSUE TITLE
DD trace floods with logs and errors

### ISSUE THREAD

**Issue by snbby** [DataDog/dd-trace-py#7061]
I tried to remove datadog python tracing on my Ubuntu server with `pip uninstall ddtrace`, but it seems smth went wrong

When I try commands like `pip freeze` or even `supervisorctl status`

I receive that logs constantly:
```
INFO:datadog.autoinstrumentation(pid: 2467695): user-installed ddtrace not found, configuring application to use injection site-packages
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ModuleNotFoundError: No module named 'ddtrace.bootstrap'
```

On `pip freeze` I also receive such error:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/commands/freeze.py", line 98, in run
    for line in freeze(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/operations/freeze.py", line 43, in freeze
    req = FrozenRequirement.from_dist(dist)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/operations/freeze.py", line 236, in from_dist
    editable = dist.editable
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/metadata/base.py", line 338, in editable
    return bool(self.editable_project_location)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/metadata/base.py", line 183, in editable_project_location
    egg_link_path = egg_link_path_from_sys_path(self.raw_name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/metadata/base.py", line 429, in raw_name
    return self.metadata.get("Name", self.canonical_name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/metadata/base.py", line 406, in metadata
    return self._metadata_cached()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/metadata/base.py", line 393, in _metadata_cached
    metadata = self._metadata_impl()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 201, in _metadata_impl
    metadata = self.read_text(metadata_name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 180, in read_text
    content = self._dist.get_metadata(name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1519, in get_metadata
    value = self._get(path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1727, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/opt/datadog/apm/library/python/ddtrace_pkgs/site-packages-ddtrace-py3.10-manylinux2014/protobuf-4.24.0.dist-info/METADATA'
```

How can I remove datadog python tracing completely?

**Comment by snbby** [comment]
Thanks man, you saved my nerves

Good to mention, you don't need really to `Restart host` (because this might be painful) as mentioned [here](https://docs.datadoghq.com/tracing/trace_collection/single-step-apm/?tab=linuxhostorvm#removing-apm-for-all-services-on-the-infrastructure), just to relogin to host (I struggled with this for some time)

**Comment by GoranPopovic1** [comment]
@Kyle-Verhoog hi :) I'm experiencing the same issue at this point. Is there a way to resolve the issue without removing the APM single step? I see that the mentioned PR that should resolve the issue has been merged. How could I apply those latest changes? Thanks.

**Comment by Kyle-Verhoog** [comment]
Hi @GoranPopovic1, ah it looks like the backport failed on that PR. I will backport it manually and get it out in `1.20.3`!
