### ISSUE TITLE
Enabling profiling breaks google-datastore python client

### ISSUE THREAD

**Issue by michaelCTS** [DataDog/dd-trace-py#7101]
### Summary of problem

Our `connexion` + `flask` application throws an exception after `DD_PROFILING_ENABLE=true` in our smoke tests. The application runs on Google Cloud Run and the breaking env variable is that one.
After disabling it, things worked fine again. With google cloud profiler things work without a hitch.

The error is very consistent and presents itself on the same endpoint and has the same stacktrace every time.

### Which version of dd-trace-py are you using?

Not sure. Followed [the guide](https://docs.datadoghq.com/serverless/google_cloud_run/) and using [serverless-init:1](https://hub.docker.com/layers/datadog/serverless-init/1/images/sha256-4fbe6e9fb6b2121c033e6c060b03b161481390d7da768cd25a7e509026c4b66c?context=explore) with the latest `ddtrace` from pypi (currently 1.20.2)

### Which version of pip are you using?

23.1.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>

```
api-common==0.0.2
attrs==23.1.0
backoff==2.2.1
beautifulsoup4==4.9.3
build==0.10.0
CacheControl==0.12.14
cachetools==4.2.4
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
cleo==2.0.1
click==8.1.7
clickclick==20.10.2
connexion==2.14.2
crashtest==0.4.1
cryptography==41.0.2
distlib==0.3.6
dulwich==0.21.5
event-client==0.0.8
filelock==3.12.2
Flask==2.2.5
Flask-SQLAlchemy==3.0.5
google-api-core==1.34.0
google-api-python-client==2.97.0
google-auth==1.35.0
google-auth-httplib2==0.1.0
google-cloud-core==2.3.3
google-cloud-datastore==2.17.0
google-cloud-profiler==4.1.0
google-cloud-pubsub==2.18.3
google-cloud-secret-manager==2.16.3
google-cloud-storage==2.10.0
google-crc32c==1.5.0
google-resumable-media==2.5.0
googleapis-common-protos==1.60.0
greenlet==2.0.2
grpc-google-iam-v1==0.12.6
grpcio==1.57.0
grpcio-status==1.48.2
gunicorn==20.0.4
html5lib==1.1
httplib2==0.22.0
idna==3.4
importlib-metadata==6.8.0
inflection==0.5.1
installer==0.7.0
itsdangerous==2.1.2
jaraco.classes==3.3.0
jeepney==0.8.0
Jinja2==3.1.2
json-logging==1.2.11
jsonschema==4.17.3
jsonschema-specifications==2023.6.1
keyring==23.13.1
keyrings.google-artifactregistry-auth==1.1.2
lockfile==0.12.2
lxml==4.6.3
MarkupSafe==2.1.3
more-itertools==9.1.0
msgpack==1.0.5
packaging==23.1
pexpect==4.8.0
pkginfo==1.9.6
platformdirs==3.8.1
pluggy==1.2.0
poetry==1.5.1
poetry-core==1.6.1
poetry-plugin-export==1.4.0
proto-plus==1.22.3
protobuf==3.20.3
ptyprocess==0.7.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
PyMuPDF==1.18.10
pyodbc==4.0.39
pyparsing==3.1.1
pyproject_hooks==1.0.0
pyrsistent==0.19.3
python-dateutil==2.8.1
PyYAML==6.0.1
rapidfuzz==2.15.1
referencing==0.29.1
requests==2.31.0
requests-toolbelt==1.0.0
rpds-py==0.8.10
rsa==4.9
SecretStorage==3.3.3
shellingham==1.5.0.post1
six==1.16.0
soupsieve==2.4.1
SQLAlchemy==2.0.20
swagger-ui-bundle==0.0.8
tomli==2.0.1
tomlkit==0.11.8
trove-classifiers==2023.7.6
typing_extensions==4.7.1
uritemplate==4.1.1
urllib3==2.0.4
virtualenv==20.23.1
webencodings==0.5.1
Werkzeug==2.2.3
zipp==3.16.2
```

</details>

### How can we reproduce your problem?

I'm honestly not sure, as the problem presents itself only when deployed on Google Cloud Run. This very simple script works locally, but possibly expanded with `connexion` and `flask`, it won't. I didn't get around to testing it more deeply. No time to create a new cloud run, service account, api key, etc.

```py
# Imports the Google Cloud client library
from google.cloud import datastore

# Instantiates a client
project = "google-project-name"
datastore_client = datastore.Client(project)
article = datastore_client.get(datastore_client.key("Articles", 10))

print(f"article: {article}")
```

DD env vars:

```
DD_SITE	datadoghq.eu	
DD_PROFILING_ENABLED	true	
DD_LOGS_ENABLED	true	
DD_LOGS_INJECTION	true	
DD_ENV	dev	
DD_API_KEY	A_valid_key
```

### What is the result that you get?

<details>
<summary>Stacktrace</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/dd_tracer/python/ddtrace/contrib/flask/wrappers.py", line 88, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/dd_tracer/python/ddtrace/contrib/flask/wrappers.py", line 75, in wrapper
    return _wrap_call(wrapped, pin, name, span_type=span_type, args=args, kwargs=kwargs)
  File "/dd_tracer/python/ddtrace/contrib/flask/wrappers.py", line 52, in _wrap_call
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/dd_tracer/python/ddtrace/contrib/flask/wrappers.py", line 88, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/dd_tracer/python/ddtrace/contrib/flask/patch.py", line 511, in _patched_request
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/dd_tracer/python/ddtrace/contrib/flask/wrappers.py", line 61, in patch_func
    return _wrap_call(
  File "/dd_tracer/python/ddtrace/contrib/flask/wrappers.py", line 52, in _wrap_call
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/validation.py", line 399, in wrapper
    return function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
    return function(**kwargs)
  File "/app/openapi_server/controllers/articles_controller.py", line 220, in metadata
    article_metadata = article_service.get_metadata(metadata_request)
  File "/app/openapi_server/services/article_service.py", line 301, in get_metadata
    article = metadata.get_article(article_id)
  File "/app/openapi_server/data_access/metadata.py", line 88, in get_article
    article = client.get(client.key(constants.ARTICLES, article_id))
  File "/usr/local/lib/python3.9/site-packages/google/cloud/datastore/client.py", line 485, in get
    entities = self.get_multi(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/datastore/client.py", line 569, in get_multi
    key_pbs=[key.to_protobuf() for key in keys],
  File "/usr/local/lib/python3.9/site-packages/google/cloud/datastore/client.py", line 569, in <listcomp>
    key_pbs=[key.to_protobuf() for key in keys],
  File "/usr/local/lib/python3.9/site-packages/google/cloud/datastore/key.py", line 324, in to_protobuf
    key.path.append(element)
TypeError: Parameter to MergeFrom() must be instance of same class: expected google.datastore.v1.Key.PathElement got PathElement.
```

</details>

### What is the result that you expected?

A functional application that can access datastore.

**Comment by P403n1x87** [comment]
Thanks for reporting this @michaelCTS. Based on the stacktrace provided, my initial thought is on the protobuf dependency, since this is also used by the profiler to export pprofs. Could you please confirm whether the same version of protobuf is installed locally? Would you be able to use a later version of the protobuf dependency on the cloud deployment to see if that helps?

**Comment by michaelCTS** [comment]
Hi @P403n1x87, I'm using the same docker image locally as in prod and mounting my `test.py` into the docker container. The dependencies are thus equal. I also tried updating the dependencies and deploying those, unfortunately to no avail.

**Comment by itallix** [comment]
We were able to get our service working after upgrading one of our google clients to the latest version, the earlier version was dependent on protobuf 3.x 👍

**Comment by P403n1x87** [comment]
@michaelCTS @itallix thanks for the extra insight into this. We just merged https://github.com/DataDog/dd-trace-py/pull/7124, but since we don't have a reproducer from our end we're not quite sure it will fix the OP issue with protobuf < 4. It will require switching to the new export mechanism via the libdatadog shared library though, to bypass the Python path that depends on protobuf. This is achieved by setting [DD_PROFILING_EXPORT_LIBDD_ENABLED](https://ddtrace.readthedocs.io/en/stable/configuration.html#DD_PROFILING_EXPORT_LIBDD_ENABLED) to `1` and [DD_PROFILING_EXPORT_PY_ENABLED](https://ddtrace.readthedocs.io/en/stable/configuration.html#DD_PROFILING_EXPORT_PY_ENABLED) to `0`. In the future, the new libdatadog-based export mechanism will be the default.

**Comment by michaelCTS** [comment]
Thanks for the solution @P403n1x87!
