### ISSUE TITLE
v2.1 issues with Lambda and Django

### ISSUE THREAD

**Issue by jensenbox** [DataDog/dd-trace-py#7344]
### Summary of problem
We use Django in a Lambda handler. The lambda handler is pretty rudimentary in that it simply initializes Django and calls out to a function. Version 2.0.3 works perfectly in this context however v2.1 is causing issues.

### Which version of dd-trace-py are you using?
v2.1.2

### Which version of pip are you using?
We use Poetry

### Which libraries and their versions are you using?
Django 4.2.6

### How can we reproduce your problem?
Create a lambda handler like the following:

```python
# Standard Library
import importlib
import logging
import os

# Third Party
import django


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


def lambda_handler(event, context):
    logger.debug("Lambda handler called")

    logger.info("Incoming event: %s", event)
    logger.info("Incoming context: %s", context)

    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "projectname.settings")

    logger.debug("Setting up Django")
    django.setup()

    logger.debug("Django setup complete")

    whole_function = os.environ["LAMBDA_FUNCTION"]

    logger.debug("Function to call: %s", whole_function)

    module_name, function_name = whole_function.rsplit(".", 1)

    logger.debug("Module: %s", module_name)
    logger.debug("Function: %s", function_name)

    module = importlib.import_module(module_name)
    function = getattr(module, function_name)

    logger.debug("Function imported, calling it")
    function(event, context)

```

### What is the result that you get?
```

[ERROR] RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/aws_lambda.py", line 168, in sentry_handler
    reraise(*exc_info)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 115, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/aws_lambda.py", line 159, in sentry_handler
    return handler(aws_event, aws_context, *args, **kwargs)
  File "/app/noviconnect/lambda.py", line 23, in lambda_handler
    django.setup()
  File "/usr/local/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")


```
### What is the result that you expected?
No error

**Comment by mabdinur** [comment]
Hi @jensenbox, 

Looking at the stacktrace it seems like this error is raised by the sentry-sdk. It's not clear where ddtrace fits into the picture. Can you reproduce this error when sentry is not installed?

Also the django apps registry is likely catching the original error and then raising a runtime error that isn't very useful. You can you follow these [steps](https://stackoverflow.com/a/55929118) to get the original error. This should good give us more insight into what is being misconfigured.

@

**Comment by mabdinur** [comment]
Closing due to inactivity. Feel free to reopen this issue.
