### ISSUE TITLE
AgentWriter thread gets killed due to concurrent dictionary modification

### ISSUE THREAD

**Issue by krosen040** [DataDog/dd-trace-py#7411]
### Summary of problem
The `AgentWriter` thread that's responsible for flushing traces to the agent gets killed due to something modifying a dictionary while iterating over it [here](https://github.com/DataDog/dd-trace-py/blob/v1.18.6/ddtrace/internal/writer/writer.py#L456). Stack trace:

```python
Exception in thread ddtrace.internal.writer.writer:AgentWriter:
Traceback (most recent call last):
  File "/python-install/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/mnt/kubernetes/sandbox/responsiveness-model-evaluator/lib/python3.10/site-packages/ddtrace/internal/periodic.py", line 56, in run
    self._target()
  File "/mnt/kubernetes/sandbox/responsiveness-model-evaluator/lib/python3.10/site-packages/ddtrace/internal/writer/writer.py", line 461, in periodic
    self.flush_queue(raise_exc=False)
  File "/mnt/kubernetes/sandbox/responsiveness-model-evaluator/lib/python3.10/site-packages/ddtrace/internal/writer/writer.py", line 415, in flush_queue
    self._flush_queue_with_client(client, raise_exc=raise_exc)
  File "/mnt/kubernetes/sandbox/responsiveness-model-evaluator/lib/python3.10/site-packages/ddtrace/internal/writer/writer.py", line 456, in _flush_queue_with_client
    for name, metric_tags in self._metrics.items():
RuntimeError: dictionary changed size during iteration
```

This causes traces to stop being sent to the agent, and the following warning message is logged over and over:

```python
2023-10-25 09:06:52,043 WARNING ddtrace.internal.writer.writer: trace buffer (53414 traces 8388538b/8388608b) cannot fit trace of size 157b, dropping (writer status: running) [in /mnt/kubernetes/sandbox/responsiveness-model-evaluator/lib/python3.10/site-packages/ddtrace/internal/writer/writer.py:396, 139702107621120 (ThreadPoolExecutor-3_2), 586 (MainProcess)]
```

### Which version of dd-trace-py are you using?
1.18.6, but looking at the code the problem still seems to be there in the latest 2.x version.

### How can we reproduce your problem?
I'm not sure how to reproduce it, but this keeps happening for several of our Python applications. The only way to fix it is to restart the application.

**Comment by mabdinur** [comment]
Hi @krosen040, 

Thanks for calling out this issue. This error is raised when the tracer attempts to collect health metrics. You can avoid this bug by setting `DD_TRACE_HEALTH_METRICS_ENABLED=False`. 

Note - Health metrics are opt in. So you should not experience this error if the `DD_TRACE_HEALTH_METRICS_ENABLED` environment variable is not set in your application. 

This PR should resolve this issue: https://github.com/DataDog/dd-trace-py/pull/7413
