### ISSUE TITLE
openai 1.1.1 is not supported

### ISSUE THREAD

**Issue by iherasymenko** [DataDog/dd-trace-py#7494]
### Summary of problem

`ddtrace` is not compatible with `openai` version `1.1.1`

### Which version of dd-trace-py are you using?

`2.1.5`

### How can we reproduce your problem?

1. Create a new file `main.py`:
```
from openai import OpenAI

client = OpenAI(api_key="something")
```

2. Run it with `ddtrace-run`
```
ddtrace-run python main.py
```

### What is the result that you get?

```
Traceback (most recent call last):
  File "/***/openai-playground/main.py", line 1, in <module>
    from openai import OpenAI
  File "/***/openai-playground/venv/lib/python3.11/site-packages/ddtrace/vendor/wrapt/importer.py", line 177, in _exec_module
    notify_module_loaded(module)
  File "/***/openai-playground/venv/lib/python3.11/site-packages/ddtrace/vendor/wrapt/decorators.py", line 470, in _synchronized
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/***/openai-playground/venv/lib/python3.11/site-packages/ddtrace/vendor/wrapt/importer.py", line 136, in notify_module_loaded
    hook(module)
  File "/***/openai-playground/venv/lib/python3.11/site-packages/ddtrace/_monkey.py", line 167, in on_import
    imported_module.patch()
  File "/***/openai-playground/venv/lib/python3.11/site-packages/ddtrace/contrib/openai/patch.py", line 157, in patch
    import openai.api_requestor
ModuleNotFoundError: No module named 'openai.api_requestor'
```

### What is the result that you expected?

`ddtrace` can instrument `openai` versions >= `1.1.1`

**Comment by Yun-Kim** [comment]
Hi @iherasymenko, thanks for reaching out!

We're currently working on adding support for OpenAI v1. Unfortunately it is a complete rewrite of their library ([in their own words](https://github.com/openai/openai-python/discussions/631)), so it isn't a trivial bugfix. In the meantime, I would recommend downgrading to `openai<1.0` if you would like to continue using ddtrace with openai.

**Comment by dudongtai2002** [comment]
notice similar issue for my application as well.

**Comment by sqlboy** [comment]
How do just disable this in ddtrace?

**Comment by Yun-Kim** [comment]
Hi @sqlboy, ddtrace supports openai >1.0 since ddtrace 2.2 and newer, so you should be able to run your application without any issues. 

If you need to disable this in ddtrace for other reasons, you can add `DD_TRACE_OPENAI_ENABLED=false` on your app startup command.
