### ISSUE TITLE
Openai upgrade

### ISSUE THREAD

**Issue by ryanpeach** [DataDog/dd-trace-py#7617]
### Summary of problem

Openai recently made an upgrade that is breaking all sorts of repos, apparently you are effected too.

https://github.com/langchain-ai/langchain/issues/13368

https://github.com/langchain-ai/langchain/issues/12967

### Which version of dd-trace-py are you using?

2.1.1

### Which version of pip are you using?

pip 23.0.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
    aiohttp==3.8.5
    aiosignal==1.3.1
    aiostream==0.5.2
    alabaster==0.7.13
    annotated-types==0.5.0
    ans.protocol.amk==0.1.0b8
    ansys-materials-manager==0.2.3
    ansys-simbuilder-core @ git+ssh://git@github.com/OnScale/Simulation_API.git@08c460bcc57cc71b95c7d67f38e6fe6c4dc967fc#subdirectory=packages/sim_builder
    anyio==3.7.1
    appnope==0.1.3
    argon2-cffi==23.1.0
    argon2-cffi-bindings==21.2.0
    arrow==1.2.3
    astroid==2.13.5
    asttokens==2.4.0
    async-lru==2.0.4
    async-timeout==4.0.3
    attrs==23.1.0
    Babel==2.12.1
    backcall==0.2.0
    beautifulsoup4==4.12.2
    black==23.3.0
    bleach==6.0.0
    boto3==1.28.50
    botocore==1.31.50
    bytecode==0.15.1
    cachetools==5.3.1
    cattrs==23.1.2
    certifi==2023.7.22
    cffi==1.15.1
    cfgv==3.4.0
    charset-normalizer==3.2.0
    click==8.1.7
    colorama==0.4.6
    comm==0.1.4
    coverage==7.3.2
    cryptography==41.0.3
    dataclasses-json==0.5.14
    ddsketch==2.0.4
    ddtrace==2.1.1
    debugpy==1.8.0
    decorator==5.1.1
    defusedxml==0.7.1
    Deprecated==1.2.14
    dill==0.3.7
    discord.py==2.3.2
    distlib==0.3.7
    distro==1.8.0
    dnspython==2.4.2
    docker==6.1.3
    docutils==0.18.1
    email-validator==2.0.0.post2
    envier==0.4.0
    exceptiongroup==1.1.3
    executing==1.2.0
    fastapi==0.98.0
    fastjsonschema==2.18.0
    filelock==3.12.4
    flaky==3.7.0
    flatbuffers==23.5.26
    fqdn==1.5.1
    frozenlist==1.4.0
    fsspec==2023.9.0
    google-api-core==2.11.1
    google-api-python-client==2.100.0
    google-auth==2.23.0
    google-auth-httplib2==0.1.1
    google-auth-oauthlib==1.1.0
    googleapis-common-protos==1.60.0
    greenlet==3.0.0
    grpcio==1.59.0
    h11==0.14.0
    html2text==2020.1.16
    httpcore==0.16.3
    httplib2==0.22.0
    httptools==0.6.1
    httpx==0.23.3
    identify==2.5.28
    idna==3.4
    imagesize==1.4.1
    importlib-metadata==6.8.0
    iniconfig==2.0.0
    ipykernel==6.23.1
    ipython==8.10.0
    ipython-genutils==0.2.0
    isoduration==20.11.0
    isort==5.12.0
    itsdangerous==2.1.2
    jedi==0.19.0
    Jinja2==3.1.2
    jmespath==1.0.1
    joblib==1.3.2
    json5==0.9.14
    jsonpatch==1.33
    jsonpath-ng==1.6.0
    jsonpointer==2.4
    jsonschema==4.19.0
    jsonschema-specifications==2023.7.1
    jupyter-events==0.7.0
    jupyter-lsp==2.2.0
    jupyter_client==8.3.1
    jupyter_core==5.3.1
    jupyter_server==2.7.3
    jupyter_server_terminals==0.4.4
    jupyterlab==4.0.5
    jupyterlab-pygments==0.2.2
    jupyterlab_server==2.25.0
    langchain==0.0.335
    langsmith==0.0.64
    lazy-object-proxy==1.9.0
    loguru==0.7.0
    markdown-it-py==3.0.0
    MarkupSafe==2.1.3
    marshmallow==3.20.1
    matplotlib-inline==0.1.6
    mccabe==0.7.0
    mdit-py-plugins==0.4.0
    mdurl==0.1.2
    mistune==3.0.1
    moto==4.2.3
    motor==3.2.0
    multidict==6.0.4
    mypy==1.3.0
    mypy-extensions==1.0.0
    myst-parser==2.0.0
    nbclassic==1.0.0
    nbclient==0.8.0
    nbconvert==7.8.0
    nbformat==5.9.2
    nest-asyncio==1.5.8
    nltk==3.8.1
    nodeenv==1.8.0
    notebook==6.5.4
    notebook_shim==0.2.3
    numexpr==2.8.6
    numpy==1.25.2
    oauthlib==3.2.2
    openai==1.2.4
    openapi-schema-pydantic==1.2.4
    opentelemetry-api==1.20.0
    orjson==3.9.9
    overrides==7.4.0
    packaging==23.1
    pandas==2.0.3
    pandocfilters==1.5.0
    parso==0.8.3
    pathspec==0.11.2
    pexpect==4.8.0
    pickleshare==0.7.5
    platformdirs==3.10.0
    pluggy==1.3.0
    ply==3.11
    pre-commit==3.2.0
    prometheus-client==0.17.1
    prompt-toolkit==3.0.39
    protobuf==4.24.3
    psutil==5.9.5
    ptyprocess==0.7.0
    pure-eval==0.2.2
    py-cpuinfo==9.0.0
    py-partiql-parser==0.3.7
    pyasn1==0.5.0
    pyasn1-modules==0.3.0
    pycparser==2.21
    pydantic==1.10.12
    pydantic_core==2.6.3
    Pygments==2.16.1
    pylint==2.15.10
    pymongo==4.5.0
    pyparsing==3.1.1
    pytest==7.3.1
    pytest-asyncio==0.21.1
    pytest-benchmark==4.0.0
    pytest-cov==4.1.0
    pytest-dotenv==0.5.2
    python-dateutil==2.8.2
    python-dotenv==1.0.0
    python-json-logger==2.0.7
    python-multipart==0.0.6
    pytz==2023.3.post1
    PyYAML==6.0.1
    pyzmq==25.1.1
    rake-nltk==1.0.6
    referencing==0.30.2
    regex==2023.8.8
    requests==2.31.0
    requests-oauthlib==1.3.1
    responses==0.23.3
    rfc3339-validator==0.1.4
    rfc3986==1.5.0
    rfc3986-validator==0.1.1
    rich==13.6.0
    rpds-py==0.10.3
    rsa==4.9
    ruff==0.1.1
    rustworkx==0.12.0
    s3transfer==0.6.2
    scikit-learn==1.3.0
    scipy==1.11.3
    semver==3.0.2
    Send2Trash==1.8.2
    shellingham==1.5.3
    six==1.16.0
    slack-sdk==3.22.0
    sniffio==1.3.0
    snowballstemmer==2.2.0
    soupsieve==2.5
    Sphinx==7.2.6
    sphinx-rtd-theme==1.3.0
    sphinxcontrib-applehelp==1.0.7
    sphinxcontrib-devhelp==1.0.5
    sphinxcontrib-htmlhelp==2.0.4
    sphinxcontrib-jquery==4.1
    sphinxcontrib-jsmath==1.0.1
    sphinxcontrib-mermaid==0.9.2
    sphinxcontrib-qthelp==1.0.6
    sphinxcontrib-serializinghtml==1.1.9
    SQLAlchemy==2.0.20
    stack-data==0.6.2
    starlette==0.27.0
    tabulate==0.9.0
    tenacity==8.2.3
    terminado==0.17.1
    threadpoolctl==3.2.0
    tiktoken==0.5.1
    tinycss2==1.2.1
    tokenize-rt==5.2.0
    tomli==2.0.1
    tomlkit==0.12.1
    tornado==6.3.3
    tqdm==4.66.1
    traitlets==5.9.0
    tree-sitter==0.20.2
    tree-sitter-languages==1.7.0
    typer==0.9.0
    types-docutils==0.20.0.3
    types-pyOpenSSL==23.2.0.2
    types-python-dateutil==2.8.19.14
    types-PyYAML==6.0.12.11
    types-redis==4.5.5.0
    types-requests==2.31.0.1
    types-setuptools==67.1.0.0
    types-urllib3==1.26.25.14
    typing-inspect==0.9.0
    typing_extensions==4.7.1
    tzdata==2023.3
    ujson==5.8.0
    uri-template==1.3.0
    uritemplate==4.1.1
    urllib3==1.26.16
    uvicorn==0.22.0
    uvloop==0.18.0
    vellum-ai==0.0.15
    virtualenv==20.24.5
    watchfiles==0.21.0
    wcwidth==0.2.6
    webcolors==1.13
    webencodings==0.5.1
    websocket-client==1.6.3
    websockets==11.0.3
    Werkzeug==2.3.7
    wikipedia==1.4.0
    wrapt==1.15.0
    xmltodict==0.13.0
    yarl==1.9.2
    zipp==3.17.0
</details>

### How can we reproduce your problem?

```python
from langchain.embeddings import OpenAIEmbeddings, AzureOpenAIEmbeddings
from llama_index import LangchainEmbedding
import os
from ddtrace import config, patch_all

config.langchain["logs_enabled"] = True
patch_all()
```

### What is the result that you get?

```
Traceback (most recent call last):
  File "/Users/ryan.peach/Documents/OnScale/chat-simapi/experiments/langchain_version.py", line 7, in <module>
    patch_all()
  File "/Users/ryan.peach/.pyenv/versions/llama_index/lib/python3.10/site-packages/ddtrace/_monkey.py", line 211, in patch_all
    patch(raise_errors=False, **modules)
  File "/Users/ryan.peach/.pyenv/versions/llama_index/lib/python3.10/site-packages/ddtrace/_monkey.py", line 239, in patch
    when_imported(module)(
  File "/Users/ryan.peach/.pyenv/versions/llama_index/lib/python3.10/site-packages/wrapt/importer.py", line 291, in register
    register_post_import_hook(hook, name)
  File "/Users/ryan.peach/.pyenv/versions/llama_index/lib/python3.10/site-packages/wrapt/importer.py", line 77, in register_post_import_hook
    hook(module)
  File "/Users/ryan.peach/.pyenv/versions/llama_index/lib/python3.10/site-packages/ddtrace/_monkey.py", line 167, in on_import
    imported_module.patch()
  File "/Users/ryan.peach/.pyenv/versions/llama_index/lib/python3.10/site-packages/ddtrace/contrib/openai/patch.py", line 157, in patch
    import openai.api_requestor
ModuleNotFoundError: No module named 'openai.api_requestor'
```

### What is the result that you expected?

We probably need to find the new module name.

**Comment by mabdinur** [comment]
Hi @ryanpeach, 

ddtrace v2.2.0 adds support for `openai>=1.0`. This version was released earlier today. Can you try upgrading to this release?

**Comment by Yun-Kim** [comment]
Hi @ryanpeach, thanks for reaching out!

https://github.com/DataDog/dd-trace-py/pull/7513 was just merged which adds support for openai>=1.0. This was released in ddtrace 2.2.0, please try upgrading and let us know if there are still any issues.

Closing as this is a duplicate of https://github.com/DataDog/dd-trace-py/issues/7494 and resolved.
