### ISSUE TITLE
OpenAI python client raw response support

### ISSUE THREAD

**Issue by Tradunsky** [DataDog/dd-trace-py#7645]
### Summary of problem
OpenAI client used to return time it took to process request on their side without the time for the round-trip. 

The new python client has no this field present in the response class, however it is possible to get it from the raw response, by setting the extra header:
```
    from openai._constants import RAW_RESPONSE_HEADER
    extra_headers={RAW_RESPONSE_HEADER: "true"},
```

### Which version of dd-trace-py are you using?
2.2.0
### Which version of pip are you using?
pip 23.2.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
annotated-types==0.6.0
anyio==3.7.1
attrs==23.1.0
bytecode==0.15.1
cattrs==23.1.2
certifi==2023.7.22
ddsketch==2.0.4
ddtrace==2.2.0
Deprecated==1.2.14
distro==1.8.0
envier==0.4.0
h11==0.14.0
httpcore==1.0.2
httpx==0.25.1
idna==3.4
importlib-metadata==6.8.0
openai==1.3.2
opentelemetry-api==1.21.0
protobuf==4.25.1
pydantic==2.5.1
pydantic_core==2.14.3
six==1.16.0
sniffio==1.3.0
tqdm==4.66.1
typing_extensions==4.8.0
wrapt==1.16.0
xmltodict==0.13.0
zipp==3.17.0
</details>

### How can we reproduce your problem?
```python
from openai import OpenAI
from openai._constants import RAW_RESPONSE_HEADER
from openai._response import APIResponse
from openai.types.chat import ChatCompletionSystemMessageParam

client = OpenAI()

api_response: APIResponse = client.chat.completions.create(
    # RAW_RESPONSE_HEADER changes the output type from ChatCompletion to APIResponse to preserve headers
    extra_headers={RAW_RESPONSE_HEADER: "true"},
    model="gpt-4",
    messages=[ChatCompletionSystemMessageParam(content="Say datadog is awesome!", role="system")]
)
print("openai-processing-ms: ", api_response.headers.get("openai-processing-ms"))
openai_response = api_response.parse()
print("Response:", openai_response)
```

```
ddtrace-run python openai_processing_ms.py
```

### What is the result that you get?
```
Traceback (most recent call last):
  File "./openai_processing_ms.py", line 8, in <module>
    api_response: APIResponse = client.chat.completions.create(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/openai/_utils/_utils.py", line 270, in wrapper
    def wrapper(*args: object, **kwargs: object) -> object:
  File ".venv/lib/python3.11/site-packages/ddtrace/contrib/openai/patch.py", line 411, in patched_endpoint
    g.send((resp, err))
  File ".venv/lib/python3.11/site-packages/ddtrace/contrib/openai/patch.py", line 376, in _traced_endpoint
    hook.send((resp, err))
  File ".venv/lib/python3.11/site-packages/ddtrace/contrib/openai/_endpoint_hooks.py", line 71, in handle_request
    return self._record_response(pin, integration, span, args, kwargs, resp, error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/ddtrace/contrib/openai/_endpoint_hooks.py", line 275, in _record_response
    choices = resp.choices or []
              ^^^^^^^^^^^^
AttributeError: 'APIResponse' object has no attribute 'choices'
```
or on CI
```
resp = <APIResponse [200 OK] type=<class 'openai.types.chat.chat_completion.ChatCompletion'>>
error = None

    def _record_response(self, pin, integration, span, args, kwargs, resp, error):
        if not resp:
            return self._handle_response(pin, span, integration, resp)
        messages = kwargs.get("messages")
        if kwargs.get("stream"):
            est_num_message_tokens = 0
            estimated = False
            for m in messages:
                estimated, prompt_tokens = _compute_prompt_token_count(m.get("content", ""), kwargs.get("model"))
                est_num_message_tokens += prompt_tokens
            span.set_metric("openai.request.prompt_tokens_estimated", int(estimated))
            span.set_metric("openai.response.usage.prompt_tokens", est_num_message_tokens)
            return self._handle_response(pin, span, integration, resp)
>       choices = resp.choices or []
E       AttributeError: 'APIResponse' object has no attribute 'choices'

/usr/local/lib/python3.11/dist-packages/ddtrace/contrib/openai/_endpoint_hooks.py:275: AttributeError
```
### What is the result that you expected?
```
python openai_processing_ms.py            

openai-processing-ms:  343
Response: ChatCompletion(id='chatcmpl-***', choices=[Choice(finish_reason='stop', index=0, message=ChatCompletionMessage(content='Datadog is awesome!', role='assistant', function_call=None, tool_calls=None))], created=1700197780, model='gpt-4-0613', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=6, prompt_tokens=14, total_tokens=20))
```

**Comment by Tradunsky** [comment]
This potentially uses encapsulated API, however, they also encapsulated exceptions `openai._exceptions`, which I believe people still need to access as part of public API, so independently from how datadog handles openapi API, I would say headers and exceptions are still part of their public interface.

**Comment by Yun-Kim** [comment]
Hi @Tradunsky, thanks for reaching out!

I was able to reproduce your issue and am working on a fix. Just as an FYI, in order to tag all relevant tags/metrics as before we will need to internally parse the response (but will still return the original raw `APIResponse` object).

**Comment by Tradunsky** [comment]
Thank you for addressing that, @Yun-Kim 🙏🏻 

I hope OpenAI will consider making server-side latency ms and token counts as part of their public API instead of all users needing to access headers this way, which overrides the declared return type with another class type not using polymorphism. 

Once again, I very much appreciate Datadog's proactive community reaction here ❤️
