### ISSUE TITLE
Broken static files with Django + Whitenoise on 2.2.0

### ISSUE THREAD

**Issue by browniebroke** [DataDog/dd-trace-py#7646]
### Summary of problem

Trying to upgrade ddtrace from 2.1.7 to 2.2.0 on a Django project using [Whitenoise](https://whitenoise.readthedocs.io/en/latest/) and got the following error when trying to access a static file:

```
AttributeError: This WhiteNoiseFileResponse instance has no `content` attribute. Use `streaming_content` instead.
```

```
AttributeError: This WhiteNoiseFileResponse instance has no `content` attribute. Use `streaming_content` instead.
  File "django/core/handlers/asgi.py", line 160, in __call__
    await self.handle(scope, receive, send)
  File "django/core/handlers/asgi.py", line 183, in handle
    response = await self.get_response_async(request)
  File "ddtrace/contrib/django/_asgi.py", line 35, in traced_get_response_async
    _after_request_tags(pin, span, request, response)
  File "ddtrace/contrib/django/utils.py", line 398, in _after_request_tags
    core.dispatch("django.after_request_headers.finalize", response.content, None)
  File "django/http/response.py", line 458, in content
    raise AttributeError(
```

Seems like this PR might be related: #7011

### Which version of dd-trace-py are you using?

2.2.0

### Which version of pip are you using?

23.3.1

### Which libraries and their versions are you using?

 _Not the full list, I tried to put the relevant ones here, but if that's not enough I'll try to get it_

<details>
  <summary>`pip freeze`</summary>
 
  

  whitenoise==6.6.0
  django==4.2.7
  gunicorn==21.2.0
  uvicorn==0.24.0.post1
</details>

### What is the result that you get?

500 error when loading static files, so broken styling on the page.

### What is the result that you expected?

Static files should load fine

**Comment by mzaveiro** [comment]
I'm seeing the same issue with `StreamingHttpResponse`. 

```
    raise AttributeError(
AttributeError: This StreamingHttpResponse instance has no `content` attribute. Use `streaming_content` instead.
```

Using Django 4.2.7 with uvicorn.

**Comment by smirnoffs** [comment]
Same for me with ddtrace==2.2.0 and Whitenoise.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/asgi/middleware.py", line 275, in __call__
    reraise(exc_type, exc_val, exc_tb)
  File "/usr/local/lib/python3.11/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/asgi/middleware.py", line 270, in __call__
    return await self.app(scope, receive, wrapped_send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/asgi.py", line 160, in __call__
    await self.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/asgi.py", line 183, in handle
    response = await self.get_response_async(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/django/_asgi.py", line 35, in traced_get_response_async
    _after_request_tags(pin, span, request, response)
  File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/django/utils.py", line 398, in _after_request_tags
    core.dispatch("django.after_request_headers.finalize", response.content, None)
                                                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/http/response.py", line 475, in content
    raise AttributeError(
AttributeError: This WhiteNoiseFileResponse instance has no `content` attribute. Use `streaming_content` instead.
```

**Comment by jensenbox** [comment]
I look forward to this being released.

**Comment by jensenbox** [comment]
What release version will this land in?
