### ISSUE TITLE
[OpenTracer] Custom scope manager results in an exception

### ISSUE THREAD

**Issue by Maximilien-R** [DataDog/dd-trace-py#770]
Hi !

When initializing a `ddtrace.opentracer.Tracer` object with a custom scope manager it result on an `AttributeError`:

```python
from ddtrace.opentracer import Tracer
from opentracing.scope_managers.asyncio import AsyncioScopeManager
tracer = Tracer(service_name="service", scope_manager=AsyncioScopeManager())

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/m.raulic/.virtualenvs/ddtrace/lib/python3.6/site-packages/ddtrace/opentracer/tracer.py", line 80, in __init__
    dd_context_provider = get_context_provider_for_scope_manager(self._scope_manager)
  File "/Users/m.raulic/.virtualenvs/ddtrace/lib/python3.6/site-packages/ddtrace/opentracer/utils.py", line 12, in get_context_provider_for_scope_manager
    dd_context_provider = ddtrace.contrib.asyncio.context_provider
AttributeError: module 'ddtrace' has no attribute 'contrib'
```

This seems to be due to the way that `context_provider` are imported on https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/opentracer/utils.py.

**Comment by brettlangdon** [comment]
@Maximilien-R is this issue resolved for you now?

**Comment by brettlangdon** [comment]
Closing this issue for now, @Maximilien-R please feel free to re-open if you are still experiencing the problem.
