### ISSUE TITLE
KeyError: 'split_by_domain' 

### ISSUE THREAD

**Issue by viperfx** [DataDog/dd-trace-py#778]
```
  File "/Users/viperfx/.pyenv/versions/scrumgenius-env-3.6/lib/python3.6/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/viperfx/.pyenv/versions/scrumgenius-env-3.6/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/viperfx/.pyenv/versions/scrumgenius-env-3.6/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py", line 73, in _wrap_send
    span.service = _extract_service_name(instance, span, hostname=hostname)
  File "/Users/viperfx/.pyenv/versions/scrumgenius-env-3.6/lib/python3.6/site-packages/ddtrace/contrib/requests/connection.py", line 30, in _extract_service_name
    if cfg['split_by_domain'] and hostname:
KeyError: 'split_by_domain'
```

Happens on python 3.6 and 3.7

**Comment by brettlangdon** [comment]
@viperfx why was this closed? were you able to resolve this issue? what was the issue?

**Comment by benhoyt** [comment]
@viperfx @brettlangdon I'm having this same issue too -- any ideas?

**Comment by jd** [comment]
@benhoyt Can you provide more context, such as the `requests` version?

**Comment by benhoyt** [comment]
@jd Thanks, and sure. Here's a standalone script that reproduces this issue, including version numbers:

```python

# Python 3.7.4 on macOS
# ddtrace==0.29.0
# requests==2.22.0

import ddtrace
import ddtrace.contrib.requests
import requests

session = ddtrace.contrib.requests.TracedSession()

# NOTE: These lines don't actually prevent the KeyError
config = ddtrace.config.get_from(session)
config["service_name"] = "requests"
config["split_by_domain"] = False

# Raises KeyError: 'split_by_domain'
session.get("https://example.com/")
```

When you run it, here's what you get:

```
$ python3 ddbug.py 
Traceback (most recent call last):
  File "ddbug.py", line 18, in <module>
    session.get("https://example.com/")
  File "/Users/ben.hoyt/development/html-sitemap-generator/venv/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/ben.hoyt/development/html-sitemap-generator/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/ben.hoyt/development/html-sitemap-generator/venv/lib/python3.7/site-packages/ddtrace/contrib/requests/connection.py", line 73, in _wrap_send
    span.service = _extract_service_name(instance, span, hostname=hostname)
  File "/Users/ben.hoyt/development/html-sitemap-generator/venv/lib/python3.7/site-packages/ddtrace/contrib/requests/connection.py", line 30, in _extract_service_name
    if cfg['split_by_domain'] and hostname:
KeyError: 'split_by_domain'
Failed to send traces to Datadog Agent at localhost:8126: [Errno 61] Connection refused
```

So I don't know whether a patch call is required, or if I'm doing something else wrong. The [docs](http://pypi.datadoghq.com/trace/docs/other_integrations.html#requests) imply that you can use `TracedSession` instead of the patch call to get finer-grained control (which is what I want to do).

**Comment by jeremyahuang** [comment]
I think you are getting this error because the the TracedSession doesn't get it's PIN (patch info) unless `patch` is called. `ddtrace.config.get_from(session)` fails to find the config (because the PIN is missing), but returns a fresh dictionary instead of failing. 

Then when the session again uses `ddtrace.config.get_from` to get the config, it again returns a fresh, empty dictionary, causing the error. 

@jd Is it expected that `patch` needs to be called for `TracedSession` to work? Is it expected for `config.get_from` to return a dict that writes without throwing errors but also doesn't set the config?
