### ISSUE TITLE
Error installing ddtrace 1.18.3 with poetry 1.4.2

### ISSUE THREAD

**Issue by selynna** [DataDog/dd-trace-py#8340]
### Summary of problem

I am having trouble installing ddtrace 1.18.3 via `poetry install`.  It errors on a `KeyError: 'text'` at the very end.

### Which version of dd-trace-py are you using?

1.18.3

### Which version of pip are you using?

Not using pip, but Poetry (version 1.4.2)

### Which libraries and their versions are you using?

Poetry 1.4.2
Python 3.9.10
pyenv 
pyenv 2.3.35

### How can we reproduce your problem?

Code isn't open source 😓 

### What is the result that you get?

<details>
  <summary>Stack trace</summary>
```shell
  • Installing ddtrace (1.18.3)

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  <string>:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/_distutils/extension.py:134: UserWarning: Unknown Extension options: 'parallel'
    warnings.warn(msg)
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpni_56r7b/ddtrace-1.18.3/ddtrace/internal/_encoding.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  warning: ddtrace/internal/_utils.pxd:2:37: Declarations should not be declared inline.
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpni_56r7b/ddtrace-1.18.3/ddtrace/internal/_rand.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpni_56r7b/ddtrace-1.18.3/ddtrace/internal/_tagset.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpni_56r7b/ddtrace-1.18.3/ddtrace/profiling/_build.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpni_56r7b/ddtrace-1.18.3/ddtrace/profiling/collector/_task.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpni_56r7b/ddtrace-1.18.3/ddtrace/profiling/collector/_traceback.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpni_56r7b/ddtrace-1.18.3/ddtrace/profiling/collector/stack.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpni_56r7b/ddtrace-1.18.3/ddtrace/profiling/exporter/pprof.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpni_56r7b/ddtrace-1.18.3/ddtrace/profiling/_threading.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  [1/9] Cythonizing ddtrace/internal/_encoding.pyx
  [2/9] Cythonizing ddtrace/internal/_rand.pyx
  [3/9] Cythonizing ddtrace/internal/_tagset.pyx
  [4/9] Cythonizing ddtrace/profiling/_build.pyx
  [5/9] Cythonizing ddtrace/profiling/collector/_task.pyx
  [6/9] Cythonizing ddtrace/profiling/collector/_traceback.pyx
  [7/9] Cythonizing ddtrace/profiling/collector/stack.pyx
  [8/9] Cythonizing ddtrace/profiling/exporter/pprof.pyx
  [9/9] Cythonizing ddtrace/profiling/_threading.pyx
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'package_urls'
    warnings.warn(msg)
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
  !!
  
          ********************************************************************************
          The following seems to be defined outside of `pyproject.toml`:
  
          `license = 'BSD'`
  
          According to the spec (see the link below), however, setuptools CANNOT
          consider this value unless `license` is listed as `dynamic`.
  
          https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
  
          To prevent this problem, you can list `license` under `dynamic` or alternatively
          remove the `[project]` table from your file and rely entirely on other means of
          configuration.
          ********************************************************************************
  
  !!
    _handle_missing_dynamic(dist, project_table)
  /private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
    corresp(dist, value, root_dir)
  Traceback (most recent call last):
    File "/Users/selynna/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/selynna/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/selynna/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 404, in build_wheel
      return self._build_with_temp_dir(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 511, in <module>
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 159, in setup
      dist.parse_config_files()
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/_virtualenv.py", line 21, in parse_config_files
      result = old_parse_config_files(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 627, in parse_config_files
      pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 67, in apply_configuration
      return _apply(dist, config, filepath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 56, in apply
      _apply_project_table(dist, config, root_dir)
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 82, in _apply_project_table
      corresp(dist, value, root_dir)
    File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 183, in _license
      _set_config(dist, "license", val["text"])
                                   ~~~^^^^^^^^
  KeyError: 'text'
  

  at ~/.pyenv/versions/3.9.10/lib/python3.9/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with ddtrace (1.18.3) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "ddtrace (==1.18.3)"'.
```
</details>

### What is the result that you expected?

I expect that ddtrace should install.

**Comment by P403n1x87** [comment]
Something about the poetry virtual environment doesn't feel right
```
File "/Users/selynna/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
return _build_backend().build_wheel(wheel_directory, config_settings,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/private/var/folders/00/8n9b304x0d52q7fybwblq4v40000gn/T/tmpi200meqj/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 404, in build_wheel
return self._build_with_temp_dir(
^^^^^^^^^^^^^^^^^^^^^^^^^^
```
It looks like the environment is supposed to be Python 3.9, but the traceback shows Python 3.12 sources involved 🤔 . @selynna would you be able to remove the virtual environment, re-create it and try again? Could you also include details about the target platform, please? We publish wheels, so I'm surprised to see that the library is being installed from sources.

**Comment by selynna** [comment]
Figured it out - turns out my pyenv shell was linked to 3.12.x while everything else was 3.9.10. Ran `pyenv shell 3.9.10` to fix. Thanks for the help!
