### ISSUE TITLE
Tornado 6 integration broken

### ISSUE THREAD

**Issue by ekhaydarov** [DataDog/dd-trace-py#837]
Upgrading to Tornado 6 throws an error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ddtrace/monkey.py", line 175, in _patch_module
    imported_module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/ddtrace/contrib/tornado/__init__.py", line 91, in <module>
    from .stack_context import run_with_trace_context, TracerStackContext
  File "/usr/local/lib/python3.6/site-packages/ddtrace/contrib/tornado/stack_context.py", line 2, in <module>
    from tornado.stack_context import StackContextInconsistentError, _state
ModuleNotFoundError: No module named 'tornado.stack_context'
ddtrace.monkey.PatchException: integration not available
```

Was asked to raise it here by the datadog team for a more in depth discussion.

Let me know if i need to add any more details

Thanks

**Comment by brettlangdon** [comment]
@ekhaydarov thank you for reporting! We'll try to triage this one as soon as can.

**Comment by dkgramming** [comment]
It seems like `tornado.stack_context` was removed in Tornado 6.0.0: https://www.tornadoweb.org/en/stable/releases/v6.0.0.html#backwards-incompatible-changes

**Comment by majorgreys** [comment]
@ekhaydarov I am working on adding support for Tornado 6 to ddtrace. As @dkgramming highlighted, this depends on us replacing our use of `tornado.stack_context._state` to manage tracer contexts. If either of you wants to contribute insights or help, do drop me an email at tahir.butt@datadoghq.com or reach me at https://chat.datadoghq.com.

**Comment by abandali** [comment]
Now that https://github.com/DataDog/dd-trace-py/pull/1034 is merged, i think this issue can be closed?

**Comment by majorgreys** [comment]
I will go ahead and close this though the support is limited to Python 3.7. Extending this work to Python 3.6 is planned. @ekhaydarov, if Python 3.7 is not an option for your team, please re-open this issue and we can continue discussions here for 3.6 support.

**Comment by ekhaydarov** [comment]
thanks team. I think it will be less hassle for everyone involved if we just migrate to 3.7 in the near future.
