### ISSUE TITLE
TypeError: Env.v() got an unexpected keyword argument 'private' after bump to version 2.7.0

### ISSUE THREAD

**Issue by somnam** [DataDog/dd-trace-py#8604]
### Summary of problem
There's an error configuring Datadog tracing due to missing version constraint on `envier` dependency.
`envier` must be at `>= 0.5.0` for support of `private` keyword.

### Which version of dd-trace-py are you using?
`ddtrace 2.7.0`

### Which version of pip are you using?
`pip 23.1.2`

### Which libraries and their versions are you using?

<details>
  <summary>pip freeze | grep -iE 'ddtrace|envier'</summary>
  ddtrace==2.7.0
  envier==0.4.0
</details>

### How can we reproduce your problem?
Update `ddtrace` to `2.7.0` without automatically bumping `envier` to version `>= 0.5.0`

### What is the result that you get?
```
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/ddtrace/bootstrap/sitecustomize.py", line 116, in <module>
    import ddtrace.bootstrap.preload as preload  # Perform the actual initialisation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 208, in _exec_module
    self.loader.exec_module(module)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/ddtrace/bootstrap/preload.py", line 18, in <module>
    from ddtrace.settings.symbol_db import config as symdb_config  # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 208, in _exec_module
    self.loader.exec_module(module)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/ddtrace/settings/symbol_db.py", line 6, in <module>
    class SymbolDatabaseConfig(En):
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/ddtrace/settings/symbol_db.py", line 28, in SymbolDatabaseConfig
    _force = En.v(
             ^^^^^
TypeError: Env.v() got an unexpected keyword argument 'private'
```

### What is the result that you expected?
`ddtrace` should work and install a minimal required version of `envier`

**Comment by mabdinur** [comment]
Resolved by ddtrace v2.7.3
