### ISSUE TITLE
Unexpected TypeError while exporting events

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [DataDog/dd-trace-py#8996]
### Summary of problem

Error occurred in DD

### Which version of dd-trace-py are you using?

ddtrace = "^2.0.0"

from our `poetry.lock` file

### Which version of pip are you using?

not sure; production system

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?

unsure, we're seeing `Unexpected error while exporting events. Please report this bug to https://github.com/DataDog/dd-trace-py/issues`

### What is the result that you get?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ddtrace/profiling/scheduler.py", line 65, in flush
    exp.export(events, start, self._last_export)
  File "/usr/local/lib/python3.10/site-packages/ddtrace/profiling/exporter/http.py", line 218, in export
    "tags_profiler": self._get_tags(service),
  File "/usr/local/lib/python3.10/site-packages/ddtrace/profiling/exporter/http.py", line 155, in _get_tags
    return ",".join(tag + ":" + value for tag, value in tags.items())
  File "/usr/local/lib/python3.10/site-packages/ddtrace/profiling/exporter/http.py", line 155, in <genexpr>
    return ",".join(tag + ":" + value for tag, value in tags.items())
TypeError: can only concatenate str (not "int") to str
```

### What is the result that you expected?

No error

**Comment by mewc** [comment]
also getting this

```
http://localhost:8126/profiling/v1/input

{
http.fragment: ,
http.method: POST,
http.query: ,
http.response.status_code: 502,
reason: Bad Gateway,
thread.id: 140156566505216,
thread.name: ddtrace.profiling.scheduler:Scheduler
}

{
http.fragment: ,
http.method: POST,
http.query: ,
http.response.status_code: 403,
reason: Forbidden,
thread.id: 140156566505216,
thread.name: ddtrace.profiling.scheduler:Scheduler
}
```

**Comment by mewc** [comment]
api key valid?

**Comment by Andrew-Chen-Wang** [comment]
I believe #9042 addresses this
