### ISSUE TITLE
Langchain v0.2+: ModuleNotFoundError: No module named 'langchain_community'

### ISSUE THREAD

**Issue by gruebel** [DataDog/dd-trace-py#9481]
### Summary of problem

The new `langchain` version 0.2+ doesn't come with `langchain-community` bundled anymore, and therefore the patching process results in an ugly exception.

```
Traceback (most recent call last):
  ...

  File "/app/main.py", line 12, in <module>
    from llm.anthropic_llm import AnthropicClaude3Opus
  File "/app/.venv/lib/python3.12/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/app/llm/anthropic_llm.py", line 3, in <module>
    from llm.base import BaseLlmExtractor
  File "/app/.venv/lib/python3.12/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/app/llm/base.py", line 6, in <module>
    from langchain.prompts import PromptTemplate
  File "/app/.venv/lib/python3.12/site-packages/ddtrace/vendor/wrapt/importer.py", line 177, in _exec_module
    notify_module_loaded(module)
  File "/app/.venv/lib/python3.12/site-packages/ddtrace/vendor/wrapt/decorators.py", line 470, in _synchronized
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/ddtrace/vendor/wrapt/importer.py", line 136, in notify_module_loaded
    hook(module)
  File "/app/.venv/lib/python3.12/site-packages/ddtrace/_monkey.py", line 166, in on_import
    imported_module = importlib.import_module(path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/app/.venv/lib/python3.12/site-packages/ddtrace/contrib/langchain/__init__.py", line 210, in <module>
    from . import patch as _patch
  File "/app/.venv/lib/python3.12/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "/app/.venv/lib/python3.12/site-packages/ddtrace/contrib/langchain/patch.py", line 9, in <module>
    import langchain_community
ModuleNotFoundError: No module named 'langchain_community'
```

### Which version of dd-trace-py are you using?

2.8.5 and 2.9.0rc9

### Which version of pip are you using?

24.0

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?

install `langchain` version 0.2+

**Comment by Yun-Kim** [comment]
Hi @gruebel, thanks for reaching out! We'll be working on a fix for this asap.

**Comment by emmettbutler** [comment]
this appears to duplicate #9368
